// Command genspec は登録表(registry.go)から components パッケージの
// EntitySpec / Components / InitializeComponents / AddEntity を生成する。
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"text/template"
)

func main() {
	out := flag.String("out", "components_gen.go", "出力先ファイルパス")
	flag.Parse()

	formatted, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, "genspec:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "genspec:", err)
		os.Exit(1)
	}
}

// generate は登録表から整形済みの生成コードを返す。
func generate() ([]byte, error) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, Registry); err != nil {
		return nil, fmt.Errorf("テンプレート展開に失敗した: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("生成コードのフォーマットに失敗した: %w\n%s", err, buf.String())
	}
	return formatted, nil
}

var tmpl = template.Must(template.New("gen").Parse(`// Code generated by genspec. DO NOT EDIT.

package components

import "github.com/mlange-42/ark/ecs"

// EntitySpec はエンティティ作成用の仕様定義。
// 付与するコンポーネントのセットを定義し、AddEntity でECSエンティティに変換される。
type EntitySpec struct {
{{- range .}}
	{{.Field}} *{{.Type}} // {{.Comment}}
{{- end}}
}

// Components はECSコンポーネントのハンドル束。
// 各コンポーネント型の型付き *ecs.Map[T] を保持し、Add/Has/Get やクエリに使用される。
type Components struct {
{{- range .}}
	{{.Field}} *ecs.Map[{{.Type}}] // {{.Comment}}
{{- end}}
}

// InitializeComponents は全コンポーネント型を Ark のワールドに登録し、
// 各フィールドに型付き Map ハンドルを割り当てる。
func (c *Components) InitializeComponents(world *ecs.World) error {
{{- range .}}
	c.{{.Field}} = ecs.NewMap[{{.Type}}](world)
{{- end}}
	return nil
}

// AddEntity は EntitySpec から新しいエンティティを生成し、非nilな各フィールドを
// 対応するコンポーネントとして付与する。
func (c *Components) AddEntity(world *ecs.World, spec *EntitySpec) ecs.Entity {
	entity := world.NewEntity()
{{- range .}}
	addComp(c.{{.Field}}, entity, spec.{{.Field}})
{{- end}}
	return entity
}
`))
