[sprite_sheet.field]
texture_image = "file/textures/game.png"
[sprite_sheet.field.sprites]
exterior = { x = 0,   y = 0, width = 32, height = 32 }
wall_generic = { x = 32,  y = 0, width = 32, height = 32 }
floor = { x = 64,  y = 0, width = 32, height = 32 }
player = { x = 160, y = 0, width = 32, height = 32 }
warp_next = { x = 96,  y = 0, width = 32, height = 32 }
warp_escape = { x = 128, y = 0, width = 32, height = 32 }
red_ball = { x = 192, y = 0, width = 32, height = 32 }
dirt_simple = { x = 224, y = 0, width = 32, height = 32 }
reserved_8 = { x = 0,   y = 32, width = 32, height = 32 }
reserved_9 = { x = 32,  y = 32, width = 32, height = 32 }
wall_top = { x = 64,  y = 32, width = 32, height = 32 }
wall_bottom = { x = 96,  y = 32, width = 32, height = 32 }
wall_left = { x = 128, y = 32, width = 32, height = 32 }
wall_right = { x = 160, y = 32, width = 32, height = 32 }
wall_corner_tl = { x = 192, y = 32, width = 32, height = 32 }
wall_corner_tr = { x = 224, y = 32, width = 32, height = 32 }
wall_corner_bl = { x = 0,   y = 64, width = 32, height = 32 }
wall_corner_br = { x = 32,  y = 64, width = 32, height = 32 }
field_item = { x = 64,  y = 64, width = 32, height = 32 }
prop_table = { x = 96,  y = 64, width = 32, height = 32 }
prop_chair = { x = 128, y = 64, width = 32, height = 32 }
prop_bookshelf = { x = 160, y = 64, width = 32, height = 32 }
prop_barrel = { x = 192, y = 64, width = 32, height = 32 }
prop_crate = { x = 224, y = 64, width = 32, height = 32 }

# ================

[sprite_sheet.bg_title1]
texture_image = "file/bg/title1.png"
[sprite_sheet.bg_title1.sprites]
background = { x = 0, y = 0, width = 960, height = 720 }
