[sprite_sheet.field]
texture_image = "file/textures/game.png"
sprites = [
    # Exterior
    { x = 0,   y = 0, width = 32, height = 32 }, # Sprite 0
    # Wall
    { x = 32,  y = 0, width = 32, height = 32 }, # Sprite 1
    # Floor
    { x = 64,  y = 0, width = 32, height = 32 }, # Sprite 2
    # Player
    { x = 160, y = 0, width = 32, height = 32 }, # Sprite 3
    # WarpNext
    { x = 96,  y = 0, width = 32, height = 32 }, # Sprite 4
    # WarpEscape
    { x = 128, y = 0, width = 32, height = 32 }, # Sprite 5
    # Red Ball
    { x = 192, y = 0, width = 32, height = 32 }, # Sprite 6
]

[sprite_sheet.bg_title1]
texture_image = "file/bg/title1.png"
sprites = [
    { x = 0, y = 0, width = 960, height = 720 },
]

[sprite_sheet.bg_black1]
texture_image = "file/bg/black1.png"
sprites = [
    { x = 0, y = 0, width = 960, height = 720 },
]

[sprite_sheet.bg_urban1]
texture_image = "file/bg/urban1.png"
sprites = [
    { x = 0, y = 0, width = 960, height = 720 },
]

[sprite_sheet.bg_crystal1]
texture_image = "file/bg/crystal1.png"
sprites = [
    { x = 0, y = 0, width = 960, height = 720 },
]
