[sprite_sheet.field]
texture_image = "file/textures/game.png"
[sprite_sheet.field.sprites]
exterior = { x = 0,   y = 0, width = 32, height = 32 }
player = { x = 160, y = 0, width = 32, height = 32 }
warp_next = { x = 96,  y = 0, width = 32, height = 32 }
warp_escape = { x = 128, y = 0, width = 32, height = 32 }
red_ball = { x = 192, y = 0, width = 32, height = 32 }

prop_lantern = { x = 32,  y = 64, width = 32, height = 32 }
field_item = { x = 64,  y = 64, width = 32, height = 32 }
prop_table = { x = 96,  y = 64, width = 32, height = 32 }
prop_chair = { x = 128, y = 64, width = 32, height = 32 }
prop_bookshelf = { x = 160, y = 64, width = 32, height = 32 }
prop_barrel = { x = 192, y = 64, width = 32, height = 32 }
prop_crate = { x = 224, y = 64, width = 32, height = 32 }

# ================

# オートタイル用スプライトシート
[sprite_sheet.tile]
texture_image = "file/textures/tile.png"
[sprite_sheet.tile.sprites]

# 土タイル16パターン（オートタイル）
# tile.png配置: y=0～64の範囲
dirt_0 = { x = 160, y = 0, width = 32, height = 32 }   # G: 完全孤立 (0000) - 全方向に境界
dirt_1 = { x = 96, y = 64, width = 32, height = 32 }   # C: T字下向き (0001) - 上だけ同じタイル
dirt_2 = { x = 128, y = 32, width = 32, height = 32 }  # D: 横通し (0010) - 右だけ同じタイル
dirt_3 = { x = 0, y = 64, width = 32, height = 32 }    # 7: 左下外角 (0011) - 上右に同じタイル
dirt_4 = { x = 96, y = 0, width = 32, height = 32 }    # A: T字上向き (0100) - 下だけ同じタイル
dirt_5 = { x = 96, y = 32, width = 32, height = 32 }   # B: 縦通し (0101) - 上下に同じタイル
dirt_6 = { x = 0, y = 0, width = 32, height = 32 }     # 1: 左上外角 (0110) - 下右に同じタイル
dirt_7 = { x = 0, y = 32, width = 32, height = 32 }    # 4: 左側境界のみ (0111) - 上右下に同じタイル
dirt_8 = { x = 192, y = 32, width = 32, height = 32 }  # F: T字左向き (1000) - 左だけ同じタイル
dirt_9 = { x = 64, y = 64, width = 32, height = 32 }   # 9: 右下外角 (1001) - 上左に同じタイル
dirt_10 = { x = 160, y = 32, width = 32, height = 32 } # E: T字右向き (1010) - 左右に同じタイル
dirt_11 = { x = 32, y = 64, width = 32, height = 32 }  # 8: 下にのみ境界 (1011) - 上左右に同じタイル
dirt_12 = { x = 64, y = 0, width = 32, height = 32 }   # 3: 右上外角 (1100) - 下左に同じタイル
dirt_13 = { x = 64, y = 32, width = 32, height = 32 }  # 6: 右にのみ境界 (1101) - 上下左に同じタイル
dirt_14 = { x = 32, y = 0, width = 32, height = 32 }   # 2: 上だけ境界 (1110) - 左下右に同じタイル
dirt_15 = { x = 32, y = 32, width = 32, height = 32 }  # 5: 全方向同じ (1111) - 4面すべて境界なし

# 壁タイル16パターン（オートタイル）
# tile.png配置: y=96～160の範囲
wall_0 = { x = 160, y = 96, width = 32, height = 32 }  # G: 完全孤立 (0000) - 全方向に境界
wall_1 = { x = 96, y = 160, width = 32, height = 32 }   # C: T字下向き (0001) - 上だけ同じタイル
wall_2 = { x = 128, y = 128, width = 32, height = 32 }  # D: 横通し (0010) - 右だけ同じタイル
wall_3 = { x = 0, y = 160, width = 32, height = 32 }    # 7: 左下外角 (0011) - 上右に同じタイル
wall_4 = { x = 96, y = 96, width = 32, height = 32 }   # A: T字上向き (0100) - 下だけ同じタイル
wall_5 = { x = 96, y = 128, width = 32, height = 32 }   # B: 縦通し (0101) - 上下に同じタイル
wall_6 = { x = 0, y = 96, width = 32, height = 32 }    # 1: 左上外角 (0110) - 下右に同じタイル
wall_7 = { x = 0, y = 128, width = 32, height = 32 }    # 4: 左側境界のみ (0111) - 上右下に同じタイル
wall_8 = { x = 192, y = 128, width = 32, height = 32 }  # F: T字左向き (1000) - 左だけ同じタイル
wall_9 = { x = 64, y = 160, width = 32, height = 32 }   # 9: 右下外角 (1001) - 上左に同じタイル
wall_10 = { x = 160, y = 128, width = 32, height = 32 } # E: T字右向き (1010) - 左右に同じタイル
wall_11 = { x = 32, y = 160, width = 32, height = 32 }  # 8: 下にのみ境界 (1011) - 上左右に同じタイル
wall_12 = { x = 64, y = 96, width = 32, height = 32 }  # 3: 右上外角 (1100) - 下左に同じタイル
wall_13 = { x = 64, y = 128, width = 32, height = 32 }  # 6: 右にのみ境界 (1101) - 上下左に同じタイル
wall_14 = { x = 32, y = 96, width = 32, height = 32 }  # 2: 上だけ境界 (1110) - 左下右に同じタイル
wall_15 = { x = 32, y = 128, width = 32, height = 32 }  # 5: 全方向同じ (1111) - 4面すべて境界なし

# フロアタイル16パターン（オートタイル）
# tile.png配置: y=192～256の範囲
floor_0 = { x = 160, y = 192, width = 32, height = 32 }  # G: 完全孤立 (0000) - 全方向に境界
floor_1 = { x = 96, y = 256, width = 32, height = 32 }   # C: T字下向き (0001) - 上だけ同じタイル
floor_2 = { x = 128, y = 224, width = 32, height = 32 }  # D: 横通し (0010) - 右だけ同じタイル
floor_3 = { x = 0, y = 256, width = 32, height = 32 }    # 7: 左下外角 (0011) - 上右に同じタイル
floor_4 = { x = 96, y = 192, width = 32, height = 32 }   # A: T字上向き (0100) - 下だけ同じタイル
floor_5 = { x = 96, y = 224, width = 32, height = 32 }   # B: 縦通し (0101) - 上下に同じタイル
floor_6 = { x = 0, y = 192, width = 32, height = 32 }    # 1: 左上外角 (0110) - 下右に同じタイル
floor_7 = { x = 0, y = 224, width = 32, height = 32 }    # 4: 左側境界のみ (0111) - 上右下に同じタイル
floor_8 = { x = 192, y = 224, width = 32, height = 32 }  # F: T字左向き (1000) - 左だけ同じタイル
floor_9 = { x = 64, y = 256, width = 32, height = 32 }   # 9: 右下外角 (1001) - 上左に同じタイル
floor_10 = { x = 160, y = 224, width = 32, height = 32 } # E: T字右向き (1010) - 左右に同じタイル
floor_11 = { x = 32, y = 256, width = 32, height = 32 }  # 8: 下にのみ境界 (1011) - 上左右に同じタイル
floor_12 = { x = 64, y = 192, width = 32, height = 32 }  # 3: 右上外角 (1100) - 下左に同じタイル
floor_13 = { x = 64, y = 224, width = 32, height = 32 }  # 6: 右にのみ境界 (1101) - 上下左に同じタイル
floor_14 = { x = 32, y = 192, width = 32, height = 32 }  # 2: 上だけ境界 (1110) - 左下右に同じタイル
floor_15 = { x = 32, y = 224, width = 32, height = 32 }  # 5: 全方向同じ (1111) - 4面すべて境界なし

# ================

[sprite_sheet.bg_title1]
texture_image = "file/bg/title1.png"
[sprite_sheet.bg_title1.sprites]
background = { x = 0, y = 0, width = 960, height = 720 }
