[[chunk]]
name = '11x6_small_office'
weight = 80
palettes = ['standard']
map = "@@@@@#@@@@.\n@@@@@#@@@@.\n@@@@@#@@@@.\n@@@@@#@@@B.\n@@@@A#+####\n...........\n"
spawn_points = []

[chunk.Size]
W = 11
H = 6

[[chunk.placements]]
chunks = ['5x5_meeting_room']
id = 'A'

[[chunk.placements]]
chunks = ['4x4_storage']
id = 'B'

[[chunk]]
name = '15x10_office_building'
weight = 60
palettes = ['standard']
map = "@@@@@.....@@@@@\n@@@@@.....@@@@@\n@@@@@.....@@@@@\n@@@@@.....@@@@@\n@@@@A.....@@@@B\n######...######\n@@@@@#...#.....\n@@@@@+...+.@@@.\n@@@@@#...#.@@@.\n@@@@C#...#.@@D.\n"
spawn_points = []

[chunk.Size]
W = 15
H = 10

[[chunk.placements]]
chunks = ['5x5_meeting_room']
id = 'A'

[[chunk.placements]]
chunks = ['5x5_meeting_room']
id = 'B'

[[chunk.placements]]
chunks = ['5x4_office']
id = 'C'

[[chunk.placements]]
chunks = ['3x3_bedroom']
id = 'D'
