[[chunk]]
name = '20x20_debug_town'
weight = 100
palettes = ['standard', 'town']
map = """
####################
#..................#
#..................#
#..................#
#..................#
#..................#
#..................#
#..................#
#..................#
#........2$1.......#
#........K..A......#
#..................#
#..................#
#..................#
#..................#
#..................#
#..................#
#..................#
#..................#
####################
"""
placements = []

[[chunk.spawn_points]]
x = 10
y = 10

[chunk.Size]
W = 20
H = 20
