[[chunk]]
name = '10x10_small_room'
weight = 100
palettes = ['standard']
map = """
..........
..........
..........
...CTC....
..........
..........
..........
..........
.X..B.....
..........
"""
placements = []
spawn_points = []

[chunk.Size]
W = 10
H = 10
