package cmd

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"os"
	"text/template"

	"github.com/kijimaD/ruins/internal/components/genspec"
	"github.com/urfave/cli/v3"
)

// CmdGenComponents は genspec.Registry から components パッケージの
// EntitySpec / Components / InitializeComponents / AddEntity を生成するサブコマンド。
// 通常はトップの //go:generate から呼ばれる。
var CmdGenComponents = &cli.Command{
	Name:  "gencomponents",
	Usage: "generate component definitions such as EntitySpec and Components from the registry",
	Flags: []cli.Flag{
		&cli.StringFlag{
			Name:  "out",
			Value: "internal/components/components_gen.go",
			Usage: "output file path",
		},
	},
	Action: runGenComponents,
}

func runGenComponents(_ context.Context, c *cli.Command) error {
	formatted, err := generateComponents()
	if err != nil {
		return err
	}
	if err := os.WriteFile(c.String("out"), formatted, 0o644); err != nil {
		return fmt.Errorf("failed to write generated code: %w", err)
	}
	fmt.Printf("Generated %s\n", c.String("out"))
	return nil
}

// generateComponents は登録表から整形済みの生成コードを返す。
// format.Source を通すため、返り値がGoとして妥当でなければエラーになる。
func generateComponents() ([]byte, error) {
	var buf bytes.Buffer
	if err := componentsTmpl.Execute(&buf, genspec.Registry); err != nil {
		return nil, fmt.Errorf("failed to expand template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("failed to format generated code: %w\n%s", err, buf.String())
	}
	return formatted, nil
}

var componentsTmpl = template.Must(template.New("gen").Parse(`// Code generated by "ruins gencomponents". DO NOT EDIT.

package components

import "github.com/mlange-42/ark/ecs"

// EntitySpec is the specification used to create an entity.
// It defines the set of components to attach, which AddEntity converts into an ECS entity.
type EntitySpec struct {
{{- range .}}
	{{.Field}} *{{.Field}}
{{- end}}
}

// Components is the bundle of ECS component handles.
// It holds a typed *ecs.Map[T] for each component type, used by Add/Has/Get and queries.
type Components struct {
{{- range .}}
	{{.Field}} *ecs.Map[{{.Field}}]
{{- end}}
}

// InitializeComponents registers every component type with the Ark world
// and assigns a typed Map handle to each field.
func (c *Components) InitializeComponents(world *ecs.World) error {
{{- range .}}
	c.{{.Field}} = ecs.NewMap[{{.Field}}](world)
{{- end}}
	return nil
}

// AddEntity creates a new entity from an EntitySpec and attaches each non-nil field
// as its corresponding component.
func (c *Components) AddEntity(world *ecs.World, spec *EntitySpec) ecs.Entity {
	entity := world.NewEntity()
{{- range .}}
	addComp(c.{{.Field}}, entity, spec.{{.Field}})
{{- end}}
	return entity
}
`))
