package cmd

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"os"
	"text/template"

	"github.com/kijimaD/ruins/internal/components/genspec"
	"github.com/urfave/cli/v3"
)

// CmdGenComponents は genspec.Registry から components パッケージの
// EntitySpec / Components / InitializeComponents / AddEntity を生成するサブコマンド。
// 通常はトップの //go:generate から呼ばれる。
var CmdGenComponents = &cli.Command{
	Name:  "gencomponents",
	Usage: "コンポーネント定義(EntitySpec/Components等)を登録表から生成する",
	Flags: []cli.Flag{
		&cli.StringFlag{
			Name:  "out",
			Value: "internal/components/components_gen.go",
			Usage: "出力先ファイルパス",
		},
	},
	Action: runGenComponents,
}

func runGenComponents(_ context.Context, c *cli.Command) error {
	formatted, err := generateComponents()
	if err != nil {
		return err
	}
	if err := os.WriteFile(c.String("out"), formatted, 0o644); err != nil {
		return fmt.Errorf("生成コードの書き込みに失敗した: %w", err)
	}
	fmt.Printf("Generated %s\n", c.String("out"))
	return nil
}

// generateComponents は登録表から整形済みの生成コードを返す。
// format.Source を通すため、返り値がGoとして妥当でなければエラーになる。
func generateComponents() ([]byte, error) {
	var buf bytes.Buffer
	if err := componentsTmpl.Execute(&buf, genspec.Registry); err != nil {
		return nil, fmt.Errorf("テンプレート展開に失敗した: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("生成コードのフォーマットに失敗した: %w\n%s", err, buf.String())
	}
	return formatted, nil
}

var componentsTmpl = template.Must(template.New("gen").Parse(`// Code generated by "ruins gencomponents". DO NOT EDIT.

package components

import "github.com/mlange-42/ark/ecs"

// EntitySpec はエンティティ作成用の仕様定義。
// 付与するコンポーネントのセットを定義し、AddEntity でECSエンティティに変換される。
type EntitySpec struct {
{{- range .}}
	{{.Field}} *{{.Type}} // {{.Comment}}
{{- end}}
}

// Components はECSコンポーネントのハンドル束。
// 各コンポーネント型の型付き *ecs.Map[T] を保持し、Add/Has/Get やクエリに使用される。
type Components struct {
{{- range .}}
	{{.Field}} *ecs.Map[{{.Type}}] // {{.Comment}}
{{- end}}
}

// InitializeComponents は全コンポーネント型を Ark のワールドに登録し、
// 各フィールドに型付き Map ハンドルを割り当てる。
func (c *Components) InitializeComponents(world *ecs.World) error {
{{- range .}}
	c.{{.Field}} = ecs.NewMap[{{.Type}}](world)
{{- end}}
	return nil
}

// AddEntity は EntitySpec から新しいエンティティを生成し、非nilな各フィールドを
// 対応するコンポーネントとして付与する。
func (c *Components) AddEntity(world *ecs.World, spec *EntitySpec) ecs.Entity {
	entity := world.NewEntity()
{{- range .}}
	addComp(c.{{.Field}}, entity, spec.{{.Field}})
{{- end}}
	return entity
}
`))
