// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

// Defines values for AmmoTag.
const (
	EnergyCell AmmoTag = "energy_cell"
	N9mm       AmmoTag = "9mm"
	Rifle      AmmoTag = "rifle"
	Shell      AmmoTag = "shell"
)

// Defines values for AttackCategory.
const (
	BOW     AttackCategory = "BOW"
	CANON   AttackCategory = "CANON"
	FIST    AttackCategory = "FIST"
	HANDGUN AttackCategory = "HANDGUN"
	RIFLE   AttackCategory = "RIFLE"
	SPEAR   AttackCategory = "SPEAR"
	SWORD   AttackCategory = "SWORD"
)

// Defines values for Element.
const (
	ElementCHILL   Element = "CHILL"
	ElementFIRE    Element = "FIRE"
	ElementNONE    Element = "NONE"
	ElementPHOTON  Element = "PHOTON"
	ElementTHUNDER Element = "THUNDER"
)

// Defines values for EquipSlot.
const (
	EquipSlotARMS    EquipSlot = "ARMS"
	EquipSlotFEET    EquipSlot = "FEET"
	EquipSlotHANDS   EquipSlot = "HANDS"
	EquipSlotHEAD    EquipSlot = "HEAD"
	EquipSlotLEGS    EquipSlot = "LEGS"
	EquipSlotTORSO   EquipSlot = "TORSO"
	EquipSlotWEAPON1 EquipSlot = "WEAPON1"
	EquipSlotWEAPON2 EquipSlot = "WEAPON2"
	EquipSlotWEAPON3 EquipSlot = "WEAPON3"
	EquipSlotWEAPON4 EquipSlot = "WEAPON4"
	EquipSlotWEAPON5 EquipSlot = "WEAPON5"
)

// Defines values for EquipmentCategory.
const (
	EquipmentCategoryARMS    EquipmentCategory = "ARMS"
	EquipmentCategoryFEET    EquipmentCategory = "FEET"
	EquipmentCategoryHANDS   EquipmentCategory = "HANDS"
	EquipmentCategoryHEAD    EquipmentCategory = "HEAD"
	EquipmentCategoryJEWELRY EquipmentCategory = "JEWELRY"
	EquipmentCategoryLEGS    EquipmentCategory = "LEGS"
	EquipmentCategoryTORSO   EquipmentCategory = "TORSO"
)

// Defines values for FactionMemberType.
const (
	FactionNeutral FactionMemberType = "FactionNeutral"
)

// Defines values for FoliageType.
const (
	FoliageTypeMinus1 FoliageType = -1
	FoliageTypeMinus3 FoliageType = -3
	FoliageTypeN0     FoliageType = 0
)

// Defines values for HealingValueType.
const (
	PERCENTAGE HealingValueType = "PERCENTAGE"
)

// Defines values for ShelterType.
const (
	ShelterTypeN0  ShelterType = 0
	ShelterTypeN10 ShelterType = 10
	ShelterTypeN5  ShelterType = 5
)

// Defines values for SpriteDepth.
const (
	SpriteDepthN0 SpriteDepth = 0
	SpriteDepthN1 SpriteDepth = 1
	SpriteDepthN2 SpriteDepth = 2
	SpriteDepthN3 SpriteDepth = 3
)

// Defines values for TargetGroup.
const (
	TargetGroupALLY   TargetGroup = "ALLY"
	TargetGroupENEMY  TargetGroup = "ENEMY"
	TargetGroupNONE   TargetGroup = "NONE"
	TargetGroupWEAPON TargetGroup = "WEAPON"
)

// Defines values for TargetNum.
const (
	ALL    TargetNum = "ALL"
	SINGLE TargetNum = "SINGLE"
)

// Defines values for UsableScene.
const (
	ANY    UsableScene = "ANY"
	BATTLE UsableScene = "BATTLE"
	FIELD  UsableScene = "FIELD"
)

// Defines values for WaterType.
const (
	WaterTypeMinus10 WaterType = -10
	WaterTypeMinus5  WaterType = -5
	WaterTypeN0      WaterType = 0
)

// Abilities 能力値
type Abilities struct {
	Agility   int32 `json:"agility"`
	Defense   int32 `json:"defense"`
	Dexterity int32 `json:"dexterity"`
	Sensation int32 `json:"sensation"`
	Strength  int32 `json:"strength"`
	Vitality  int32 `json:"vitality"`
}

// Ammo 弾薬設定
type Ammo struct {
	AccuracyBonus int32 `json:"accuracyBonus"`

	// AmmoTag 弾薬タグ
	AmmoTag     AmmoTag `json:"ammoTag"`
	DamageBonus int32   `json:"damageBonus"`
}

// AmmoTag 弾薬タグ
type AmmoTag string

// AttackCategory 攻撃種別
type AttackCategory string

// Book 本の設定
type Book struct {
	// Skill スキル本設定
	Skill       *SkillBook `json:"skill,omitempty"`
	TotalEffort int32      `json:"totalEffort"`
}

// CommandTable コマンドテーブル
type CommandTable struct {
	Entries []CommandTableEntry `json:"entries"`
	Name    string              `json:"name"`
}

// CommandTableEntry コマンドテーブルエントリ
type CommandTableEntry struct {
	Weapon string  `json:"weapon"`
	Weight float64 `json:"weight"`
}

// CommandTableList コマンドテーブル一覧
type CommandTableList struct {
	Data       []CommandTable `json:"data"`
	TotalCount int32          `json:"totalCount"`
}

// Consumable 消費可能アイテムの設定
type Consumable struct {
	// TargetGroup ターゲットグループ
	TargetGroup TargetGroup `json:"targetGroup"`

	// TargetNum ターゲット数
	TargetNum TargetNum `json:"targetNum"`

	// UsableScene 使用可能シーン
	UsableScene UsableScene `json:"usableScene"`
}

// Dialog 会話データ
type Dialog struct {
	MessageKey string `json:"messageKey"`
}

// DoorLockTriggerRaw 扉ロックトリガー
type DoorLockTriggerRaw = map[string]interface{}

// DoorRaw 扉ローデータ
type DoorRaw = map[string]interface{}

// DropTable ドロップテーブル
type DropTable struct {
	Entries []DropTableEntry `json:"entries"`
	Name    string           `json:"name"`
}

// DropTableEntry ドロップテーブルエントリ
type DropTableEntry struct {
	Material string  `json:"material"`
	Weight   float64 `json:"weight"`
}

// DropTableList ドロップテーブル一覧
type DropTableList struct {
	Data       []DropTable `json:"data"`
	TotalCount int32       `json:"totalCount"`
}

// DungeonGateTriggerRaw ダンジョン選択ゲートトリガー
type DungeonGateTriggerRaw = map[string]interface{}

// Element 攻撃属性
type Element string

// EnemyTable 敵テーブル
type EnemyTable struct {
	Entries []EnemyTableEntry `json:"entries"`
	Name    string            `json:"name"`
}

// EnemyTableEntry 敵テーブルエントリ
type EnemyTableEntry struct {
	EnemyName string  `json:"enemyName"`
	MaxDepth  int32   `json:"maxDepth"`
	MinDepth  int32   `json:"minDepth"`
	Weight    float64 `json:"weight"`
}

// EnemyTableList 敵テーブル一覧
type EnemyTableList struct {
	Data       []EnemyTable `json:"data"`
	TotalCount int32        `json:"totalCount"`
}

// EquipBonus 装備ボーナス
type EquipBonus struct {
	Agility   int32 `json:"agility"`
	Dexterity int32 `json:"dexterity"`
	Sensation int32 `json:"sensation"`
	Strength  int32 `json:"strength"`
	Vitality  int32 `json:"vitality"`
}

// EquipSlot 装備スロット。防具部位 + 武器スロット
type EquipSlot string

// EquipmentCategory 装備部位
type EquipmentCategory string

// Error エラーレスポンス
type Error struct {
	Message string `json:"message"`
}

// FactionMemberType 派閥タイプ
type FactionMemberType string

// Fire 遠距離攻撃設定
type Fire struct {
	Accuracy int32 `json:"accuracy"`

	// AmmoTag 弾薬タグ
	AmmoTag AmmoTag `json:"ammoTag"`

	// AttackCategory 攻撃種別
	AttackCategory AttackCategory `json:"attackCategory"`
	AttackCount    int32          `json:"attackCount"`
	Cost           int32          `json:"cost"`
	Damage         int32          `json:"damage"`

	// Element 攻撃属性
	Element      Element `json:"element"`
	MagazineSize int32   `json:"magazineSize"`
	ReloadEffort int32   `json:"reloadEffort"`

	// TargetGroup ターゲットグループ
	TargetGroup TargetGroup `json:"targetGroup"`

	// TargetNum ターゲット数
	TargetNum TargetNum `json:"targetNum"`
}

// FoliageType 植生タイプ
type FoliageType float32

// HealingValueType 回復量の計算方式
type HealingValueType string

// Item アイテム
type Item struct {
	// Ammo 弾薬設定
	Ammo     *Ammo    `json:"ammo,omitempty"`
	AnimKeys []string `json:"animKeys"`

	// Book 本の設定
	Book *Book `json:"book,omitempty"`

	// Consumable 消費可能アイテムの設定
	Consumable  *Consumable `json:"consumable,omitempty"`
	Description string      `json:"description"`

	// EquipBonus 装備ボーナス
	EquipBonus *EquipBonus `json:"equipBonus,omitempty"`

	// Fire 遠距離攻撃設定
	Fire           *Fire  `json:"fire,omitempty"`
	InflictsDamage *int32 `json:"inflictsDamage,omitempty"`

	// Melee 近接攻撃設定
	Melee *Melee `json:"melee,omitempty"`
	Name  string `json:"name"`

	// ProvidesHealing 回復効果
	ProvidesHealing   *ProvidesHealing `json:"providesHealing,omitempty"`
	ProvidesNutrition *int32           `json:"providesNutrition,omitempty"`
	SpriteKey         string           `json:"spriteKey"`
	SpriteSheetName   string           `json:"spriteSheetName"`
	Stackable         *bool            `json:"stackable,omitempty"`
	Value             int32            `json:"value"`

	// Weapon 武器マーカー
	Weapon *Weapon `json:"weapon,omitempty"`

	// Wearable 装備可能設定
	Wearable *Wearable `json:"wearable,omitempty"`
	Weight   *float64  `json:"weight,omitempty"`
}

// ItemList アイテム一覧レスポンス
type ItemList struct {
	Data       []Item `json:"data"`
	TotalCount int32  `json:"totalCount"`
}

// ItemTable アイテムテーブル
type ItemTable struct {
	Entries []ItemTableEntry `json:"entries"`
	Name    string           `json:"name"`
}

// ItemTableEntry アイテムテーブルエントリ
type ItemTableEntry struct {
	ItemName string  `json:"itemName"`
	MaxDepth int32   `json:"maxDepth"`
	MinDepth int32   `json:"minDepth"`
	Weight   float64 `json:"weight"`
}

// ItemTableList アイテムテーブル一覧
type ItemTableList struct {
	Data       []ItemTable `json:"data"`
	TotalCount int32       `json:"totalCount"`
}

// LightSource 光源設定
type LightSource struct {
	// Color RGBA色
	Color   RGBAColor `json:"color"`
	Enabled bool      `json:"enabled"`
	Radius  int32     `json:"radius"`
}

// Melee 近接攻撃設定
type Melee struct {
	Accuracy int32 `json:"accuracy"`

	// AttackCategory 攻撃種別
	AttackCategory AttackCategory `json:"attackCategory"`
	AttackCount    int32          `json:"attackCount"`
	Cost           int32          `json:"cost"`
	Damage         int32          `json:"damage"`

	// Element 攻撃属性
	Element Element `json:"element"`

	// TargetGroup ターゲットグループ
	TargetGroup TargetGroup `json:"targetGroup"`

	// TargetNum ターゲット数
	TargetNum TargetNum `json:"targetNum"`
}

// Member メンバー
type Member struct {
	// Abilities 能力値
	Abilities        Abilities `json:"abilities"`
	AnimKeys         []string  `json:"animKeys"`
	CommandTableName string    `json:"commandTableName"`

	// Dialog 会話データ
	Dialog        *Dialog `json:"dialog,omitempty"`
	DropTableName string  `json:"dropTableName"`

	// FactionType 派閥タイプ
	FactionType *FactionMemberType `json:"factionType,omitempty"`
	IsBoss      bool               `json:"isBoss"`

	// LightSource 光源設定
	LightSource     *LightSource `json:"lightSource,omitempty"`
	Name            string       `json:"name"`
	Player          *bool        `json:"player,omitempty"`
	SpriteKey       string       `json:"spriteKey"`
	SpriteSheetName string       `json:"spriteSheetName"`
}

// MemberList メンバー一覧レスポンス
type MemberList struct {
	Data       []Member `json:"data"`
	TotalCount int32    `json:"totalCount"`
}

// Palette パレット
type Palette struct {
	Description string                  `json:"description"`
	Id          string                  `json:"id"`
	Npcs        map[string]PaletteEntry `json:"npcs"`
	Props       map[string]PaletteEntry `json:"props"`
	Terrain     map[string]string       `json:"terrain"`
}

// PaletteEntry パレットエントリ
type PaletteEntry struct {
	Id   string `json:"id"`
	Tile string `json:"tile"`
}

// PaletteList パレット一覧
type PaletteList struct {
	Data       []Palette `json:"data"`
	TotalCount int32     `json:"totalCount"`
}

// Profession 職業
type Profession struct {
	// Abilities 能力値
	Abilities   Abilities         `json:"abilities"`
	Description string            `json:"description"`
	Equips      []ProfessionEquip `json:"equips"`
	Id          string            `json:"id"`
	Items       []ProfessionItem  `json:"items"`
	Name        string            `json:"name"`
	Skills      []ProfessionSkill `json:"skills"`
}

// ProfessionEquip 職業初期装備
type ProfessionEquip struct {
	Name string `json:"name"`

	// Slot 装備スロット。防具部位 + 武器スロット
	Slot EquipSlot `json:"slot"`
}

// ProfessionItem 職業初期所持アイテム
type ProfessionItem struct {
	Count int32  `json:"count"`
	Name  string `json:"name"`
}

// ProfessionList 職業一覧
type ProfessionList struct {
	Data       []Profession `json:"data"`
	TotalCount int32        `json:"totalCount"`
}

// ProfessionSkill 職業スキル初期値
type ProfessionSkill struct {
	Id    string `json:"id"`
	Value int32  `json:"value"`
}

// Prop 置物
type Prop struct {
	AnimKeys    []string `json:"animKeys"`
	BlockPass   bool     `json:"blockPass"`
	BlockView   bool     `json:"blockView"`
	Description string   `json:"description"`

	// Door 扉ローデータ
	Door *DoorRaw `json:"door,omitempty"`

	// DoorLockTrigger 扉ロックトリガー
	DoorLockTrigger *DoorLockTriggerRaw `json:"doorLockTrigger,omitempty"`

	// DungeonGateTrigger ダンジョン選択ゲートトリガー
	DungeonGateTrigger *DungeonGateTriggerRaw `json:"dungeonGateTrigger,omitempty"`

	// LightSource 光源設定
	LightSource *LightSource `json:"lightSource,omitempty"`
	Name        string       `json:"name"`

	// SpriteRender スプライトレンダー設定
	SpriteRender SpriteRender `json:"spriteRender"`

	// WarpEscapeTrigger 脱出ワープトリガー
	WarpEscapeTrigger *WarpEscapeTriggerRaw `json:"warpEscapeTrigger,omitempty"`

	// WarpNextTrigger 次階層ワープトリガー
	WarpNextTrigger *WarpNextTriggerRaw `json:"warpNextTrigger,omitempty"`
}

// PropList 置物一覧
type PropList struct {
	Data       []Prop `json:"data"`
	TotalCount int32  `json:"totalCount"`
}

// ProvidesHealing 回復効果
type ProvidesHealing struct {
	Amount int32   `json:"amount"`
	Ratio  float64 `json:"ratio"`

	// ValueType 回復量の計算方式
	ValueType HealingValueType `json:"valueType"`
}

// RGBAColor RGBA色
type RGBAColor struct {
	A uint8 `json:"a"`
	B uint8 `json:"b"`
	G uint8 `json:"g"`
	R uint8 `json:"r"`
}

// Recipe レシピ
type Recipe struct {
	Inputs []RecipeInput `json:"inputs"`
	Name   string        `json:"name"`
}

// RecipeInput レシピ素材
type RecipeInput struct {
	Amount int32  `json:"amount"`
	Name   string `json:"name"`
}

// RecipeList レシピ一覧レスポンス
type RecipeList struct {
	Data       []Recipe `json:"data"`
	TotalCount int32    `json:"totalCount"`
}

// ShelterType 遮蔽タイプ
type ShelterType float32

// SkillBook スキル本設定
type SkillBook struct {
	MaxLevel      int32  `json:"maxLevel"`
	RequiredLevel int32  `json:"requiredLevel"`
	TargetSkill   string `json:"targetSkill"`
}

// SpriteDepth スプライト描画深度
type SpriteDepth float32

// SpriteRender スプライトレンダー設定
type SpriteRender struct {
	// Depth スプライト描画深度
	Depth           SpriteDepth `json:"depth"`
	SpriteKey       string      `json:"spriteKey"`
	SpriteSheetName string      `json:"spriteSheetName"`
}

// SpriteSheet スプライトシート
type SpriteSheet struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

// SpriteSheetList スプライトシート一覧
type SpriteSheetList struct {
	Data       []SpriteSheet `json:"data"`
	TotalCount int32         `json:"totalCount"`
}

// TargetGroup ターゲットグループ
type TargetGroup string

// TargetNum ターゲット数
type TargetNum string

// Tile タイル
type Tile struct {
	BlockPass   bool   `json:"blockPass"`
	BlockView   bool   `json:"blockView"`
	Description string `json:"description"`

	// Foliage 植生タイプ
	Foliage FoliageType `json:"foliage"`
	Name    string      `json:"name"`

	// Shelter 遮蔽タイプ
	Shelter ShelterType `json:"shelter"`

	// SpriteRender スプライトレンダー設定
	SpriteRender SpriteRender `json:"spriteRender"`

	// Water 水タイプ
	Water WaterType `json:"water"`
}

// TileList タイル一覧
type TileList struct {
	Data       []Tile `json:"data"`
	TotalCount int32  `json:"totalCount"`
}

// UsableScene 使用可能シーン
type UsableScene string

// WarpEscapeTriggerRaw 脱出ワープトリガー
type WarpEscapeTriggerRaw = map[string]interface{}

// WarpNextTriggerRaw 次階層ワープトリガー
type WarpNextTriggerRaw = map[string]interface{}

// WaterType 水タイプ
type WaterType float32

// Weapon 武器マーカー
type Weapon = map[string]interface{}

// Wearable 装備可能設定
type Wearable struct {
	Defense int32 `json:"defense"`

	// EquipmentCategory 装備部位
	EquipmentCategory EquipmentCategory `json:"equipmentCategory"`
	InsulationCold    int32             `json:"insulationCold"`
	InsulationHeat    int32             `json:"insulationHeat"`
}

// CommandTablesCreateJSONRequestBody defines body for CommandTablesCreate for application/json ContentType.
type CommandTablesCreateJSONRequestBody = CommandTable

// CommandTablesUpdateJSONRequestBody defines body for CommandTablesUpdate for application/json ContentType.
type CommandTablesUpdateJSONRequestBody = CommandTable

// DropTablesCreateJSONRequestBody defines body for DropTablesCreate for application/json ContentType.
type DropTablesCreateJSONRequestBody = DropTable

// DropTablesUpdateJSONRequestBody defines body for DropTablesUpdate for application/json ContentType.
type DropTablesUpdateJSONRequestBody = DropTable

// EnemyTablesCreateJSONRequestBody defines body for EnemyTablesCreate for application/json ContentType.
type EnemyTablesCreateJSONRequestBody = EnemyTable

// EnemyTablesUpdateJSONRequestBody defines body for EnemyTablesUpdate for application/json ContentType.
type EnemyTablesUpdateJSONRequestBody = EnemyTable

// ItemTablesCreateJSONRequestBody defines body for ItemTablesCreate for application/json ContentType.
type ItemTablesCreateJSONRequestBody = ItemTable

// ItemTablesUpdateJSONRequestBody defines body for ItemTablesUpdate for application/json ContentType.
type ItemTablesUpdateJSONRequestBody = ItemTable

// ItemsCreateJSONRequestBody defines body for ItemsCreate for application/json ContentType.
type ItemsCreateJSONRequestBody = Item

// ItemsUpdateJSONRequestBody defines body for ItemsUpdate for application/json ContentType.
type ItemsUpdateJSONRequestBody = Item

// MembersCreateJSONRequestBody defines body for MembersCreate for application/json ContentType.
type MembersCreateJSONRequestBody = Member

// MembersUpdateJSONRequestBody defines body for MembersUpdate for application/json ContentType.
type MembersUpdateJSONRequestBody = Member

// PalettesCreateJSONRequestBody defines body for PalettesCreate for application/json ContentType.
type PalettesCreateJSONRequestBody = Palette

// PalettesUpdateJSONRequestBody defines body for PalettesUpdate for application/json ContentType.
type PalettesUpdateJSONRequestBody = Palette

// ProfessionsCreateJSONRequestBody defines body for ProfessionsCreate for application/json ContentType.
type ProfessionsCreateJSONRequestBody = Profession

// ProfessionsUpdateJSONRequestBody defines body for ProfessionsUpdate for application/json ContentType.
type ProfessionsUpdateJSONRequestBody = Profession

// PropsCreateJSONRequestBody defines body for PropsCreate for application/json ContentType.
type PropsCreateJSONRequestBody = Prop

// PropsUpdateJSONRequestBody defines body for PropsUpdate for application/json ContentType.
type PropsUpdateJSONRequestBody = Prop

// RecipesCreateJSONRequestBody defines body for RecipesCreate for application/json ContentType.
type RecipesCreateJSONRequestBody = Recipe

// RecipesUpdateJSONRequestBody defines body for RecipesUpdate for application/json ContentType.
type RecipesUpdateJSONRequestBody = Recipe

// SpriteSheetsCreateJSONRequestBody defines body for SpriteSheetsCreate for application/json ContentType.
type SpriteSheetsCreateJSONRequestBody = SpriteSheet

// SpriteSheetsUpdateJSONRequestBody defines body for SpriteSheetsUpdate for application/json ContentType.
type SpriteSheetsUpdateJSONRequestBody = SpriteSheet

// TilesCreateJSONRequestBody defines body for TilesCreate for application/json ContentType.
type TilesCreateJSONRequestBody = Tile

// TilesUpdateJSONRequestBody defines body for TilesUpdate for application/json ContentType.
type TilesUpdateJSONRequestBody = Tile
