// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

// Defines values for AmmoTag.
const (
	EnergyCell AmmoTag = "energy_cell"
	N9mm       AmmoTag = "9mm"
	Rifle      AmmoTag = "rifle"
	Shell      AmmoTag = "shell"
)

// Defines values for AttackCategory.
const (
	BOW     AttackCategory = "BOW"
	CANON   AttackCategory = "CANON"
	FIST    AttackCategory = "FIST"
	HANDGUN AttackCategory = "HANDGUN"
	RIFLE   AttackCategory = "RIFLE"
	SPEAR   AttackCategory = "SPEAR"
	SWORD   AttackCategory = "SWORD"
)

// Defines values for DispositionType.
const (
	Cowardly DispositionType = "cowardly"
	Hostile  DispositionType = "hostile"
	Neutral  DispositionType = "neutral"
)

// Defines values for Element.
const (
	ElementCHILL   Element = "CHILL"
	ElementFIRE    Element = "FIRE"
	ElementNONE    Element = "NONE"
	ElementPHOTON  Element = "PHOTON"
	ElementTHUNDER Element = "THUNDER"
)

// Defines values for EquipSlot.
const (
	EquipSlotARMS    EquipSlot = "ARMS"
	EquipSlotFEET    EquipSlot = "FEET"
	EquipSlotHANDS   EquipSlot = "HANDS"
	EquipSlotHEAD    EquipSlot = "HEAD"
	EquipSlotLEGS    EquipSlot = "LEGS"
	EquipSlotTORSO   EquipSlot = "TORSO"
	EquipSlotWEAPON1 EquipSlot = "WEAPON1"
	EquipSlotWEAPON2 EquipSlot = "WEAPON2"
	EquipSlotWEAPON3 EquipSlot = "WEAPON3"
	EquipSlotWEAPON4 EquipSlot = "WEAPON4"
	EquipSlotWEAPON5 EquipSlot = "WEAPON5"
)

// Defines values for EquipmentCategory.
const (
	EquipmentCategoryARMS    EquipmentCategory = "ARMS"
	EquipmentCategoryFEET    EquipmentCategory = "FEET"
	EquipmentCategoryHANDS   EquipmentCategory = "HANDS"
	EquipmentCategoryHEAD    EquipmentCategory = "HEAD"
	EquipmentCategoryJEWELRY EquipmentCategory = "JEWELRY"
	EquipmentCategoryLEGS    EquipmentCategory = "LEGS"
	EquipmentCategoryTORSO   EquipmentCategory = "TORSO"
)

// Defines values for FactionMemberType.
const (
	FactionNeutral FactionMemberType = "FactionNeutral"
)

// Defines values for FoliageType.
const (
	FoliageTypeMinus1 FoliageType = -1
	FoliageTypeMinus3 FoliageType = -3
	FoliageTypeN0     FoliageType = 0
)

// Defines values for HealingValueType.
const (
	PERCENTAGE HealingValueType = "PERCENTAGE"
)

// Defines values for MovementPatternType.
const (
	Patrol      MovementPatternType = "patrol"
	Random      MovementPatternType = "random"
	Stationary  MovementPatternType = "stationary"
	Swarm       MovementPatternType = "swarm"
	Territorial MovementPatternType = "territorial"
	WallHug     MovementPatternType = "wallHug"
	Wander      MovementPatternType = "wander"
)

// Defines values for ShelterType.
const (
	ShelterTypeN0  ShelterType = 0
	ShelterTypeN10 ShelterType = 10
	ShelterTypeN5  ShelterType = 5
)

// Defines values for SpriteDepth.
const (
	SpriteDepthN0 SpriteDepth = 0
	SpriteDepthN1 SpriteDepth = 1
	SpriteDepthN2 SpriteDepth = 2
	SpriteDepthN3 SpriteDepth = 3
)

// Defines values for TargetGroup.
const (
	TargetGroupALLY   TargetGroup = "ALLY"
	TargetGroupENEMY  TargetGroup = "ENEMY"
	TargetGroupNONE   TargetGroup = "NONE"
	TargetGroupWEAPON TargetGroup = "WEAPON"
)

// Defines values for TargetNum.
const (
	ALL    TargetNum = "ALL"
	SINGLE TargetNum = "SINGLE"
)

// Defines values for UsableScene.
const (
	ANY    UsableScene = "ANY"
	BATTLE UsableScene = "BATTLE"
	FIELD  UsableScene = "FIELD"
)

// Defines values for WaterType.
const (
	WaterTypeMinus10 WaterType = -10
	WaterTypeMinus5  WaterType = -5
	WaterTypeN0      WaterType = 0
)

// Abilities 能力値
type Abilities struct {
	// Agility 敏捷性。行動順に影響する
	Agility int32 `json:"agility"`

	// Defense 防御力。被ダメージを軽減する
	Defense int32 `json:"defense"`

	// Dexterity 器用さ。クリティカル率に影響する
	Dexterity int32 `json:"dexterity"`

	// Sensation 感覚。命中率と回避率に影響する
	Sensation int32 `json:"sensation"`

	// Strength 筋力。物理ダメージに影響する
	Strength int32 `json:"strength"`

	// Vitality 体力。HPに影響する
	Vitality int32 `json:"vitality"`
}

// Ammo 弾薬設定
type Ammo struct {
	// AccuracyBonus 命中率補正値
	AccuracyBonus int32 `json:"accuracyBonus"`

	// AmmoTag 弾薬の種類タグ
	AmmoTag AmmoTag `json:"ammoTag"`

	// DamageBonus ダメージ補正値
	DamageBonus int32 `json:"damageBonus"`
}

// AmmoTag 弾薬タグ
type AmmoTag string

// AttackCategory 攻撃種別
type AttackCategory string

// Book 本の設定
type Book struct {
	// Skill スキル本としての設定。未設定なら娯楽本
	Skill *SkillBook `json:"skill,omitempty"`

	// TotalEffort 読了に必要な総読書量
	TotalEffort int32 `json:"totalEffort"`
}

// CommandTable コマンドテーブル
type CommandTable struct {
	// Entries コマンドエントリのリスト
	Entries []CommandTableEntry `json:"entries"`

	// Name テーブル名
	Name string `json:"name"`
}

// CommandTableEntry コマンドテーブルエントリ
type CommandTableEntry struct {
	// Weapon 使用する武器名
	Weapon string `json:"weapon"`

	// Weight 選択される重み。大きいほど選ばれやすい
	Weight float64 `json:"weight"`
}

// CommandTableList コマンドテーブル一覧
type CommandTableList struct {
	// Data コマンドテーブルの配列
	Data []CommandTable `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// Consumable 消費可能アイテムの設定
type Consumable struct {
	// TargetGroup 効果の対象グループ
	TargetGroup TargetGroup `json:"targetGroup"`

	// TargetNum 効果の対象数
	TargetNum TargetNum `json:"targetNum"`

	// UsableScene 使用可能なシーン
	UsableScene UsableScene `json:"usableScene"`
}

// Dialog 会話データ
type Dialog struct {
	// MessageKey メッセージリソースのキー
	MessageKey string `json:"messageKey"`
}

// DispositionType 態度タイプ。エンティティの他者に対する初期態度を定義する
type DispositionType string

// DoorLockTriggerRaw 扉ロックトリガー
type DoorLockTriggerRaw = map[string]interface{}

// DoorRaw 扉ローデータ
type DoorRaw = map[string]interface{}

// DropTable ドロップテーブル
type DropTable struct {
	// Entries ドロップエントリのリスト
	Entries []DropTableEntry `json:"entries"`

	// Name テーブル名
	Name string `json:"name"`
}

// DropTableEntry ドロップテーブルエントリ
type DropTableEntry struct {
	// Material ドロップする素材名
	Material string `json:"material"`

	// Weight ドロップする重み。大きいほど選ばれやすい
	Weight float64 `json:"weight"`
}

// DropTableList ドロップテーブル一覧
type DropTableList struct {
	// Data ドロップテーブルの配列
	Data []DropTable `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// DungeonGateTriggerRaw ダンジョン選択ゲートトリガー
type DungeonGateTriggerRaw = map[string]interface{}

// Element 攻撃属性
type Element string

// EnemyTable 敵テーブル
type EnemyTable struct {
	// Entries 敵エントリのリスト
	Entries []EnemyTableEntry `json:"entries"`

	// Name テーブル名
	Name string `json:"name"`
}

// EnemyTableEntry 敵テーブルエントリ
type EnemyTableEntry struct {
	// EnemyName 出現する敵メンバー名
	EnemyName string `json:"enemyName"`

	// MaxDepth 出現する最大階層
	MaxDepth int32 `json:"maxDepth"`

	// MinDepth 出現する最小階層
	MinDepth int32 `json:"minDepth"`

	// Weight 出現する重み。大きいほど選ばれやすい
	Weight float64 `json:"weight"`
}

// EnemyTableList 敵テーブル一覧
type EnemyTableList struct {
	// Data 敵テーブルの配列
	Data []EnemyTable `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// EquipBonus 装備ボーナス
type EquipBonus struct {
	// Agility 敏捷性ボーナス
	Agility int32 `json:"agility"`

	// Dexterity 器用さボーナス
	Dexterity int32 `json:"dexterity"`

	// Sensation 感覚ボーナス
	Sensation int32 `json:"sensation"`

	// Strength 筋力ボーナス
	Strength int32 `json:"strength"`

	// Vitality 体力ボーナス
	Vitality int32 `json:"vitality"`
}

// EquipSlot 装備スロット。防具部位 + 武器スロット
type EquipSlot string

// EquipmentCategory 装備部位
type EquipmentCategory string

// Error エラーレスポンス
type Error struct {
	// Message エラーメッセージ
	Message string `json:"message"`
}

// FactionMemberType 派閥タイプ
type FactionMemberType string

// Fire 遠距離攻撃設定
type Fire struct {
	// Accuracy 命中率
	Accuracy int32 `json:"accuracy"`

	// AmmoTag 使用する弾薬の種類
	AmmoTag AmmoTag `json:"ammoTag"`

	// AttackCategory 攻撃種別
	AttackCategory AttackCategory `json:"attackCategory"`

	// AttackCount 1ターンあたりの攻撃回数
	AttackCount int32 `json:"attackCount"`

	// Cost 行動コスト
	Cost int32 `json:"cost"`

	// Damage ダメージ
	Damage int32 `json:"damage"`

	// Element 攻撃属性
	Element Element `json:"element"`

	// MagazineSize マガジン容量
	MagazineSize int32 `json:"magazineSize"`

	// ReloadEffort リロードに必要な行動力
	ReloadEffort int32 `json:"reloadEffort"`

	// TargetGroup 対象グループ
	TargetGroup TargetGroup `json:"targetGroup"`

	// TargetNum 対象数
	TargetNum TargetNum `json:"targetNum"`
}

// FoliageType 植生タイプ
type FoliageType float32

// HealingValueType 回復量の計算方式
type HealingValueType string

// Item アイテム
type Item struct {
	// Ammo 弾薬設定
	Ammo *Ammo `json:"ammo,omitempty"`

	// AnimKeys アニメーション用スプライトキーの配列
	AnimKeys []string `json:"animKeys"`

	// Book 本設定
	Book *Book `json:"book,omitempty"`

	// Consumable 消費アイテム設定
	Consumable *Consumable `json:"consumable,omitempty"`

	// Description アイテムの説明文
	Description string `json:"description"`

	// EquipBonus 装備ボーナス
	EquipBonus *EquipBonus `json:"equipBonus,omitempty"`

	// Fire 遠距離攻撃設定
	Fire *Fire `json:"fire,omitempty"`

	// InflictsDamage 投擲ダメージ。未設定なら投擲不可
	InflictsDamage *int32 `json:"inflictsDamage,omitempty"`

	// Melee 近接攻撃設定
	Melee *Melee `json:"melee,omitempty"`

	// Name アイテム名
	Name string `json:"name"`

	// ProvidesHealing 回復効果
	ProvidesHealing *ProvidesHealing `json:"providesHealing,omitempty"`

	// ProvidesNutrition 栄養価。未設定なら食べられない
	ProvidesNutrition *int32 `json:"providesNutrition,omitempty"`

	// SpriteKey スプライトキー
	SpriteKey string `json:"spriteKey"`

	// SpriteSheetName スプライトシート名
	SpriteSheetName string `json:"spriteSheetName"`

	// Stackable スタック可能かどうか
	Stackable *bool `json:"stackable,omitempty"`

	// Value 売買価格
	Value int32 `json:"value"`

	// Weapon 武器マーカー。存在すれば武器として扱う
	Weapon *Weapon `json:"weapon,omitempty"`

	// Wearable 防具設定
	Wearable *Wearable `json:"wearable,omitempty"`

	// Weight 重量。未設定なら0
	Weight *float64 `json:"weight,omitempty"`
}

// ItemList アイテム一覧レスポンス
type ItemList struct {
	// Data アイテムの配列
	Data []Item `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// ItemTable アイテムテーブル
type ItemTable struct {
	// Entries アイテムエントリのリスト
	Entries []ItemTableEntry `json:"entries"`

	// Name テーブル名
	Name string `json:"name"`
}

// ItemTableEntry アイテムテーブルエントリ
type ItemTableEntry struct {
	// ItemName 出現するアイテム名
	ItemName string `json:"itemName"`

	// MaxDepth 出現する最大階層
	MaxDepth int32 `json:"maxDepth"`

	// MinDepth 出現する最小階層
	MinDepth int32 `json:"minDepth"`

	// Weight 出現する重み。大きいほど選ばれやすい
	Weight float64 `json:"weight"`
}

// ItemTableList アイテムテーブル一覧
type ItemTableList struct {
	// Data アイテムテーブルの配列
	Data []ItemTable `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// LightSource 光源設定
type LightSource struct {
	// Color 光の色
	Color RGBAColor `json:"color"`

	// Enabled 光源が有効かどうか
	Enabled bool `json:"enabled"`

	// Radius 光の到達半径
	Radius int32 `json:"radius"`
}

// Melee 近接攻撃設定
type Melee struct {
	// Accuracy 命中率
	Accuracy int32 `json:"accuracy"`

	// AttackCategory 攻撃種別
	AttackCategory AttackCategory `json:"attackCategory"`

	// AttackCount 1ターンあたりの攻撃回数
	AttackCount int32 `json:"attackCount"`

	// Cost 行動コスト
	Cost int32 `json:"cost"`

	// Damage ダメージ
	Damage int32 `json:"damage"`

	// Element 攻撃属性
	Element Element `json:"element"`

	// TargetGroup 対象グループ
	TargetGroup TargetGroup `json:"targetGroup"`

	// TargetNum 対象数
	TargetNum TargetNum `json:"targetNum"`
}

// Member メンバー
type Member struct {
	// Abilities 基本能力値
	Abilities Abilities `json:"abilities"`

	// AnimKeys アニメーション用スプライトキーの配列
	AnimKeys []string `json:"animKeys"`

	// CommandTableName 参照するコマンドテーブル名
	CommandTableName string `json:"commandTableName"`

	// Dialog 会話データ。未設定なら会話不可
	Dialog *Dialog `json:"dialog,omitempty"`

	// Disposition 態度
	Disposition *DispositionType `json:"disposition,omitempty"`

	// DropTableName 参照するドロップテーブル名
	DropTableName string `json:"dropTableName"`

	// FactionType 所属する派閥。未設定なら敵対
	FactionType *FactionMemberType `json:"factionType,omitempty"`

	// IsBoss ボスモンスターかどうか
	IsBoss bool `json:"isBoss"`

	// LightSource 光源設定。未設定なら光源なし
	LightSource *LightSource `json:"lightSource,omitempty"`

	// MovementPattern 非戦闘時の移動パターン
	MovementPattern *MovementPatternType `json:"movementPattern,omitempty"`

	// Name メンバー名
	Name string `json:"name"`

	// Player プレイヤーキャラクターかどうか
	Player *bool `json:"player,omitempty"`

	// SpriteKey スプライトキー
	SpriteKey string `json:"spriteKey"`

	// SpriteSheetName スプライトシート名
	SpriteSheetName string `json:"spriteSheetName"`
}

// MemberList メンバー一覧レスポンス
type MemberList struct {
	// Data メンバーの配列
	Data []Member `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// MovementPatternType 非戦闘時の移動パターン
type MovementPatternType string

// Palette パレット
type Palette struct {
	// Description パレットの説明文
	Description string `json:"description"`

	// Id パレットID
	Id string `json:"id"`

	// Npcs NPCマッピング。マップ文字からNPCエントリへの対応
	Npcs map[string]PaletteEntry `json:"npcs"`

	// Props 置物マッピング。マップ文字から置物エントリへの対応
	Props map[string]PaletteEntry `json:"props"`

	// Terrain 地形マッピング。マップ文字からタイル名への対応
	Terrain map[string]string `json:"terrain"`
}

// PaletteEntry パレットエントリ
type PaletteEntry struct {
	// Id エントリID
	Id string `json:"id"`

	// Tile 対応するタイル名
	Tile string `json:"tile"`
}

// PaletteList パレット一覧
type PaletteList struct {
	// Data パレットの配列
	Data []Palette `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// Profession 職業
type Profession struct {
	// Abilities 基本能力値
	Abilities Abilities `json:"abilities"`

	// Description 職業の説明文
	Description string `json:"description"`

	// Equips 初期装備のリスト
	Equips []ProfessionEquip `json:"equips"`

	// Id 職業ID
	Id string `json:"id"`

	// Items 初期所持アイテムのリスト
	Items []ProfessionItem `json:"items"`

	// Name 職業名
	Name string `json:"name"`

	// Skills 初期スキルのリスト
	Skills []ProfessionSkill `json:"skills"`
}

// ProfessionEquip 職業初期装備
type ProfessionEquip struct {
	// Name 装備アイテム名
	Name string `json:"name"`

	// Slot 装備するスロット
	Slot EquipSlot `json:"slot"`
}

// ProfessionItem 職業初期所持アイテム
type ProfessionItem struct {
	// Count 所持数
	Count int32 `json:"count"`

	// Name アイテム名
	Name string `json:"name"`
}

// ProfessionList 職業一覧
type ProfessionList struct {
	// Data 職業の配列
	Data []Profession `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// ProfessionSkill 職業スキル初期値
type ProfessionSkill struct {
	// Id スキルID
	Id string `json:"id"`

	// Value 初期スキルレベル
	Value int32 `json:"value"`
}

// Prop 置物
type Prop struct {
	// AnimKeys アニメーション用スプライトキーの配列
	AnimKeys []string `json:"animKeys"`

	// BlockPass 通行を妨げるかどうか
	BlockPass bool `json:"blockPass"`

	// BlockView 視線を遮るかどうか
	BlockView bool `json:"blockView"`

	// Description 置物の説明文
	Description string `json:"description"`

	// Door 扉データ。設定すると開閉可能な扉として動作する
	Door *DoorRaw `json:"door,omitempty"`

	// DoorLockTrigger 扉ロックトリガー。設定すると鍵付き扉として動作する
	DoorLockTrigger *DoorLockTriggerRaw `json:"doorLockTrigger,omitempty"`

	// DungeonGateTrigger ダンジョン選択ゲートトリガー。調べるとダンジョン選択画面を開く
	DungeonGateTrigger *DungeonGateTriggerRaw `json:"dungeonGateTrigger,omitempty"`

	// LightSource 光源設定。未設定なら光源なし
	LightSource *LightSource `json:"lightSource,omitempty"`

	// Name 置物名
	Name string `json:"name"`

	// SpriteRender スプライト描画設定
	SpriteRender SpriteRender `json:"spriteRender"`

	// WarpEscapeTrigger 脱出ワープトリガー。踏むとダンジョンから脱出する
	WarpEscapeTrigger *WarpEscapeTriggerRaw `json:"warpEscapeTrigger,omitempty"`

	// WarpNextTrigger 次階層ワープトリガー。踏むと次の階層に進む
	WarpNextTrigger *WarpNextTriggerRaw `json:"warpNextTrigger,omitempty"`
}

// PropList 置物一覧
type PropList struct {
	// Data 置物の配列
	Data []Prop `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// ProvidesHealing 回復効果
type ProvidesHealing struct {
	// Amount 回復固定量
	Amount int32 `json:"amount"`

	// Ratio 回復割合。0.0〜1.0
	Ratio float64 `json:"ratio"`

	// ValueType 回復量の計算方式
	ValueType HealingValueType `json:"valueType"`
}

// RGBAColor RGBA色
type RGBAColor struct {
	// A 透明度 (0-255)
	A uint8 `json:"a"`

	// B 青 (0-255)
	B uint8 `json:"b"`

	// G 緑 (0-255)
	G uint8 `json:"g"`

	// R 赤 (0-255)
	R uint8 `json:"r"`
}

// Recipe レシピ
type Recipe struct {
	// Inputs 必要素材のリスト
	Inputs []RecipeInput `json:"inputs"`

	// Name レシピ名。生成されるアイテム名と一致する
	Name string `json:"name"`
}

// RecipeInput レシピ素材
type RecipeInput struct {
	// Amount 必要個数
	Amount int32 `json:"amount"`

	// Name 素材アイテム名
	Name string `json:"name"`
}

// RecipeList レシピ一覧レスポンス
type RecipeList struct {
	// Data レシピの配列
	Data []Recipe `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// ShelterType 遮蔽タイプ
type ShelterType float32

// SkillBook スキル本設定
type SkillBook struct {
	// MaxLevel 習得可能な最大レベル
	MaxLevel int32 `json:"maxLevel"`

	// RequiredLevel 習得に必要なスキルレベル
	RequiredLevel int32 `json:"requiredLevel"`

	// TargetSkill 習得対象のスキルID
	TargetSkill string `json:"targetSkill"`
}

// SpriteDepth スプライト描画深度
type SpriteDepth float32

// SpriteRender スプライトレンダー設定
type SpriteRender struct {
	// Depth 描画深度。レイヤー順序を決定する
	Depth SpriteDepth `json:"depth"`

	// SpriteKey スプライトキー
	SpriteKey string `json:"spriteKey"`

	// SpriteSheetName スプライトシート名
	SpriteSheetName string `json:"spriteSheetName"`
}

// SpriteSheet スプライトシート
type SpriteSheet struct {
	// Name シート名
	Name string `json:"name"`

	// Path 画像ファイルパス
	Path string `json:"path"`
}

// SpriteSheetList スプライトシート一覧
type SpriteSheetList struct {
	// Data スプライトシートの配列
	Data []SpriteSheet `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// TargetGroup ターゲットグループ
type TargetGroup string

// TargetNum ターゲット数
type TargetNum string

// Tile タイル
type Tile struct {
	// BlockPass 通行を妨げるかどうか
	BlockPass bool `json:"blockPass"`

	// BlockView 視線を遮るかどうか
	BlockView bool `json:"blockView"`

	// Description タイルの説明文
	Description string `json:"description"`

	// Foliage 植生タイプ。視界に影響する
	Foliage FoliageType `json:"foliage"`

	// Name タイル名
	Name string `json:"name"`

	// Shelter 遮蔽タイプ。戦闘時の命中率に影響する
	Shelter ShelterType `json:"shelter"`

	// SpriteRender スプライト描画設定
	SpriteRender SpriteRender `json:"spriteRender"`

	// Water 水タイプ。移動コストに影響する
	Water WaterType `json:"water"`
}

// TileList タイル一覧
type TileList struct {
	// Data タイルの配列
	Data []Tile `json:"data"`

	// TotalCount 総件数
	TotalCount int32 `json:"totalCount"`
}

// UsableScene 使用可能シーン
type UsableScene string

// WarpEscapeTriggerRaw 脱出ワープトリガー
type WarpEscapeTriggerRaw = map[string]interface{}

// WarpNextTriggerRaw 次階層ワープトリガー
type WarpNextTriggerRaw = map[string]interface{}

// WaterType 水タイプ
type WaterType float32

// Weapon 武器マーカー
type Weapon = map[string]interface{}

// Wearable 装備可能設定
type Wearable struct {
	// Defense 防御力
	Defense int32 `json:"defense"`

	// EquipmentCategory 装備する部位
	EquipmentCategory EquipmentCategory `json:"equipmentCategory"`

	// InsulationCold 耐寒性能
	InsulationCold int32 `json:"insulationCold"`

	// InsulationHeat 耐暑性能
	InsulationHeat int32 `json:"insulationHeat"`
}

// CommandTablesCreateJSONRequestBody defines body for CommandTablesCreate for application/json ContentType.
type CommandTablesCreateJSONRequestBody = CommandTable

// CommandTablesUpdateJSONRequestBody defines body for CommandTablesUpdate for application/json ContentType.
type CommandTablesUpdateJSONRequestBody = CommandTable

// DropTablesCreateJSONRequestBody defines body for DropTablesCreate for application/json ContentType.
type DropTablesCreateJSONRequestBody = DropTable

// DropTablesUpdateJSONRequestBody defines body for DropTablesUpdate for application/json ContentType.
type DropTablesUpdateJSONRequestBody = DropTable

// EnemyTablesCreateJSONRequestBody defines body for EnemyTablesCreate for application/json ContentType.
type EnemyTablesCreateJSONRequestBody = EnemyTable

// EnemyTablesUpdateJSONRequestBody defines body for EnemyTablesUpdate for application/json ContentType.
type EnemyTablesUpdateJSONRequestBody = EnemyTable

// ItemTablesCreateJSONRequestBody defines body for ItemTablesCreate for application/json ContentType.
type ItemTablesCreateJSONRequestBody = ItemTable

// ItemTablesUpdateJSONRequestBody defines body for ItemTablesUpdate for application/json ContentType.
type ItemTablesUpdateJSONRequestBody = ItemTable

// ItemsCreateJSONRequestBody defines body for ItemsCreate for application/json ContentType.
type ItemsCreateJSONRequestBody = Item

// ItemsUpdateJSONRequestBody defines body for ItemsUpdate for application/json ContentType.
type ItemsUpdateJSONRequestBody = Item

// MembersCreateJSONRequestBody defines body for MembersCreate for application/json ContentType.
type MembersCreateJSONRequestBody = Member

// MembersUpdateJSONRequestBody defines body for MembersUpdate for application/json ContentType.
type MembersUpdateJSONRequestBody = Member

// PalettesCreateJSONRequestBody defines body for PalettesCreate for application/json ContentType.
type PalettesCreateJSONRequestBody = Palette

// PalettesUpdateJSONRequestBody defines body for PalettesUpdate for application/json ContentType.
type PalettesUpdateJSONRequestBody = Palette

// ProfessionsCreateJSONRequestBody defines body for ProfessionsCreate for application/json ContentType.
type ProfessionsCreateJSONRequestBody = Profession

// ProfessionsUpdateJSONRequestBody defines body for ProfessionsUpdate for application/json ContentType.
type ProfessionsUpdateJSONRequestBody = Profession

// PropsCreateJSONRequestBody defines body for PropsCreate for application/json ContentType.
type PropsCreateJSONRequestBody = Prop

// PropsUpdateJSONRequestBody defines body for PropsUpdate for application/json ContentType.
type PropsUpdateJSONRequestBody = Prop

// RecipesCreateJSONRequestBody defines body for RecipesCreate for application/json ContentType.
type RecipesCreateJSONRequestBody = Recipe

// RecipesUpdateJSONRequestBody defines body for RecipesUpdate for application/json ContentType.
type RecipesUpdateJSONRequestBody = Recipe

// SpriteSheetsCreateJSONRequestBody defines body for SpriteSheetsCreate for application/json ContentType.
type SpriteSheetsCreateJSONRequestBody = SpriteSheet

// SpriteSheetsUpdateJSONRequestBody defines body for SpriteSheetsUpdate for application/json ContentType.
type SpriteSheetsUpdateJSONRequestBody = SpriteSheet

// TilesCreateJSONRequestBody defines body for TilesCreate for application/json ContentType.
type TilesCreateJSONRequestBody = Tile

// TilesUpdateJSONRequestBody defines body for TilesUpdate for application/json ContentType.
type TilesUpdateJSONRequestBody = Tile
