// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oapi

import (
	"time"
)

// Defines values for AmmoTag.
const (
	EnergyCell AmmoTag = "energy_cell"
	N9mm       AmmoTag = "9mm"
	Rifle      AmmoTag = "rifle"
	Shell      AmmoTag = "shell"
)

// Valid indicates whether the value is a known member of the AmmoTag enum.
func (e AmmoTag) Valid() bool {
	switch e {
	case EnergyCell:
		return true
	case N9mm:
		return true
	case Rifle:
		return true
	case Shell:
		return true
	default:
		return false
	}
}

// Defines values for AttackCategory.
const (
	BOW     AttackCategory = "BOW"
	CANON   AttackCategory = "CANON"
	FIST    AttackCategory = "FIST"
	HANDGUN AttackCategory = "HANDGUN"
	RIFLE   AttackCategory = "RIFLE"
	SPEAR   AttackCategory = "SPEAR"
	SWORD   AttackCategory = "SWORD"
)

// Valid indicates whether the value is a known member of the AttackCategory enum.
func (e AttackCategory) Valid() bool {
	switch e {
	case BOW:
		return true
	case CANON:
		return true
	case FIST:
		return true
	case HANDGUN:
		return true
	case RIFLE:
		return true
	case SPEAR:
		return true
	case SWORD:
		return true
	default:
		return false
	}
}

// Defines values for CombatPolicyType.
const (
	CombatPolicyTypeAttack CombatPolicyType = "attack"
	CombatPolicyTypeEvade  CombatPolicyType = "evade"
	CombatPolicyTypeIgnore CombatPolicyType = "ignore"
)

// Valid indicates whether the value is a known member of the CombatPolicyType enum.
func (e CombatPolicyType) Valid() bool {
	switch e {
	case CombatPolicyTypeAttack:
		return true
	case CombatPolicyTypeEvade:
		return true
	case CombatPolicyTypeIgnore:
		return true
	default:
		return false
	}
}

// Defines values for Element.
const (
	ElementCHILL   Element = "CHILL"
	ElementFIRE    Element = "FIRE"
	ElementNONE    Element = "NONE"
	ElementPHOTON  Element = "PHOTON"
	ElementTHUNDER Element = "THUNDER"
)

// Valid indicates whether the value is a known member of the Element enum.
func (e Element) Valid() bool {
	switch e {
	case ElementCHILL:
		return true
	case ElementFIRE:
		return true
	case ElementNONE:
		return true
	case ElementPHOTON:
		return true
	case ElementTHUNDER:
		return true
	default:
		return false
	}
}

// Defines values for EquipSlot.
const (
	EquipSlotARMS    EquipSlot = "ARMS"
	EquipSlotFEET    EquipSlot = "FEET"
	EquipSlotHANDS   EquipSlot = "HANDS"
	EquipSlotHEAD    EquipSlot = "HEAD"
	EquipSlotLEGS    EquipSlot = "LEGS"
	EquipSlotTORSO   EquipSlot = "TORSO"
	EquipSlotWEAPON1 EquipSlot = "WEAPON1"
	EquipSlotWEAPON2 EquipSlot = "WEAPON2"
	EquipSlotWEAPON3 EquipSlot = "WEAPON3"
	EquipSlotWEAPON4 EquipSlot = "WEAPON4"
	EquipSlotWEAPON5 EquipSlot = "WEAPON5"
)

// Valid indicates whether the value is a known member of the EquipSlot enum.
func (e EquipSlot) Valid() bool {
	switch e {
	case EquipSlotARMS:
		return true
	case EquipSlotFEET:
		return true
	case EquipSlotHANDS:
		return true
	case EquipSlotHEAD:
		return true
	case EquipSlotLEGS:
		return true
	case EquipSlotTORSO:
		return true
	case EquipSlotWEAPON1:
		return true
	case EquipSlotWEAPON2:
		return true
	case EquipSlotWEAPON3:
		return true
	case EquipSlotWEAPON4:
		return true
	case EquipSlotWEAPON5:
		return true
	default:
		return false
	}
}

// Defines values for EquipmentCategory.
const (
	EquipmentCategoryARMS    EquipmentCategory = "ARMS"
	EquipmentCategoryFEET    EquipmentCategory = "FEET"
	EquipmentCategoryHANDS   EquipmentCategory = "HANDS"
	EquipmentCategoryHEAD    EquipmentCategory = "HEAD"
	EquipmentCategoryJEWELRY EquipmentCategory = "JEWELRY"
	EquipmentCategoryLEGS    EquipmentCategory = "LEGS"
	EquipmentCategoryTORSO   EquipmentCategory = "TORSO"
)

// Valid indicates whether the value is a known member of the EquipmentCategory enum.
func (e EquipmentCategory) Valid() bool {
	switch e {
	case EquipmentCategoryARMS:
		return true
	case EquipmentCategoryFEET:
		return true
	case EquipmentCategoryHANDS:
		return true
	case EquipmentCategoryHEAD:
		return true
	case EquipmentCategoryJEWELRY:
		return true
	case EquipmentCategoryLEGS:
		return true
	case EquipmentCategoryTORSO:
		return true
	default:
		return false
	}
}

// Defines values for FactionMemberType.
const (
	FactionNeutral FactionMemberType = "FactionNeutral"
)

// Valid indicates whether the value is a known member of the FactionMemberType enum.
func (e FactionMemberType) Valid() bool {
	switch e {
	case FactionNeutral:
		return true
	default:
		return false
	}
}

// Defines values for FoliageType.
const (
	FoliageTypeMinus1 FoliageType = -1
	FoliageTypeMinus3 FoliageType = -3
	FoliageTypeN0     FoliageType = 0
)

// Valid indicates whether the value is a known member of the FoliageType enum.
func (e FoliageType) Valid() bool {
	switch e {
	case FoliageTypeMinus1:
		return true
	case FoliageTypeMinus3:
		return true
	case FoliageTypeN0:
		return true
	default:
		return false
	}
}

// Defines values for HealingValueType.
const (
	ABSOLUTE   HealingValueType = "ABSOLUTE"
	NUMERAL    HealingValueType = "NUMERAL"
	PERCENTAGE HealingValueType = "PERCENTAGE"
)

// Valid indicates whether the value is a known member of the HealingValueType enum.
func (e HealingValueType) Valid() bool {
	switch e {
	case ABSOLUTE:
		return true
	case NUMERAL:
		return true
	case PERCENTAGE:
		return true
	default:
		return false
	}
}

// Defines values for ItemGroupSubtype.
const (
	Collection   ItemGroupSubtype = "collection"
	Distribution ItemGroupSubtype = "distribution"
)

// Valid indicates whether the value is a known member of the ItemGroupSubtype enum.
func (e ItemGroupSubtype) Valid() bool {
	switch e {
	case Collection:
		return true
	case Distribution:
		return true
	default:
		return false
	}
}

// Defines values for MovementPatternType.
const (
	MovementPatternTypePatrol      MovementPatternType = "patrol"
	MovementPatternTypeRandom      MovementPatternType = "random"
	MovementPatternTypeStationary  MovementPatternType = "stationary"
	MovementPatternTypeSwarm       MovementPatternType = "swarm"
	MovementPatternTypeTerritorial MovementPatternType = "territorial"
	MovementPatternTypeWallHug     MovementPatternType = "wallHug"
	MovementPatternTypeWander      MovementPatternType = "wander"
)

// Valid indicates whether the value is a known member of the MovementPatternType enum.
func (e MovementPatternType) Valid() bool {
	switch e {
	case MovementPatternTypePatrol:
		return true
	case MovementPatternTypeRandom:
		return true
	case MovementPatternTypeStationary:
		return true
	case MovementPatternTypeSwarm:
		return true
	case MovementPatternTypeTerritorial:
		return true
	case MovementPatternTypeWallHug:
		return true
	case MovementPatternTypeWander:
		return true
	default:
		return false
	}
}

// Defines values for SaveDataAttackRangeType.
const (
	MELEE  SaveDataAttackRangeType = "MELEE"
	RANGED SaveDataAttackRangeType = "RANGED"
)

// Valid indicates whether the value is a known member of the SaveDataAttackRangeType enum.
func (e SaveDataAttackRangeType) Valid() bool {
	switch e {
	case MELEE:
		return true
	case RANGED:
		return true
	default:
		return false
	}
}

// Defines values for SaveDataCombatPolicyType.
const (
	SaveDataCombatPolicyTypeAttack SaveDataCombatPolicyType = "attack"
	SaveDataCombatPolicyTypeEvade  SaveDataCombatPolicyType = "evade"
	SaveDataCombatPolicyTypeIgnore SaveDataCombatPolicyType = "ignore"
)

// Valid indicates whether the value is a known member of the SaveDataCombatPolicyType enum.
func (e SaveDataCombatPolicyType) Valid() bool {
	switch e {
	case SaveDataCombatPolicyTypeAttack:
		return true
	case SaveDataCombatPolicyTypeEvade:
		return true
	case SaveDataCombatPolicyTypeIgnore:
		return true
	default:
		return false
	}
}

// Defines values for SaveDataHealingAmountType.
const (
	Numeral SaveDataHealingAmountType = "numeral"
	Ratio   SaveDataHealingAmountType = "ratio"
)

// Valid indicates whether the value is a known member of the SaveDataHealingAmountType enum.
func (e SaveDataHealingAmountType) Valid() bool {
	switch e {
	case Numeral:
		return true
	case Ratio:
		return true
	default:
		return false
	}
}

// Defines values for SaveDataItemHandlingPolicyType.
const (
	Distribute SaveDataItemHandlingPolicyType = "distribute"
	Keep       SaveDataItemHandlingPolicyType = "keep"
)

// Valid indicates whether the value is a known member of the SaveDataItemHandlingPolicyType enum.
func (e SaveDataItemHandlingPolicyType) Valid() bool {
	switch e {
	case Distribute:
		return true
	case Keep:
		return true
	default:
		return false
	}
}

// Defines values for SaveDataItemPickupPolicyType.
const (
	Ignore SaveDataItemPickupPolicyType = "ignore"
	Pickup SaveDataItemPickupPolicyType = "pickup"
)

// Valid indicates whether the value is a known member of the SaveDataItemPickupPolicyType enum.
func (e SaveDataItemPickupPolicyType) Valid() bool {
	switch e {
	case Ignore:
		return true
	case Pickup:
		return true
	default:
		return false
	}
}

// Defines values for SaveDataMovementPolicyType.
const (
	SaveDataMovementPolicyTypeEscort      SaveDataMovementPolicyType = "escort"
	SaveDataMovementPolicyTypePatrol      SaveDataMovementPolicyType = "patrol"
	SaveDataMovementPolicyTypeRandom      SaveDataMovementPolicyType = "random"
	SaveDataMovementPolicyTypeRetreat     SaveDataMovementPolicyType = "retreat"
	SaveDataMovementPolicyTypeStationary  SaveDataMovementPolicyType = "stationary"
	SaveDataMovementPolicyTypeSwarm       SaveDataMovementPolicyType = "swarm"
	SaveDataMovementPolicyTypeTerritorial SaveDataMovementPolicyType = "territorial"
	SaveDataMovementPolicyTypeVanguard    SaveDataMovementPolicyType = "vanguard"
	SaveDataMovementPolicyTypeWallHug     SaveDataMovementPolicyType = "wallHug"
	SaveDataMovementPolicyTypeWander      SaveDataMovementPolicyType = "wander"
)

// Valid indicates whether the value is a known member of the SaveDataMovementPolicyType enum.
func (e SaveDataMovementPolicyType) Valid() bool {
	switch e {
	case SaveDataMovementPolicyTypeEscort:
		return true
	case SaveDataMovementPolicyTypePatrol:
		return true
	case SaveDataMovementPolicyTypeRandom:
		return true
	case SaveDataMovementPolicyTypeRetreat:
		return true
	case SaveDataMovementPolicyTypeStationary:
		return true
	case SaveDataMovementPolicyTypeSwarm:
		return true
	case SaveDataMovementPolicyTypeTerritorial:
		return true
	case SaveDataMovementPolicyTypeVanguard:
		return true
	case SaveDataMovementPolicyTypeWallHug:
		return true
	case SaveDataMovementPolicyTypeWander:
		return true
	default:
		return false
	}
}

// Defines values for SaveDataPlannerType.
const (
	Solo  SaveDataPlannerType = "solo"
	Squad SaveDataPlannerType = "squad"
)

// Valid indicates whether the value is a known member of the SaveDataPlannerType enum.
func (e SaveDataPlannerType) Valid() bool {
	switch e {
	case Solo:
		return true
	case Squad:
		return true
	default:
		return false
	}
}

// Defines values for SaveDataSaveDataVersion.
const (
	N100 SaveDataSaveDataVersion = "1.0.0"
)

// Valid indicates whether the value is a known member of the SaveDataSaveDataVersion enum.
func (e SaveDataSaveDataVersion) Valid() bool {
	switch e {
	case N100:
		return true
	default:
		return false
	}
}

// Defines values for ShelterType.
const (
	ShelterTypeN0  ShelterType = 0
	ShelterTypeN10 ShelterType = 10
	ShelterTypeN5  ShelterType = 5
)

// Valid indicates whether the value is a known member of the ShelterType enum.
func (e ShelterType) Valid() bool {
	switch e {
	case ShelterTypeN0:
		return true
	case ShelterTypeN10:
		return true
	case ShelterTypeN5:
		return true
	default:
		return false
	}
}

// Defines values for SpriteDepth.
const (
	SpriteDepthN0 SpriteDepth = 0
	SpriteDepthN1 SpriteDepth = 1
	SpriteDepthN2 SpriteDepth = 2
	SpriteDepthN3 SpriteDepth = 3
)

// Valid indicates whether the value is a known member of the SpriteDepth enum.
func (e SpriteDepth) Valid() bool {
	switch e {
	case SpriteDepthN0:
		return true
	case SpriteDepthN1:
		return true
	case SpriteDepthN2:
		return true
	case SpriteDepthN3:
		return true
	default:
		return false
	}
}

// Defines values for TargetGroup.
const (
	TargetGroupALLY   TargetGroup = "ALLY"
	TargetGroupENEMY  TargetGroup = "ENEMY"
	TargetGroupNONE   TargetGroup = "NONE"
	TargetGroupWEAPON TargetGroup = "WEAPON"
)

// Valid indicates whether the value is a known member of the TargetGroup enum.
func (e TargetGroup) Valid() bool {
	switch e {
	case TargetGroupALLY:
		return true
	case TargetGroupENEMY:
		return true
	case TargetGroupNONE:
		return true
	case TargetGroupWEAPON:
		return true
	default:
		return false
	}
}

// Defines values for TargetNum.
const (
	ALL    TargetNum = "ALL"
	SINGLE TargetNum = "SINGLE"
)

// Valid indicates whether the value is a known member of the TargetNum enum.
func (e TargetNum) Valid() bool {
	switch e {
	case ALL:
		return true
	case SINGLE:
		return true
	default:
		return false
	}
}

// Defines values for UsableScene.
const (
	ANY    UsableScene = "ANY"
	BATTLE UsableScene = "BATTLE"
	FIELD  UsableScene = "FIELD"
)

// Valid indicates whether the value is a known member of the UsableScene enum.
func (e UsableScene) Valid() bool {
	switch e {
	case ANY:
		return true
	case BATTLE:
		return true
	case FIELD:
		return true
	default:
		return false
	}
}

// Defines values for WaterType.
const (
	WaterTypeMinus10 WaterType = -10
	WaterTypeMinus5  WaterType = -5
	WaterTypeN0      WaterType = 0
)

// Valid indicates whether the value is a known member of the WaterType enum.
func (e WaterType) Valid() bool {
	switch e {
	case WaterTypeMinus10:
		return true
	case WaterTypeMinus5:
		return true
	case WaterTypeN0:
		return true
	default:
		return false
	}
}

// Abilities 能力値
type Abilities struct {
	// Agility 敏捷性。行動順に影響する
	Agility Agility `json:"agility"`

	// Defense 防御力。被ダメージを軽減する
	Defense Defense `json:"defense"`

	// Dexterity 器用さ。クリティカル率に影響する
	Dexterity Dexterity `json:"dexterity"`

	// Sensation 感覚。命中率と回避率に影響する
	Sensation Sensation `json:"sensation"`

	// Strength 筋力。物理ダメージに影響する
	Strength Strength `json:"strength"`

	// Vitality 体力。HPに影響する
	Vitality Vitality `json:"vitality"`
}

// Accuracy 命中率。0で必中なし、100で必中
type Accuracy = int32

// AccuracyBonus 命中率補正値
type AccuracyBonus = int32

// ActionCost 行動コスト
type ActionCost = int32

// Agility 敏捷性。行動順に影響する
type Agility = int32

// Ammo 弾薬設定
type Ammo struct {
	// AccuracyBonus 命中率補正値
	AccuracyBonus AccuracyBonus `json:"accuracyBonus"`

	// AmmoTag 弾薬タグ
	AmmoTag *AmmoTag `json:"ammoTag,omitempty"`

	// DamageBonus ダメージ補正値
	DamageBonus DamageBonus `json:"damageBonus"`
}

// AmmoTag 弾薬タグ
type AmmoTag string

// ArmorDefense 防具の防御力
type ArmorDefense = int32

// AttackCategory 攻撃種別
type AttackCategory string

// AttackCount 1ターンあたりの攻撃回数
type AttackCount = int32

// BaseDamage 基本ダメージ
type BaseDamage = int32

// BlocksPassage 通行を妨げるかどうか
type BlocksPassage = bool

// BlocksView 視線を遮るかどうか
type BlocksView = bool

// Book 本の設定
type Book struct {
	// Skill スキル本設定
	Skill *SkillBook `json:"skill,omitempty"`

	// TotalEffort 読了に必要な総読書量
	TotalEffort ReadingEffort `json:"totalEffort"`
}

// ColorChannel RGBA色チャネル値 (0-255)
type ColorChannel = uint8

// CombatPolicyType 戦闘ポリシー。エンティティの戦闘時の行動方針を定義する
type CombatPolicyType string

// CommandTable コマンドテーブル
type CommandTable struct {
	Entries []CommandTableEntry `json:"entries"`

	// Name エンティティ名
	Name EntityName `json:"name"`
}

// CommandTableEntry コマンドテーブルエントリ
type CommandTableEntry struct {
	// Weapon エンティティ名
	Weapon EntityName `json:"weapon"`

	// Weight テーブルエントリの重み。大きいほど選ばれやすい
	Weight EntryWeight `json:"weight"`
}

// CommandTableList コマンドテーブル一覧
type CommandTableList struct {
	Data       []CommandTable `json:"data"`
	TotalCount int32          `json:"totalCount"`
}

// Consumable 消費可能アイテムの設定
type Consumable struct {
	// TargetGroup ターゲットグループ
	TargetGroup TargetGroup `json:"targetGroup"`

	// TargetNum ターゲット数
	TargetNum TargetNum `json:"targetNum"`

	// UsableScene 使用可能シーン
	UsableScene UsableScene `json:"usableScene"`
}

// DamageBonus ダメージ補正値
type DamageBonus = int32

// Defense 防御力。被ダメージを軽減する
type Defense = int32

// DepthLevel 階層レベル
type DepthLevel = int32

// Dexterity 器用さ。クリティカル率に影響する
type Dexterity = int32

// Dialog 会話データ
type Dialog struct {
	// MessageKey メッセージリソースのキー
	MessageKey MessageKey `json:"messageKey"`
}

// DoorLockTriggerRaw 扉ロックトリガー
type DoorLockTriggerRaw = map[string]interface{}

// DoorRaw 扉ローデータ
type DoorRaw = map[string]interface{}

// DropTable ドロップテーブル
type DropTable struct {
	Entries []DropTableEntry `json:"entries"`

	// Name エンティティ名
	Name EntityName `json:"name"`
}

// DropTableEntry ドロップテーブルエントリ
type DropTableEntry struct {
	// Material ドロップする素材名。空文字はドロップなしを意味する
	Material string `json:"material"`

	// Weight テーブルエントリの重み。大きいほど選ばれやすい
	Weight EntryWeight `json:"weight"`
}

// DropTableList ドロップテーブル一覧
type DropTableList struct {
	Data       []DropTable `json:"data"`
	TotalCount int32       `json:"totalCount"`
}

// Element 攻撃属性
type Element string

// EnemyTable 敵テーブル
type EnemyTable struct {
	Entries []EnemyTableEntry `json:"entries"`

	// Name エンティティ名
	Name EntityName `json:"name"`
}

// EnemyTableEntry 敵テーブルエントリ
type EnemyTableEntry struct {
	// EnemyName エンティティ名
	EnemyName EntityName `json:"enemyName"`

	// MaxDepth 階層レベル
	MaxDepth DepthLevel `json:"maxDepth"`

	// MinDepth 階層レベル
	MinDepth DepthLevel `json:"minDepth"`

	// PackMax パックの最大数
	PackMax PackMax `json:"packMax"`

	// PackMin パックの最小数
	PackMin PackMin `json:"packMin"`

	// Weight テーブルエントリの重み。大きいほど選ばれやすい
	Weight EntryWeight `json:"weight"`
}

// EnemyTableList 敵テーブル一覧
type EnemyTableList struct {
	Data       []EnemyTable `json:"data"`
	TotalCount int32        `json:"totalCount"`
}

// EntityDescription 説明文
type EntityDescription = string

// EntityName エンティティ名
type EntityName = string

// EntryWeight テーブルエントリの重み。大きいほど選ばれやすい
type EntryWeight = float64

// EquipBonus 装備ボーナス
type EquipBonus struct {
	// Agility 敏捷性。行動順に影響する
	Agility Agility `json:"agility"`

	// Dexterity 器用さ。クリティカル率に影響する
	Dexterity Dexterity `json:"dexterity"`

	// Sensation 感覚。命中率と回避率に影響する
	Sensation Sensation `json:"sensation"`

	// Strength 筋力。物理ダメージに影響する
	Strength Strength `json:"strength"`

	// Vitality 体力。HPに影響する
	Vitality Vitality `json:"vitality"`
}

// EquipSlot 装備スロット。防具部位 + 武器スロット
type EquipSlot string

// EquipmentCategory 装備部位
type EquipmentCategory string

// Error エラーレスポンス
type Error struct {
	// Message エラーメッセージ
	Message string `json:"message"`
}

// FactionMemberType 派閥タイプ
type FactionMemberType string

// Fire 遠距離攻撃設定
type Fire struct {
	// Accuracy 命中率。0で必中なし、100で必中
	Accuracy Accuracy `json:"accuracy"`

	// AmmoTag 弾薬タグ
	AmmoTag *AmmoTag `json:"ammoTag,omitempty"`

	// AttackCategory 攻撃種別
	AttackCategory AttackCategory `json:"attackCategory"`

	// AttackCount 1ターンあたりの攻撃回数
	AttackCount AttackCount `json:"attackCount"`

	// Cost 行動コスト
	Cost ActionCost `json:"cost"`

	// Damage 基本ダメージ
	Damage BaseDamage `json:"damage"`

	// Element 攻撃属性
	Element Element `json:"element"`

	// MagazineSize マガジン容量
	MagazineSize MagazineSize `json:"magazineSize"`

	// ReloadEffort リロードに必要な行動力
	ReloadEffort ReloadEffort `json:"reloadEffort"`

	// TargetGroup ターゲットグループ
	TargetGroup TargetGroup `json:"targetGroup"`

	// TargetNum ターゲット数
	TargetNum TargetNum `json:"targetNum"`
}

// FoliageType 植生タイプ
type FoliageType float32

// HealAmount 回復固定量
type HealAmount = int32

// HealRatio 回復割合。0.0〜1.0
type HealRatio = float64

// HealingValueType 回復量の計算方式
type HealingValueType string

// HitPoints 耐久値。設定すると破壊可能になる
type HitPoints = int32

// ImagePath 画像ファイルパス
type ImagePath = string

// InsulationCold 耐寒性能
type InsulationCold = int32

// InsulationHeat 耐暑性能
type InsulationHeat = int32

// IsBoss ボスモンスターかどうか
type IsBoss = bool

// IsPlayer プレイヤーキャラクターかどうか
type IsPlayer = bool

// Item アイテム
type Item struct {
	// Ammo 弾薬設定
	Ammo     *Ammo        `json:"ammo,omitempty"`
	AnimKeys *[]SpriteKey `json:"animKeys,omitempty"`

	// Book 本の設定
	Book *Book `json:"book,omitempty"`

	// Consumable 消費可能アイテムの設定
	Consumable *Consumable `json:"consumable,omitempty"`

	// Description 説明文
	Description EntityDescription `json:"description"`

	// EquipBonus 装備ボーナス
	EquipBonus *EquipBonus `json:"equipBonus,omitempty"`

	// Fire 遠距離攻撃設定
	Fire *Fire `json:"fire,omitempty"`

	// InflictsDamage 基本ダメージ
	InflictsDamage *BaseDamage `json:"inflictsDamage,omitempty"`
	Material       *bool       `json:"material,omitempty"`

	// Melee 近接攻撃設定
	Melee *Melee `json:"melee,omitempty"`

	// Name エンティティ名
	Name EntityName `json:"name"`

	// ProvidesHealing 回復効果
	ProvidesHealing *ProvidesHealing `json:"providesHealing,omitempty"`

	// ProvidesNutrition 栄養価
	ProvidesNutrition *NutritionAmount `json:"providesNutrition,omitempty"`

	// SpriteKey スプライトキー
	SpriteKey SpriteKey `json:"spriteKey"`

	// SpriteSheetName スプライトシート名
	SpriteSheetName SpriteSheetName `json:"spriteSheetName"`

	// Stackable スタック可能かどうか
	Stackable *Stackable `json:"stackable,omitempty"`

	// Value 売買価格
	Value ItemValue `json:"value"`

	// Wearable 装備可能設定
	Wearable *Wearable `json:"wearable,omitempty"`

	// Weight アイテム重量
	Weight *Weight `json:"weight,omitempty"`
}

// ItemCount アイテム所持数
type ItemCount = int32

// ItemGroup アイテムグループ。アイテムの出現セットを定義する
type ItemGroup struct {
	Entries []ItemGroupEntry `json:"entries"`

	// Name エンティティ名
	Name EntityName `json:"name"`

	// Subtype アイテムグループのサブタイプ
	Subtype ItemGroupSubtype `json:"subtype"`
}

// ItemGroupEntry アイテムグループエントリ
type ItemGroupEntry struct {
	// ItemName エンティティ名
	ItemName EntityName `json:"itemName"`

	// PackMax パックの最大数
	PackMax PackMax `json:"packMax"`

	// PackMin パックの最小数
	PackMin PackMin `json:"packMin"`

	// Weight distribution: 相対重み。collection: 確率（0-100）
	Weight EntryWeight `json:"weight"`
}

// ItemGroupList アイテムグループ一覧
type ItemGroupList struct {
	Data       []ItemGroup `json:"data"`
	TotalCount int32       `json:"totalCount"`
}

// ItemGroupSubtype アイテムグループのサブタイプ
type ItemGroupSubtype string

// ItemList アイテム一覧レスポンス
type ItemList struct {
	Data       []Item `json:"data"`
	TotalCount int32  `json:"totalCount"`
}

// ItemTable アイテムテーブル
type ItemTable struct {
	Entries []ItemTableEntry `json:"entries"`

	// Name エンティティ名
	Name EntityName `json:"name"`
}

// ItemTableEntry アイテムテーブルエントリ。アイテムグループを参照する
type ItemTableEntry struct {
	// GroupName 参照するアイテムグループ名
	GroupName EntityName `json:"groupName"`

	// MaxDepth 階層レベル
	MaxDepth DepthLevel `json:"maxDepth"`

	// MinDepth 階層レベル
	MinDepth DepthLevel `json:"minDepth"`

	// Weight テーブルエントリの重み。大きいほど選ばれやすい
	Weight EntryWeight `json:"weight"`
}

// ItemTableList アイテムテーブル一覧
type ItemTableList struct {
	Data       []ItemTable `json:"data"`
	TotalCount int32       `json:"totalCount"`
}

// ItemValue 売買価格
type ItemValue = int32

// LightEnabled 光源が有効かどうか
type LightEnabled = bool

// LightRadius 光の到達半径（タイル単位）
type LightRadius = int32

// LightSource 光源設定
type LightSource struct {
	// Color RGBA色
	Color RGBAColor `json:"color"`

	// Enabled 光源が有効かどうか
	Enabled LightEnabled `json:"enabled"`

	// Radius 光の到達半径（タイル単位）
	Radius LightRadius `json:"radius"`
}

// MagazineSize マガジン容量
type MagazineSize = int32

// MaterialAmount 素材必要数
type MaterialAmount = int32

// Melee 近接攻撃設定
type Melee struct {
	// Accuracy 命中率。0で必中なし、100で必中
	Accuracy Accuracy `json:"accuracy"`

	// AttackCategory 攻撃種別
	AttackCategory AttackCategory `json:"attackCategory"`

	// AttackCount 1ターンあたりの攻撃回数
	AttackCount AttackCount `json:"attackCount"`

	// Cost 行動コスト
	Cost ActionCost `json:"cost"`

	// Damage 基本ダメージ
	Damage BaseDamage `json:"damage"`

	// Element 攻撃属性
	Element Element `json:"element"`

	// TargetGroup ターゲットグループ
	TargetGroup TargetGroup `json:"targetGroup"`

	// TargetNum ターゲット数
	TargetNum TargetNum `json:"targetNum"`
}

// Member メンバー
type Member struct {
	// Abilities 能力値
	Abilities Abilities    `json:"abilities"`
	AnimKeys  *[]SpriteKey `json:"animKeys,omitempty"`

	// CombatPolicy 戦闘ポリシー。エンティティの戦闘時の行動方針を定義する
	CombatPolicy *CombatPolicyType `json:"combatPolicy,omitempty"`

	// CommandTableName プレイヤーキャラクターでは省略可能
	CommandTableName *EntityName `json:"commandTableName,omitempty"`

	// Dialog 会話データ
	Dialog *Dialog `json:"dialog,omitempty"`

	// DropTableName プレイヤーキャラクターでは省略可能
	DropTableName *EntityName `json:"dropTableName,omitempty"`

	// FactionType 派閥タイプ
	FactionType *FactionMemberType `json:"factionType,omitempty"`

	// IsBoss ボスモンスターかどうか
	IsBoss IsBoss `json:"isBoss"`

	// LightSource 光源設定
	LightSource *LightSource `json:"lightSource,omitempty"`

	// MovementPattern 非戦闘時の移動パターン
	MovementPattern *MovementPatternType `json:"movementPattern,omitempty"`

	// Name エンティティ名
	Name EntityName `json:"name"`

	// Player プレイヤーキャラクターかどうか
	Player *IsPlayer `json:"player,omitempty"`

	// SpriteKey スプライトキー
	SpriteKey SpriteKey `json:"spriteKey"`

	// SpriteSheetName スプライトシート名
	SpriteSheetName SpriteSheetName `json:"spriteSheetName"`

	// ViewDistance AI視界距離（タイル単位）
	ViewDistance *ViewDistance `json:"viewDistance,omitempty"`
}

// MemberList メンバー一覧レスポンス
type MemberList struct {
	Data       []Member `json:"data"`
	TotalCount int32    `json:"totalCount"`
}

// MessageKey メッセージリソースのキー
type MessageKey = string

// MovementPatternType 非戦闘時の移動パターン
type MovementPatternType string

// NutritionAmount 栄養価
type NutritionAmount = int32

// PackMax パックの最大数
type PackMax = int32

// PackMin パックの最小数
type PackMin = int32

// Palette パレット
type Palette struct {
	// Description 説明文
	Description EntityDescription `json:"description"`

	// Id パレットID
	Id      PaletteId               `json:"id"`
	Npcs    map[string]PaletteEntry `json:"npcs"`
	Props   map[string]PaletteEntry `json:"props"`
	Terrain map[string]EntityName   `json:"terrain"`
}

// PaletteEntry パレットエントリ
type PaletteEntry struct {
	// Id パレットID
	Id PaletteId `json:"id"`

	// Tile エンティティ名
	Tile EntityName `json:"tile"`
}

// PaletteId パレットID
type PaletteId = string

// PaletteList パレット一覧
type PaletteList struct {
	Data       []Palette `json:"data"`
	TotalCount int32     `json:"totalCount"`
}

// PassCost 通行コスト加算値。0で変化なし、50でベースコスト+50
type PassCost = int32

// Profession 職業
type Profession struct {
	// Abilities 能力値
	Abilities Abilities `json:"abilities"`

	// Description 説明文
	Description EntityDescription `json:"description"`
	Equips      []ProfessionEquip `json:"equips"`

	// Id 職業ID
	Id    ProfessionId     `json:"id"`
	Items []ProfessionItem `json:"items"`

	// Name エンティティ名
	Name   EntityName         `json:"name"`
	Skills *[]ProfessionSkill `json:"skills,omitempty"`
}

// ProfessionEquip 職業初期装備
type ProfessionEquip struct {
	// Name エンティティ名
	Name EntityName `json:"name"`

	// Slot 装備スロット。防具部位 + 武器スロット
	Slot EquipSlot `json:"slot"`
}

// ProfessionId 職業ID
type ProfessionId = string

// ProfessionItem 職業初期所持アイテム
type ProfessionItem struct {
	// Count アイテム所持数
	Count ItemCount `json:"count"`

	// Name エンティティ名
	Name EntityName `json:"name"`
}

// ProfessionList 職業一覧
type ProfessionList struct {
	Data       []Profession `json:"data"`
	TotalCount int32        `json:"totalCount"`
}

// ProfessionSkill 職業スキル初期値
type ProfessionSkill struct {
	// Id スキルID
	Id SkillId `json:"id"`

	// Value スキルレベル
	Value SkillLevel `json:"value"`
}

// Prop 置物
type Prop struct {
	AnimKeys *[]SpriteKey `json:"animKeys,omitempty"`

	// BlockPass 通行を妨げるかどうか
	BlockPass BlocksPassage `json:"blockPass"`

	// BlockView 視線を遮るかどうか
	BlockView BlocksView `json:"blockView"`

	// Description 説明文
	Description EntityDescription `json:"description"`

	// Door 扉ローデータ
	Door *DoorRaw `json:"door,omitempty"`

	// DoorLockTrigger 扉ロックトリガー
	DoorLockTrigger *DoorLockTriggerRaw `json:"doorLockTrigger,omitempty"`

	// Hp 耐久値。設定すると破壊可能になる
	Hp *HitPoints `json:"hp,omitempty"`

	// LightSource 光源設定
	LightSource *LightSource `json:"lightSource,omitempty"`

	// Name エンティティ名
	Name EntityName `json:"name"`

	// PassCost 通行コスト加算値。0で変化なし、50でベースコスト+50
	PassCost *PassCost `json:"passCost,omitempty"`

	// SpriteRender スプライトレンダー設定
	SpriteRender SpriteRender `json:"spriteRender"`

	// Storage 収納ローデータ
	Storage *StorageRaw `json:"storage,omitempty"`

	// WarpNextTrigger 次階層ワープトリガー
	WarpNextTrigger *WarpNextTriggerRaw `json:"warpNextTrigger,omitempty"`

	// WarpPrevTrigger 前階層ワープトリガー
	WarpPrevTrigger *WarpPrevTriggerRaw `json:"warpPrevTrigger,omitempty"`
}

// PropList 置物一覧
type PropList struct {
	Data       []Prop `json:"data"`
	TotalCount int32  `json:"totalCount"`
}

// ProvidesHealing 回復効果
type ProvidesHealing struct {
	// Amount 回復固定量
	Amount HealAmount `json:"amount"`

	// Ratio 回復割合。0.0〜1.0
	Ratio HealRatio `json:"ratio"`

	// ValueType 回復量の計算方式
	ValueType HealingValueType `json:"valueType"`
}

// RGBAColor RGBA色
type RGBAColor struct {
	// A RGBA色チャネル値 (0-255)
	A ColorChannel `json:"a"`

	// B RGBA色チャネル値 (0-255)
	B ColorChannel `json:"b"`

	// G RGBA色チャネル値 (0-255)
	G ColorChannel `json:"g"`

	// R RGBA色チャネル値 (0-255)
	R ColorChannel `json:"r"`
}

// Raws ローデータ全体。TOMLファイルのルート構造を定義する
type Raws struct {
	CommandTables *[]CommandTable `json:"commandTables,omitempty"`
	DropTables    *[]DropTable    `json:"dropTables,omitempty"`
	EnemyTables   *[]EnemyTable   `json:"enemyTables,omitempty"`
	ItemGroups    *[]ItemGroup    `json:"itemGroups,omitempty"`
	ItemTables    *[]ItemTable    `json:"itemTables,omitempty"`
	Items         *[]Item         `json:"items,omitempty"`
	Members       *[]Member       `json:"members,omitempty"`
	Professions   *[]Profession   `json:"professions,omitempty"`
	Props         *[]Prop         `json:"props,omitempty"`
	Recipes       *[]Recipe       `json:"recipes,omitempty"`
	SpriteSheets  *[]SpriteSheet  `json:"spriteSheets,omitempty"`
	Tiles         *[]Tile         `json:"tiles,omitempty"`
}

// ReadingEffort 読了に必要な総読書量
type ReadingEffort = int32

// Recipe レシピ
type Recipe struct {
	Inputs []RecipeInput `json:"inputs"`

	// Name エンティティ名
	Name EntityName `json:"name"`
}

// RecipeInput レシピ素材
type RecipeInput struct {
	// Amount 素材必要数
	Amount MaterialAmount `json:"amount"`

	// Name エンティティ名
	Name EntityName `json:"name"`
}

// RecipeList レシピ一覧レスポンス
type RecipeList struct {
	Data       []Recipe `json:"data"`
	TotalCount int32    `json:"totalCount"`
}

// ReloadEffort リロードに必要な行動力
type ReloadEffort = int32

// SaveDataAbilitiesComponent 能力値
type SaveDataAbilitiesComponent struct {
	// Agility 単一能力値。基本値・修正値・合計値を持つ
	Agility SaveDataAbilityValue `json:"Agility"`

	// Defense 単一能力値。基本値・修正値・合計値を持つ
	Defense SaveDataAbilityValue `json:"Defense"`

	// Dexterity 単一能力値。基本値・修正値・合計値を持つ
	Dexterity SaveDataAbilityValue `json:"Dexterity"`

	// Sensation 単一能力値。基本値・修正値・合計値を持つ
	Sensation SaveDataAbilityValue `json:"Sensation"`

	// Strength 単一能力値。基本値・修正値・合計値を持つ
	Strength SaveDataAbilityValue `json:"Strength"`

	// Vitality 単一能力値。基本値・修正値・合計値を持つ
	Vitality SaveDataAbilityValue `json:"Vitality"`
}

// SaveDataAbilityBase 能力値の基本値
type SaveDataAbilityBase = int32

// SaveDataAbilityBonus 能力値ボーナス
type SaveDataAbilityBonus = int32

// SaveDataAbilityModifier 能力値の装備・状態変化による修正値
type SaveDataAbilityModifier = int32

// SaveDataAbilityTotal 能力値の算出された現在値
type SaveDataAbilityTotal = int32

// SaveDataAbilityValue 単一能力値。基本値・修正値・合計値を持つ
type SaveDataAbilityValue struct {
	// Base 固有の基本値
	Base SaveDataAbilityBase `json:"Base"`

	// Modifier 装備や状態変化による修正値
	Modifier SaveDataAbilityModifier `json:"Modifier"`

	// Total 算出された現在値
	Total SaveDataAbilityTotal `json:"Total"`
}

// SaveDataAmmoComponent 弾薬設定
type SaveDataAmmoComponent struct {
	// AccuracyBonus 命中率補正値
	AccuracyBonus AccuracyBonus `json:"AccuracyBonus"`

	// AmmoTag 弾薬の口径タグ。セーブデータでは任意文字列を許容する
	AmmoTag SaveDataAmmoTag `json:"AmmoTag"`

	// DamageBonus ダメージ補正値
	DamageBonus DamageBonus `json:"DamageBonus"`
}

// SaveDataAmmoTag 弾薬の口径タグ。セーブデータでは任意文字列を許容する
type SaveDataAmmoTag = string

// SaveDataAttackCategoryData 攻撃種別
type SaveDataAttackCategoryData struct {
	// Label 表示用ラベル
	Label SaveDataAttackTypeLabel `json:"Label"`

	// Range 近接/遠距離の区分
	Range SaveDataAttackRangeType `json:"Range"`

	// Type 武器種別の識別子
	Type SaveDataAttackTypeId `json:"Type"`
}

// SaveDataAttackRangeType 攻撃射程。types.tspに対応するenumがないためセーブ固有で定義する
type SaveDataAttackRangeType string

// SaveDataAttackTypeId 武器種別の識別子
type SaveDataAttackTypeId = string

// SaveDataAttackTypeLabel 攻撃種別の表示用ラベル
type SaveDataAttackTypeLabel = string

// SaveDataBodyPartHealth 1つの部位の健康状態
type SaveDataBodyPartHealth struct {
	// Conditions この部位に付与されている状態の配列
	Conditions *[]SaveDataHealthCondition `json:"Conditions,omitempty"`
}

// SaveDataCameraComponent カメラ状態
type SaveDataCameraComponent struct {
	// Scale カメラのスケール値
	Scale SaveDataCameraScale `json:"Scale"`

	// ScaleTo カメラのスケール値
	ScaleTo SaveDataCameraScale `json:"ScaleTo"`

	// TargetX カメラ座標
	TargetX SaveDataCameraPosition `json:"TargetX"`

	// TargetY カメラ座標
	TargetY SaveDataCameraPosition `json:"TargetY"`

	// X カメラ座標
	X SaveDataCameraPosition `json:"X"`

	// Y カメラ座標
	Y SaveDataCameraPosition `json:"Y"`
}

// SaveDataCameraPosition カメラ座標
type SaveDataCameraPosition = float64

// SaveDataCameraScale カメラのスケール値
type SaveDataCameraScale = float64

// SaveDataChecksum SHA-256チェックサム
type SaveDataChecksum = string

// SaveDataCombatPolicyType 戦闘ポリシー
type SaveDataCombatPolicyType string

// SaveDataCommandTableComponent 戦闘コマンドテーブル名
type SaveDataCommandTableComponent struct {
	// Name コマンドテーブル名
	Name string `json:"Name"`
}

// SaveDataComponentsMap エンティティが持つコンポーネントのマップ。
// 存在するコンポーネントのみがキーとして含まれる。
// 保存対象: プレイヤー、バックパック内アイテム、装備中アイテム
type SaveDataComponentsMap struct {
	// Abilities 能力値
	Abilities *SaveDataAbilitiesComponent `json:"Abilities,omitempty"`

	// Ammo 弾薬設定
	Ammo *SaveDataAmmoComponent `json:"Ammo,omitempty"`

	// Camera カメラ状態
	Camera *SaveDataCameraComponent `json:"Camera,omitempty"`

	// CommandTable 戦闘コマンドテーブル名
	CommandTable *SaveDataCommandTableComponent `json:"CommandTable,omitempty"`

	// Consumable 消費可能アイテム設定
	Consumable *SaveDataConsumableComponent `json:"Consumable,omitempty"`

	// Description 説明文
	Description *SaveDataDescriptionComponent `json:"Description,omitempty"`

	// FactionAllyData 味方派閥マーカー
	FactionAllyData *SaveDataMarkerComponent `json:"FactionAllyData,omitempty"`

	// Fire 遠距離攻撃設定
	Fire *SaveDataFireComponent `json:"Fire,omitempty"`

	// GridElement グリッド上の位置
	GridElement *SaveDataGridElementComponent `json:"GridElement,omitempty"`

	// HP 生命力
	HP *SaveDataHPComponent `json:"HP,omitempty"`

	// HealthStatus 部位ごとの健康状態
	HealthStatus *SaveDataHealthStatusComponent `json:"HealthStatus,omitempty"`

	// InflictsDamage ダメージ効果
	InflictsDamage *SaveDataInflictsDamageComponent `json:"InflictsDamage,omitempty"`

	// LightSource 光源設定
	LightSource *SaveDataLightSourceComponent `json:"LightSource,omitempty"`

	// LocationEquipped 装備位置。エンティティ参照を含む
	LocationEquipped *SaveDataLocationEquippedComponent `json:"LocationEquipped,omitempty"`

	// LocationInBackpack バックパック内の位置。所有者エンティティ参照を含む
	LocationInBackpack *SaveDataLocationInBackpackComponent `json:"LocationInBackpack,omitempty"`

	// Melee 近接攻撃設定
	Melee *SaveDataMeleeComponent `json:"Melee,omitempty"`

	// MemberAppearance 隊員の外見情報
	MemberAppearance *SaveDataMemberAppearanceComponent `json:"MemberAppearance,omitempty"`

	// Name エンティティ名
	Name *SaveDataNameComponent `json:"Name,omitempty"`

	// Player プレイヤーマーカー
	Player *SaveDataMarkerComponent `json:"Player,omitempty"`

	// ProvidesHealing 回復効果
	ProvidesHealing *SaveDataProvidesHealingComponent `json:"ProvidesHealing,omitempty"`

	// ProvidesNutrition 栄養補給効果
	ProvidesNutrition *SaveDataProvidesNutritionComponent `json:"ProvidesNutrition,omitempty"`

	// Recipe レシピ設定
	Recipe *SaveDataRecipeComponent `json:"Recipe,omitempty"`

	// Skills スキルセット
	Skills *SaveDataSkillsComponent `json:"Skills,omitempty"`

	// SpriteRender スプライト描画設定
	SpriteRender *SaveDataSpriteRenderComponent `json:"SpriteRender,omitempty"`

	// SquadMember 隊員コンポーネント。リーダーへのエンティティ参照を含む
	SquadMember *SaveDataSquadMemberComponent `json:"SquadMember,omitempty"`

	// SquadPolicy 隊員の自律行動ポリシー
	SquadPolicy *SaveDataSquadPolicyComponent `json:"SquadPolicy,omitempty"`

	// Stackable スタック可能マーカー
	Stackable *SaveDataMarkerComponent `json:"Stackable,omitempty"`

	// StatsChanged ステータス変更フラグ
	StatsChanged *SaveDataMarkerComponent `json:"StatsChanged,omitempty"`

	// TurnBased アクションポイントと速度
	TurnBased *SaveDataTurnBasedComponent `json:"TurnBased,omitempty"`

	// Value 売買価格
	Value *SaveDataValueComponent `json:"Value,omitempty"`

	// Wallet 所持金
	Wallet *SaveDataWalletComponent `json:"Wallet,omitempty"`

	// Wearable 防具設定
	Wearable *SaveDataWearableComponent `json:"Wearable,omitempty"`

	// WeightCapacity 所持重量
	WeightCapacity *SaveDataWeightCapacityComponent `json:"WeightCapacity,omitempty"`
}

// SaveDataConsumableComponent 消費可能アイテム設定
type SaveDataConsumableComponent struct {
	// TargetType 対象指定
	TargetType SaveDataTargetTypeData `json:"TargetType"`

	// UsableScene 使用可能シーン
	UsableScene UsableScene `json:"UsableScene"`
}

// SaveDataCurrency 所持金
type SaveDataCurrency = int32

// SaveDataDamageAmount ダメージ量
type SaveDataDamageAmount = int32

// SaveDataDescriptionComponent 説明文
type SaveDataDescriptionComponent struct {
	// Description 説明文。セーブデータでは空文字を許容する
	Description SaveDataEntityDescription `json:"Description"`
}

// SaveDataEntityDescription 説明文。セーブデータでは空文字を許容する
type SaveDataEntityDescription = string

// SaveDataEntityGeneration エンティティ世代番号
type SaveDataEntityGeneration = uint32

// SaveDataEntityIndex エンティティインデックス
type SaveDataEntityIndex = uint32

// SaveDataEntityName エンティティ名。セーブデータでは空文字を許容する
type SaveDataEntityName = string

// SaveDataEntitySaveData 単一エンティティのセーブデータ
type SaveDataEntitySaveData struct {
	// Components コンポーネントのマップ。キーはコンポーネント型名で、値は型ごとに異なる
	Components SaveDataComponentsMap `json:"components"`

	// StableId エンティティの安定ID
	StableId SaveDataStableID `json:"stable_id"`
}

// SaveDataEquipBonusData 装備ボーナス
type SaveDataEquipBonusData struct {
	// Agility 能力値ボーナス
	Agility SaveDataAbilityBonus `json:"Agility"`

	// Dexterity 能力値ボーナス
	Dexterity SaveDataAbilityBonus `json:"Dexterity"`

	// Sensation 能力値ボーナス
	Sensation SaveDataAbilityBonus `json:"Sensation"`

	// Strength 能力値ボーナス
	Strength SaveDataAbilityBonus `json:"Strength"`

	// Vitality 能力値ボーナス
	Vitality SaveDataAbilityBonus `json:"Vitality"`
}

// SaveDataEquipmentSlotNumber 装備スロット番号
type SaveDataEquipmentSlotNumber = int32

// SaveDataEventState イベントの状態
type SaveDataEventState struct {
	// Active イベントがアクティブかどうか
	Active bool `json:"active"`

	// Seen イベントが表示済みかどうか
	Seen bool `json:"seen"`
}

// SaveDataFireComponent 遠距離攻撃設定
type SaveDataFireComponent struct {
	// Accuracy 命中率。0で必中なし、100で必中
	Accuracy Accuracy `json:"Accuracy"`

	// AmmoTag 使用する弾薬の口径タグ
	AmmoTag SaveDataAmmoTag `json:"AmmoTag"`

	// AttackCategory 攻撃種別
	AttackCategory SaveDataAttackCategoryData `json:"AttackCategory"`

	// AttackCount 1ターンあたりの攻撃回数
	AttackCount AttackCount `json:"AttackCount"`

	// Cost 行動コスト
	Cost ActionCost `json:"Cost"`

	// Damage 基本ダメージ
	Damage BaseDamage `json:"Damage"`

	// Element 攻撃属性
	Element Element `json:"Element"`

	// LoadedAccuracyBonus 装填中の弾薬による命中修正値
	LoadedAccuracyBonus AccuracyBonus `json:"LoadedAccuracyBonus"`

	// LoadedDamageBonus 装填中の弾薬によるダメージ修正値
	LoadedDamageBonus DamageBonus `json:"LoadedDamageBonus"`

	// Magazine 現在の装弾数
	Magazine SaveDataMagazine `json:"Magazine"`

	// MagazineSize 最大装弾数
	MagazineSize MagazineSize `json:"MagazineSize"`

	// ReloadEffort リロード完了に必要な総工数
	ReloadEffort ReloadEffort `json:"ReloadEffort"`

	// TargetType 対象指定
	TargetType SaveDataTargetTypeData `json:"TargetType"`
}

// SaveDataFloatPool 浮動小数点プール。最大値と現在値を持つ
type SaveDataFloatPool struct {
	// Current プール現在値 (浮動小数点)
	Current SaveDataPoolFloatCurrent `json:"Current"`

	// Max プール最大値 (浮動小数点)
	Max SaveDataPoolFloatMax `json:"Max"`
}

// SaveDataGameProgress ゲーム進行状態
type SaveDataGameProgress struct {
	// ClearedDungeons クリア済みダンジョンのマップ。キーはダンジョン名
	ClearedDungeons map[string]bool `json:"cleared_dungeons"`

	// Events イベント状態のマップ。キーはイベント名
	Events map[string]SaveDataEventState `json:"events"`
}

// SaveDataGridElementComponent グリッド上の位置 (タイル座標)
type SaveDataGridElementComponent struct {
	// X タイル座標
	X SaveDataTileCoord `json:"X"`

	// Y タイル座標
	Y SaveDataTileCoord `json:"Y"`
}

// SaveDataHPComponent 生命力。最大値と現在値を持つ
type SaveDataHPComponent struct {
	// Current プール現在値 (整数)
	Current SaveDataPoolCurrent `json:"Current"`

	// Max プール最大値 (整数)
	Max SaveDataPoolMax `json:"Max"`
}

// SaveDataHealNumeral 固定回復量
type SaveDataHealNumeral = int32

// SaveDataHealingAmountData 回復量データ。typeフィールドで計算方式を判別する
type SaveDataHealingAmountData struct {
	// Numeral 固定回復量。typeが"numeral"の場合に使用する
	Numeral *SaveDataHealNumeral `json:"numeral,omitempty"`

	// Ratio 最大HPに対する回復割合 (0.0-1.0)。typeが"ratio"の場合に使用する
	Ratio *HealRatio `json:"ratio,omitempty"`

	// Type 回復量の計算方式
	Type SaveDataHealingAmountType `json:"type"`
}

// SaveDataHealingAmountType 回復量の計算方式。types.tspのHealingValueTypeとは値が異なるためセーブ固有で定義する
type SaveDataHealingAmountType string

// SaveDataHealthCondition 部位に付与される1つの状態
type SaveDataHealthCondition struct {
	// Effects この状態によるステータスへの影響
	Effects *[]SaveDataStatEffect `json:"Effects,omitempty"`

	// Severity 重症度
	Severity int32 `json:"Severity"`

	// Timer 進行度タイマー
	Timer float64 `json:"Timer"`

	// Type 状態の種類
	Type string `json:"Type"`
}

// SaveDataHealthStatusComponent 部位ごとの健康状態
type SaveDataHealthStatusComponent struct {
	// Parts 部位ごとの健康情報の配列
	Parts []SaveDataBodyPartHealth `json:"Parts"`
}

// SaveDataInflictsDamageComponent ダメージ効果
type SaveDataInflictsDamageComponent struct {
	// Amount ダメージ量
	Amount SaveDataDamageAmount `json:"Amount"`
}

// SaveDataIntPool 整数プール。最大値と現在値を持つ
type SaveDataIntPool struct {
	// Current プール現在値 (整数)
	Current SaveDataPoolCurrent `json:"Current"`

	// Max プール最大値 (整数)
	Max SaveDataPoolMax `json:"Max"`
}

// SaveDataItemHandlingPolicyType アイテム処理ポリシー
type SaveDataItemHandlingPolicyType string

// SaveDataItemPickupPolicyType アイテム回収ポリシー
type SaveDataItemPickupPolicyType string

// SaveDataLightRadius 光源の到達半径 (タイル単位)。無効時は0を許容する
type SaveDataLightRadius = int32

// SaveDataLightSourceComponent 光源設定
type SaveDataLightSourceComponent struct {
	// Color RGBA色
	Color SaveDataRGBAColor `json:"Color"`

	// Enabled 有効/無効
	Enabled LightEnabled `json:"Enabled"`

	// Radius 光の到達半径 (タイル単位)
	Radius SaveDataLightRadius `json:"Radius"`
}

// SaveDataLocationEquippedComponent 装備位置コンポーネント。
// Ownerフィールドはエンティティ参照のため、StableIDに変換してシリアライズする
type SaveDataLocationEquippedComponent struct {
	// EquipmentSlot 装備スロット番号
	EquipmentSlot SaveDataEquipmentSlotNumber `json:"EquipmentSlot"`

	// OwnerRef 装備者のStableID
	OwnerRef SaveDataStableID `json:"OwnerRef"`
}

// SaveDataLocationInBackpackComponent バックパック位置コンポーネント。
// Ownerフィールドはエンティティ参照のため、StableIDに変換してシリアライズする
type SaveDataLocationInBackpackComponent struct {
	// OwnerRef 所有者のStableID
	OwnerRef SaveDataStableID `json:"OwnerRef"`
}

// SaveDataMagazine 現在の装弾数
type SaveDataMagazine = int32

// SaveDataMarkerComponent マーカーコンポーネント。データを持たず、存在の有無だけが意味を持つ
type SaveDataMarkerComponent = map[string]interface{}

// SaveDataMaterialName レシピ素材名
type SaveDataMaterialName = string

// SaveDataMeleeComponent 近接攻撃設定
type SaveDataMeleeComponent struct {
	// Accuracy 命中率。0で必中なし、100で必中
	Accuracy Accuracy `json:"Accuracy"`

	// AttackCategory 攻撃種別
	AttackCategory SaveDataAttackCategoryData `json:"AttackCategory"`

	// AttackCount 1ターンあたりの攻撃回数
	AttackCount AttackCount `json:"AttackCount"`

	// Cost 行動コスト
	Cost ActionCost `json:"Cost"`

	// Damage 基本ダメージ
	Damage BaseDamage `json:"Damage"`

	// Element 攻撃属性
	Element Element `json:"Element"`

	// TargetType 対象指定
	TargetType SaveDataTargetTypeData `json:"TargetType"`
}

// SaveDataMemberAppearanceComponent 隊員の外見情報
type SaveDataMemberAppearanceComponent struct {
	// SpriteKey スプライトキー。セーブデータではパターン制約を適用しない
	SpriteKey SaveDataSpriteKey `json:"SpriteKey"`
}

// SaveDataMovementPolicyType 移動ポリシー
type SaveDataMovementPolicyType string

// SaveDataNameComponent エンティティ名
type SaveDataNameComponent struct {
	// Name エンティティ名。セーブデータでは空文字を許容する
	Name SaveDataEntityName `json:"Name"`
}

// SaveDataPlannerType 行動計画の種別
type SaveDataPlannerType string

// SaveDataPoolCurrent プール現在値 (整数)
type SaveDataPoolCurrent = int32

// SaveDataPoolFloatCurrent プール現在値 (浮動小数点)
type SaveDataPoolFloatCurrent = float64

// SaveDataPoolFloatMax プール最大値 (浮動小数点)
type SaveDataPoolFloatMax = float64

// SaveDataPoolMax プール最大値 (整数)
type SaveDataPoolMax = int32

// SaveDataProvidesHealingComponent 回復効果。Amounterインターフェースを具体型に分解してシリアライズする
type SaveDataProvidesHealingComponent struct {
	// Amount 回復量データ。typeフィールドで計算方式を判別する
	Amount SaveDataHealingAmountData `json:"amount"`
}

// SaveDataProvidesNutritionComponent 栄養補給効果
type SaveDataProvidesNutritionComponent struct {
	// Amount 栄養価
	Amount NutritionAmount `json:"Amount"`
}

// SaveDataRGBAColor RGBA色。各チャネル0-255
type SaveDataRGBAColor struct {
	// A RGBA色チャネル値 (0-255)
	A ColorChannel `json:"A"`

	// B RGBA色チャネル値 (0-255)
	B ColorChannel `json:"B"`

	// G RGBA色チャネル値 (0-255)
	G ColorChannel `json:"G"`

	// R RGBA色チャネル値 (0-255)
	R ColorChannel `json:"R"`
}

// SaveDataRecipeComponent レシピ設定
type SaveDataRecipeComponent struct {
	Inputs []SaveDataRecipeInputData `json:"Inputs"`
}

// SaveDataRecipeInputData レシピ素材
type SaveDataRecipeInputData struct {
	// Amount 素材必要数
	Amount MaterialAmount `json:"Amount"`

	// Name レシピ素材名
	Name SaveDataMaterialName `json:"Name"`
}

// SaveDataSaveData セーブデータの最上位構造。ファイルに保存されるJSON全体を表す
type SaveDataSaveData struct {
	// Checksum データ改ざん検知用SHA-256ハッシュ値
	Checksum SaveDataChecksum `json:"checksum"`

	// Timestamp 保存日時 (RFC3339形式)
	Timestamp time.Time `json:"timestamp"`

	// Version セーブデータのバージョン。現在は "1.0.0" のみ
	Version SaveDataSaveDataVersion `json:"version"`

	// World ワールドデータ
	World SaveDataWorldSaveData `json:"world"`
}

// SaveDataSaveDataVersion セーブデータのバージョン。現在は "1.0.0" のみ
type SaveDataSaveDataVersion string

// SaveDataSkillEntry 個別スキルの状態
type SaveDataSkillEntry struct {
	// ExpCurrent 蓄積経験値
	ExpCurrent int32 `json:"ExpCurrent"`

	// ExpMax 経験値の最大値
	ExpMax int32 `json:"ExpMax"`

	// Value スキル値
	Value int32 `json:"Value"`
}

// SaveDataSkillsComponent スキルセット
type SaveDataSkillsComponent struct {
	// Data スキルIDをキーとしたスキルデータのマップ
	Data map[string]SaveDataSkillEntry `json:"Data"`
}

// SaveDataSpeed APの毎ターン回復量
type SaveDataSpeed = int32

// SaveDataSpriteDepth スプライト描画深度
type SaveDataSpriteDepth = int32

// SaveDataSpriteKey スプライトキー。セーブデータではパターン制約を適用しない
type SaveDataSpriteKey = string

// SaveDataSpriteRenderComponent スプライト描画設定
type SaveDataSpriteRenderComponent struct {
	AnimKeys *[]SaveDataSpriteKey `json:"AnimKeys,omitempty"`

	// Depth スプライト描画深度
	Depth SaveDataSpriteDepth `json:"Depth"`

	// Options Ebitengine DrawImageOptions。レンダラ内部状態
	Options *map[string]interface{} `json:"Options,omitempty"`

	// SpriteKey スプライトキー。セーブデータではパターン制約を適用しない
	SpriteKey SaveDataSpriteKey `json:"SpriteKey"`

	// SpriteSheetName スプライトシート名。セーブデータではパターン制約を適用しない
	SpriteSheetName SaveDataSpriteSheetName `json:"SpriteSheetName"`
}

// SaveDataSpriteSheetName スプライトシート名。セーブデータではパターン制約を適用しない
type SaveDataSpriteSheetName = string

// SaveDataSquadMemberComponent 隊員コンポーネント。
// Leaderフィールドはエンティティ参照のため、StableIDに変換してシリアライズする
type SaveDataSquadMemberComponent struct {
	// Active 同行中かどうか
	Active bool `json:"Active"`

	// LeaderRef リーダーのStableID
	LeaderRef SaveDataStableID `json:"LeaderRef"`
}

// SaveDataSquadPolicyComponent AIの行動ポリシー
type SaveDataSquadPolicyComponent struct {
	// CombatCurrent 戦闘ポリシー
	CombatCurrent SaveDataCombatPolicyType `json:"CombatCurrent"`

	// CombatDefault 戦闘ポリシー
	CombatDefault SaveDataCombatPolicyType `json:"CombatDefault"`

	// ItemHandling アイテム処理ポリシー
	ItemHandling SaveDataItemHandlingPolicyType `json:"ItemHandling"`

	// ItemPickup アイテム回収ポリシー
	ItemPickup SaveDataItemPickupPolicyType `json:"ItemPickup"`

	// Movement 移動ポリシー
	Movement SaveDataMovementPolicyType `json:"Movement"`

	// Planner 行動計画の種別
	Planner SaveDataPlannerType `json:"Planner"`
}

// SaveDataStableID エンティティの安定ID。セーブ/ロード間でエンティティを一意に識別する
type SaveDataStableID struct {
	// Generation 世代番号。同一インデックスの再利用を区別する
	Generation SaveDataEntityGeneration `json:"generation"`

	// Index エンティティインデックス
	Index SaveDataEntityIndex `json:"index"`
}

// SaveDataStatEffect ステータスへの影響
type SaveDataStatEffect struct {
	// Stat 影響を受けるステータスの種類
	Stat string `json:"Stat"`

	// Value 修正値
	Value int32 `json:"Value"`
}

// SaveDataTargetTypeData 対象指定
type SaveDataTargetTypeData struct {
	// TargetGroup ターゲットグループ
	TargetGroup TargetGroup `json:"TargetGroup"`

	// TargetNum ターゲット数
	TargetNum TargetNum `json:"TargetNum"`
}

// SaveDataTileCoord タイル座標
type SaveDataTileCoord = int32

// SaveDataTurnBasedComponent アクションポイントと速度
type SaveDataTurnBasedComponent struct {
	// AP アクションポイント
	AP SaveDataIntPool `json:"AP"`

	// Speed APの毎ターン回復量
	Speed SaveDataSpeed `json:"Speed"`
}

// SaveDataValueComponent 売買価格
type SaveDataValueComponent struct {
	// Value 売買価格
	Value ItemValue `json:"Value"`
}

// SaveDataWalletComponent 所持金
type SaveDataWalletComponent struct {
	// Currency 所持金
	Currency SaveDataCurrency `json:"Currency"`
}

// SaveDataWearableComponent 防具設定
type SaveDataWearableComponent struct {
	// Defense 防御力
	Defense ArmorDefense `json:"Defense"`

	// EquipBonus 装備ボーナス
	EquipBonus SaveDataEquipBonusData `json:"EquipBonus"`

	// EquipmentCategory 装備部位
	EquipmentCategory EquipmentCategory `json:"EquipmentCategory"`

	// InsulationCold 耐寒性能
	InsulationCold InsulationCold `json:"InsulationCold"`

	// InsulationHeat 耐暑性能
	InsulationHeat InsulationHeat `json:"InsulationHeat"`
}

// SaveDataWeightCapacityComponent 所持重量。最大値と現在値を持つ
type SaveDataWeightCapacityComponent struct {
	// Current プール現在値 (整数)
	Current SaveDataPoolCurrent `json:"Current"`

	// Max プール最大値 (整数)
	Max SaveDataPoolMax `json:"Max"`
}

// SaveDataWorldSaveData ワールド全体のセーブデータ。プレイヤーと所持品のみを保存する
type SaveDataWorldSaveData struct {
	// Entities エンティティの配列。StableIDでソートされる
	Entities []SaveDataEntitySaveData `json:"entities"`

	// GameProgress ゲーム進行状態
	GameProgress *SaveDataGameProgress `json:"game_progress,omitempty"`
}

// Sensation 感覚。命中率と回避率に影響する
type Sensation = int32

// ShelterType 遮蔽タイプ
type ShelterType float32

// SkillBook スキル本設定
type SkillBook struct {
	// MaxLevel スキルレベル
	MaxLevel SkillLevel `json:"maxLevel"`

	// RequiredLevel スキルレベル
	RequiredLevel SkillLevel `json:"requiredLevel"`

	// TargetSkill スキルID
	TargetSkill SkillId `json:"targetSkill"`
}

// SkillId スキルID
type SkillId = string

// SkillLevel スキルレベル
type SkillLevel = int32

// SpriteDepth スプライト描画深度
type SpriteDepth float32

// SpriteKey スプライトキー
type SpriteKey = string

// SpriteRender スプライトレンダー設定
type SpriteRender struct {
	// Depth スプライト描画深度
	Depth SpriteDepth `json:"depth"`

	// SpriteKey スプライトキー
	SpriteKey SpriteKey `json:"spriteKey"`

	// SpriteSheetName スプライトシート名
	SpriteSheetName SpriteSheetName `json:"spriteSheetName"`
}

// SpriteSheet スプライトシート
type SpriteSheet struct {
	// Name エンティティ名
	Name EntityName `json:"name"`

	// Path 画像ファイルパス
	Path ImagePath `json:"path"`
}

// SpriteSheetList スプライトシート一覧
type SpriteSheetList struct {
	Data       []SpriteSheet `json:"data"`
	TotalCount int32         `json:"totalCount"`
}

// SpriteSheetName スプライトシート名
type SpriteSheetName = string

// Stackable スタック可能かどうか
type Stackable = bool

// StorageRaw 収納ローデータ
type StorageRaw struct {
	// LootCountMax 初期アイテムの最大数
	LootCountMax *int32 `json:"lootCountMax,omitempty"`

	// LootCountMin 初期アイテムの最小数
	LootCountMin *int32 `json:"lootCountMin,omitempty"`

	// LootTableName 初期アイテムの抽選に使うItemTable名
	LootTableName *EntityName `json:"lootTableName,omitempty"`

	// MaxWeight 収納の最大格納重量
	MaxWeight Weight `json:"maxWeight"`
}

// Strength 筋力。物理ダメージに影響する
type Strength = int32

// TargetGroup ターゲットグループ
type TargetGroup string

// TargetNum ターゲット数
type TargetNum string

// Tile タイル
type Tile struct {
	// BlockPass 通行を妨げるかどうか
	BlockPass BlocksPassage `json:"blockPass"`

	// BlockView 視線を遮るかどうか
	BlockView BlocksView `json:"blockView"`

	// Description 説明文
	Description EntityDescription `json:"description"`

	// Foliage 植生タイプ
	Foliage FoliageType `json:"foliage"`

	// Name エンティティ名
	Name EntityName `json:"name"`

	// Shelter 遮蔽タイプ
	Shelter ShelterType `json:"shelter"`

	// SpriteRender スプライトレンダー設定
	SpriteRender SpriteRender `json:"spriteRender"`

	// Water 水タイプ
	Water WaterType `json:"water"`
}

// TileList タイル一覧
type TileList struct {
	Data       []Tile `json:"data"`
	TotalCount int32  `json:"totalCount"`
}

// UsableScene 使用可能シーン
type UsableScene string

// ViewDistance AI視界距離（タイル単位）
type ViewDistance = int32

// Vitality 体力。HPに影響する
type Vitality = int32

// WarpNextTriggerRaw 次階層ワープトリガー
type WarpNextTriggerRaw = map[string]interface{}

// WarpPrevTriggerRaw 前階層ワープトリガー
type WarpPrevTriggerRaw = map[string]interface{}

// WaterType 水タイプ
type WaterType float32

// Wearable 装備可能設定
type Wearable struct {
	// Defense 防具の防御力
	Defense ArmorDefense `json:"defense"`

	// EquipmentCategory 装備部位
	EquipmentCategory EquipmentCategory `json:"equipmentCategory"`

	// InsulationCold 耐寒性能
	InsulationCold InsulationCold `json:"insulationCold"`

	// InsulationHeat 耐暑性能
	InsulationHeat InsulationHeat `json:"insulationHeat"`
}

// Weight 重量。単位付き文字列で指定する。例: "500 g" "2 kg" "1 mg"
type Weight = string

// CommandTablesCreateJSONRequestBody defines body for CommandTablesCreate for application/json ContentType.
type CommandTablesCreateJSONRequestBody = CommandTable

// CommandTablesUpdateJSONRequestBody defines body for CommandTablesUpdate for application/json ContentType.
type CommandTablesUpdateJSONRequestBody = CommandTable

// DropTablesCreateJSONRequestBody defines body for DropTablesCreate for application/json ContentType.
type DropTablesCreateJSONRequestBody = DropTable

// DropTablesUpdateJSONRequestBody defines body for DropTablesUpdate for application/json ContentType.
type DropTablesUpdateJSONRequestBody = DropTable

// EnemyTablesCreateJSONRequestBody defines body for EnemyTablesCreate for application/json ContentType.
type EnemyTablesCreateJSONRequestBody = EnemyTable

// EnemyTablesUpdateJSONRequestBody defines body for EnemyTablesUpdate for application/json ContentType.
type EnemyTablesUpdateJSONRequestBody = EnemyTable

// ItemGroupsCreateJSONRequestBody defines body for ItemGroupsCreate for application/json ContentType.
type ItemGroupsCreateJSONRequestBody = ItemGroup

// ItemGroupsUpdateJSONRequestBody defines body for ItemGroupsUpdate for application/json ContentType.
type ItemGroupsUpdateJSONRequestBody = ItemGroup

// ItemTablesCreateJSONRequestBody defines body for ItemTablesCreate for application/json ContentType.
type ItemTablesCreateJSONRequestBody = ItemTable

// ItemTablesUpdateJSONRequestBody defines body for ItemTablesUpdate for application/json ContentType.
type ItemTablesUpdateJSONRequestBody = ItemTable

// ItemsCreateJSONRequestBody defines body for ItemsCreate for application/json ContentType.
type ItemsCreateJSONRequestBody = Item

// ItemsUpdateJSONRequestBody defines body for ItemsUpdate for application/json ContentType.
type ItemsUpdateJSONRequestBody = Item

// MembersCreateJSONRequestBody defines body for MembersCreate for application/json ContentType.
type MembersCreateJSONRequestBody = Member

// MembersUpdateJSONRequestBody defines body for MembersUpdate for application/json ContentType.
type MembersUpdateJSONRequestBody = Member

// PalettesCreateJSONRequestBody defines body for PalettesCreate for application/json ContentType.
type PalettesCreateJSONRequestBody = Palette

// PalettesUpdateJSONRequestBody defines body for PalettesUpdate for application/json ContentType.
type PalettesUpdateJSONRequestBody = Palette

// ProfessionsCreateJSONRequestBody defines body for ProfessionsCreate for application/json ContentType.
type ProfessionsCreateJSONRequestBody = Profession

// ProfessionsUpdateJSONRequestBody defines body for ProfessionsUpdate for application/json ContentType.
type ProfessionsUpdateJSONRequestBody = Profession

// PropsCreateJSONRequestBody defines body for PropsCreate for application/json ContentType.
type PropsCreateJSONRequestBody = Prop

// PropsUpdateJSONRequestBody defines body for PropsUpdate for application/json ContentType.
type PropsUpdateJSONRequestBody = Prop

// RecipesCreateJSONRequestBody defines body for RecipesCreate for application/json ContentType.
type RecipesCreateJSONRequestBody = Recipe

// RecipesUpdateJSONRequestBody defines body for RecipesUpdate for application/json ContentType.
type RecipesUpdateJSONRequestBody = Recipe

// SpriteSheetsCreateJSONRequestBody defines body for SpriteSheetsCreate for application/json ContentType.
type SpriteSheetsCreateJSONRequestBody = SpriteSheet

// SpriteSheetsUpdateJSONRequestBody defines body for SpriteSheetsUpdate for application/json ContentType.
type SpriteSheetsUpdateJSONRequestBody = SpriteSheet

// TilesCreateJSONRequestBody defines body for TilesCreate for application/json ContentType.
type TilesCreateJSONRequestBody = Tile

// TilesUpdateJSONRequestBody defines body for TilesUpdate for application/json ContentType.
type TilesUpdateJSONRequestBody = Tile
