// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1tV9TItvBf6ZXnfJi5J2g7c33WGb88C4VR7kVkATM+5zl6Z8XuEnLtTvokaV/OuazV6dYRFMR3R2VU",
	"RhQUQR2d4xvojwnphk/zF55VVXmpJFWVpGlgRL/MAKZqV+3atfeu/fpPIacWS6oCFEMXdv1T0HNDoCih",
	"H9uPyAXZkAH6JQ/0nCaXDFlVhF3CSm3JPnfbrkwLolDS1BLQ3O+kQTjoFPzxTxo4KuwS/td2H8J2Z/rt",
	"7c5nw6KQB0eBooO4ER3OZ2jESQNoCaB0eB8Oi4IOFF3C6+eP6vc+hKMMDSiDxlDsIPe7YVE4LhtSEiR8",
	"7343PCwKGvh7WdZAXtj1N38CAj65ARIFoodyH5WHRcE4VQLCLkE98t8gZ8BFtedyZU3KnYoepn1pafn1",
	"fOPCWatSzVrmjP3hzPLrect8bJk3rIq5I+v/URCFo6pWlAxhlyArxtdfCaJQlE7KxXJR2LUjmxWFoqzg",
	"37LeGmTFAINAIxexW1XKOmclK/cn6/P3MX0lBdiGfqXBhLPvUXWDQsdTY/b5a1b1hVV9Y9VG1rw9n/iD",
	"cOrXJurjr+qVGatSxTBX7/1omXP20vPVux8s86ZVPd+KrRaLKgWri+9Xrj9ZmZ23F25F72v4RLi3NvDx",
	"sChIxaI6IA3GjnM+g3dXKkqDIBG0DuLT8A0hpxFDm6BSv79QGnKs6ger+kwQBaBA/P5N+KZYFERBk48W",
	"ALx5Q6BQQP8KtMFTP+Tgbz4U3dBkBW2uXSuqWofPz4KgVn/61T7zyjIX4A/vp+xzt7lH/s0338TSm2FI",
	"uWN7JAMMqhqN7K6+q1+uNWYX7JEHxOa+7eofEESh/+CBvg74/97O9j5BFPa193Ts/a5HEIW+rm+7OwVR",
	"2NPecwD+vvvAQfp+MXy1rFDu1g6I1NqiVXthmVXLvGtVz1nmAl6SfftO/dqzGIondr+Dtvvdkg4wjVCO",
	"9e7b+uQTq1axalNwEdXXcbiORfbugpo7pvdKuk6FuFq5tTI1ZlUv2w9nLfOyVT1vmect85Fl/miZ8HI7",
	"Mx5R1QKQFH/G72VwgsKZHl5vvLplVS+vmguJ5lLVYxQCmHximQuMq68fkwuFWLkGP0KTD4uCoRpSofPo",
	"UVUz4sb1ASkvK4POx+HrS05Eu6571IKq7RmSFAUUorvq27u7fWX0V6tmWrX7Vm3cqs3ZlenMF9m2r3bu",
	"/JI86LKsGH8RaKe5Ry0ekYxetSDnTg2gf43gbuTh6o2frNrPVu2xVX0FqahStaqzkKBrP1rV+85/zQX8",
	"Zf1mFeIacff69TerZ3+GxLBwq/H+kcfg3RsooYsD/3BcykMOIw8qqgaol2yPWixKSn5AOlKgrBLKrtod",
	"tKZRuCB44a5btbnIaQPF0JwfZQMUY7kvCbZTMTSkQzmLkzRNQr8rUjFWcetUDNk41QO/DJMBGi56S6NT",
	"QngZiVHgntWIVXscQccJIJXiVUFy7aJwAsiDQ0aCMdqpg/jT8IYdqN5UcTvulmlaC2vDy68rKw9nIlvN",
	"S4bU1LHTThzdXI/jRzhq+KJFxLYhCYFJ6BhQ9HKRTu/1f42s/PrOnni6Uluyqr9Y1WmEgXtsNmdI2iAw",
	"9mpquRS3+QHiU7hX9GsPvLJJxsEPh0WhrMOV9+eAEns1viM+DaOKnEYMbIJcGA19HUEVK0Q7hEhspZbN",
	"1XqQsgNV31/mSPhW9fLKu6X669stU4A7QMkY6gbHaVJj9dYF+/m0VXti1W5iBrkmXb+DfISGlI+bs42r",
	"s5Z5DQmMp1B+YFFRnbNqc/Ch1XLNv0OWCipFvV1evLXy6LlVO4sw/iFyOYoAqTP/CWIfq/v9L8OkSkxC",
	"pUdV1brV3LEBTR4cBFqfRFF36qOjVm3eqtUQvkaQyH1i1RYFxnzcSRbJ/UaHa2qJJUxr7ipqN1oqTD2Y",
	"myhJQ2tIvHmuGC1K8BJIhZjpEJk3Xt6r/3zRvjhuVaqNR2/r18/a8zcs82nwS2R1qF6un56wL73w7kdE",
	"K1q7LPaWzpXGHtYYopiBtFaIYp9QN0kOd5SVQaAqeyUD8O4uYukvID+vzVi1F6vm6/q5O1b1V4SMkbjb",
	"3FkARUB7Pzovxed36pUZQnXuOdADn6bfdvXB/w3s+66noxO+Xvfs6+ruFkShd9+BgQM9VE26UwHFU4yr",
	"X7/2W0tvvA9rE698eBFxu+ZedQAn60m5ZiTIkFSOt9V6onsYCbwmRpWk3LH90sm4Qb3OZ+4IWUk0QlZa",
	"w3h8RHqzERsmMOYvz98a/5jpTCp0yq3gTcRV2iTmhKmsg9xoxIby+En9pwv162cxUrsdQ/5Xjkbl/r6D",
	"yio8GqY8v8I2APvieBDEzkQQPAqhsFT6pbTMhdWz45b5wapU7ekZyxy3zNOW+c4yH62ary3zmVUds6qn",
	"odg0T5NqZV4tH0GmTIpSq5SLR7AW2fn3slxiPBxW7p+xqzet2iRa2Dmr+qYlvp/PnhyKJ4dK7/Bs+guq",
	"wTya6htXFRmxKlVsbV6tzS4vjWf+nKnPP7RvzpLfEDJ1X2d7BxSmB/r6Dwii0N63v9+xB8P/d3fuhf/7",
	"trNzQBCFg53tvQd6dng/feX99LX30797P+2kC2K4Fyj12aZrvCe8/CZX+h+dBzu7+/5KX4GmqRrjaj9C",
	"FP4E4epnpNm8Yb2buDNMoefMO8/8HFoE/RFFPftvJeTD2g/gRWVYK1++X73+APkxpq3aDdLajwf3gLKh",
	"SXS/xbeyRnu5m/dWXv28evsXrInFOJCS+o6acxtJEU8Hd2Dwa3+8K5ISDEafDotCznEc8vfmuRg9F1fc",
	"GMJ7MSwKwNeCuWLX+QzpVYPSP2QF9Mv/iIW1n/wW0V1BlfJJDfnEt8PiBpvTQpfEIzYPy8Gj9REZIRnn",
	"JNmmtBBKQ1iiXku1IEuDgHEhp8cbV+9SLmRWbNshtn19mCJ/9wGp0F6ku9Ps23fs94/s22/thVurZyfW",
	"7M6CsPqgEGKCGv3VvgglSXZb1qpM7tiWpSsUnqEqRrmAAGVl8HupUGagDMNdPTuBjLkjjYUb9etv7MUJ",
	"gpn1dvbt6ewZaN8LH3/tu/sPdH83AH/s+W5/Z197N5W77ZONXlV24ltCUqZycfnNGbsybVWqmL9hi4Nl",
	"zjbuvbTvn3MMzeacZT6Os9SFsE71WXZBou2VsBYSXEvj6ju7NmHVrlnVKUQzc1btEpY9fOW1JBkG0OAU",
	"//U3qe0f7W3/L9v2zQ/bDx1qO/znQ4e2+X87/Oc/0UwpXYpeLkiYgxXyVCTZTy/XKzMrtaUWmCp9cPuA",
	"ZFDB1W9dah04fbeqUw3hk0jC/4IlvOOsjnOzdum9BekUoKkOtRtIaZi2atNI5M8j5+Qjq/o06dwGKNIU",
	"Ct/JERW+TsBHnBRFIlCRi/8JTiU3YfSXNNnABt/oE++I42/mijjHbZwL+HP43ifvS/Q6CDzu4m0O5GsQ",
	"CtXAc4Y73P9yWBSOOuoQbwRSmYZFQVaOFuScoXc0IfRJ42mUHIqgAOIlO/qoCWMSoqTjch7oDl+ONYGE",
	"Pidm6CkbmpzklLwPHSEHX2UekaWhRjyqfwgAI4lFqj/0OXoNSrljSUiy3/sQvgeh8IobAe8xknLYXCRp",
	"ScAcdL8LmJikQuHAUWHX3+LGYjvTYZHDO1bPjkO1gWFFJMdF0Usek4sEmkIEd86IBiKXUh+t1MfMuACg",
	"ROLUAEVPFWUDtKrPkDhdhEy6Ug35je2zbxsT79FLDb2dI1Eba7MEe2tsmSFYFPTyEcNRoRKB7ne+Z5y+",
	"Ox3fmhzaSHKM86zKEIXpjcoba+hNdgsDJt/IVczLUOE6Uoa/7so0br+2n773THk5tVAAOeeffnnbuHD2",
	"98WRLNRofl8cjRyahzLCfJzMUOydICuuhH6ArTAY+zd1k+zFkbuQnH7NBav6m1W7TrOukOeK3pjuSVKf",
	"InAR8bjH+I4zQaVG/2Zinhm9RqC8le43D+Ymet9Ca0i8+YDBPyStAmz1sj1RbZyZYcipQUjsLmtNzMK8",
	"/UY4GAmMtSb74vhG+/zW7o/zERXjj+MecgKW2mIfnH+vNvFif+9qxCFiuf/ryq+vlt9P1e8txmp5sbaq",
	"bngonQrcK8U+YZ8Zrb+9aJlj9clR+9yb2Hc2mq1PysvUFJQzo1AlHHm2al61x8/Z70//vjjiMv45e/yn",
	"5aVxKJSTGyZ2MHfUr5a1HGBtiGFvz6kF7LngGm337m5HMdToGewjjjcmgGRIDx6GYkc5yAxTkTOD6KzZ",
	"XwmNmPaH7Nlh68odq/oExZi8sBfexBlAE5zAfufxzbK3OtFKH86sPEzwVImF5j7mQ7auD5fqFx603r/y",
	"2VsS8pZsWa8F9SohPyHtEk0hxeIiDsUK0RmZ7ck9Pu/DlhsVc0RSRoJA9WACBx7vBa+3UPNJYNqdscyn",
	"jUmzce0B9hggyvZicrnaDP4Kfu/G+23+0o9in/FAAhtD1Dc9LAqyZ3TnKjD4q2FRKATFYazAcT6FSqN6",
	"HF2dXtcJEmMvDX7urrcJ66nnBuDv0HEXbKKl87gMTnTIuiEp8cj9nvyW8eRxzlYkOAbfYshmUayYWp9N",
	"rcNT2OGOm6Qz7w8E3FM27oeMoLDZJfTzG2SDmMd8m/AG7oj1Bh6G/8m2ffPD4X+jOv9oFyIaCfLzHTLH",
	"rTHzzj5/DXknnQxPwiCiSUpeLSJDlKGpKLpaKhT2lQdRCBTy+0lIsJ2QlDyAWqEBNE02VCcWWz8haUWq",
	"8STsPYi63O+dXp0+t/x+as3O8V7fvhg+oktOkoK5UJ+s2NMz8Xmssapor2+b5EN7NtESaAVgGIAB7YkX",
	"HBa6Ymv0xcn5eNMrWlcXenwopRzWSvJ5dORSoTewnAQThS0//h2EO1u/2SE5S/g0m5k/KGZCs4ctwfmI",
	"68aF7u7SQSWNFQV2wqUGvgU/3ckacmEtdje0ZTQHZ0tdef5+ujriwnWjMRWHidgKBi91oLOkmg+/FdYf",
	"9xpvkhzrlXSdXlPDTYR3amrY5+41Fm7gEBtUSGR61B677lUX2Qn/hjLykJhzR/15Z3btTFxTjwJdp4eG",
	"m6/qD+Zb9AhqSZxC8ieUvy8UtkCjgAR30psEX0sPcsolsBwLTfg0j8mFQjNLQCUKomugMQ6qt5vUYzFo",
	"70iolB9CP4O27JGf65N3cRhzhM6awI4T+R0bxYJCxFl+Xvhv/D3RWCfeUGqmGad6hoiIi0ccMsCNhcol",
	"MVf5EQotcwHl2DzS2yBdJOANtkQY+Kxus+RB6DoyNot4/LxVm8PHSqsgFs+7EATMthIF5KDvHYcRjSuw",
	"A1qg2kYxDS8tNEYfRYVHawPsCmruGJSysabRQF0ad6RbVSZ+JPqyBVIsr8b7JdzUbedzIis8ychQEjmc",
	"JJKhGjsPNad1WBSGYg3DfhzxmixWTdiaCF2LrxI633l2oz6A3tiJ6ND5FsXGqVoCm3w//szB3wlJK/WA",
	"k0bCczgY/JyYpFcDx1NMQnyOJkke3+ZsmLxq5OVh8QM6L8c8oUW8vLSJXDwcE0pNDTj3pn5nkhKNnEQE",
	"E0kOyMvopCDEDcG5Ci7LT2KZjiQcRJLzvH8R3bW7C6Ihx3eqsipSRTES78UgCl1B3p12wGDaAVq6AWGX",
	"rgBBwnWKgkTHknSCGm0fqMthn5ldXrpiVaoDB/Z3B1IezAU3mGSkPnN+tXIvLhyT9PnoLStz5Pli9NaU",
	"awBevrTeohxr2Y1n01sTgye70SR6awJQ0j0oWc/IIjLW6y0w7pc8BVVvkVrtmRHXxNY1kJNLKZDeh76n",
	"zUT4YNLqoGgQVejIaQhiQKbRAs1IGiwPSMncn19+iwqkovgLy3zceDWx8ni+fvt1ytw3qgncwSGFSz1B",
	"lf6uRh8lSqlspD2kLjho/WIPnTVRmTABn71LHOLSpBgPxc+0bFcOdPauWOZVZ1Pr4DFkX7mN0Mn6Qsm6",
	"4X0/dmXrKHlfcB3KuBqzCdxF/dJx0CEZ0jbP5LnHxVCauuDtyWpDhKCd8vJoOpJVCeeMT1hpgjlDf+Kq",
	"E8wZklagYE3wfcJyFIwJQuT3vV+bot+vTdFP1KboIGpTtHtVxjs4VcbDkHdLtJqAHplY5gKu1MsoQhhL",
	"jqxK4j6EYMGSJiDsV/PyUZkWT0Vuwy2P8q5x7l/1M+ddL8ecVR2xqueXPyywKy3GL2EAcgg+/MbCDfvs",
	"W8u8ZlXHLPNuY+K9PTnbNEBWVO/4T5C9emArVe/0rNo7b5NW7Z19cWRldgT+XL1cHzMtM8oRXNJIFuVE",
	"JSxKkPrtt/XJ0QBZoSAH/wibA+fNEAXpVl85HXPyw6LgnWNzi8DDoytgnn34xiOkEehwV8S/ycWiymH5",
	"3Ory7WuqLt+erExIYKVOvZCO1pSZd2cMThjuYxCLPl7leXPBnrhvvz+NS9CjfI93bpqA81rGMXrL797V",
	"T0/gqon2yA2renll9rm98IZdI9FfQyCotMPRfbi14oPn2C0dAU0RLgI8cKoE8AyU2zM125h+27iKq+ag",
	"wqzIiKAMgqbhodHY4hOFhyKut3u1bSD+x97aIz+i++lYlZreZVeeAhKXXsKYhZJi/id75IE9fzFCbY4p",
	"Cm9edJDOJ67QfllFFJ+dbsyetypVOJO+zdBLUFV8+t7+MImpByjlomWOIa/8aVSr3/TI0GWpM4xa5vs7",
	"uzs74bLbe/Z2dlAjt+iYii6WhahkU3pEyiZsVKA9QnC86Xer+VO9kmbsA1KBVrVjh2VC8YsLVUFiMh/Y",
	"b19hURC5RntUBQcE0Sxk5hVinrnldz8tv77g8vSH8Fiq5/G08LMz4/bIDUFM+MZ3N4M34a0i2VPdG71H",
	"KgJN4ogCVN94yqo9Ymy/PycVkmvwGBweA5cBfxhQmx2Oo/P/b8rhvaruYQrP8Nc1zLAW6M3DDTEZjBEf",
	"n3BZcHofRf5WD8eTgweHTQ3225n67E1q8aBIkSDq8bGnRmGxb6zqc8Sq5kL6bhIwQyB3TC9Tog/697W3",
	"fbXzf1s106rOOFGY1d9w4AGbXTTTVqLJvhAkTM+WzbmdDmBG7wBcwjJ4X1nlL3kz8IvcoRn5VOVR9n6p",
	"lKT2pmWO4QcGWtcLhNhF1BQEBSyaC2ixNVz54ZBiz/9kT866WayMEeYHKAxRvLVlzlrmDct8aF+cs8z3",
	"qL7meTTT8oef4WRP3688n9qVCSdaVEwUwI7rmTtRvPaPZwL5oBUTvx2WX89zI1sCjdiaejoErDYUpcgz",
	"2xBNpNICCjwTKC8z8p0wLAr4gjcBKCyGaGVPgnKI0kQlLUzqFaOoerF3LNLeIvVK3MHcdTC6ZPjoDxXO",
	"TbkKYjSXrrwCvH4Ry/ZCwXuBpIS6X9KOAY1LZJde1K+/cWphwiNYRLSwSBa5TAkUDuOBpFfJHBaFvZqc",
	"J4qbpwRLjOaT+jNkAa5ZtdHl1+csc2F5abyxtIDq3vU2AXdfLw9c4+pd+xLkFW5BP2Oo35CMcjOciRzO",
	"RbCjEl9FrDioYKNycuECXCnXEZyAi2yid4kTAhFN5U4JnRjNJWwyJRwCVXPISItCPks4uTst5NAU3IuM",
	"5RQiLWoXLKc4RPUyFJPVCrnELmW3lDtWgnpN84v0J+EfEE3kunfCqlTro5X65OhK5UyiHXhJ22n5FBzH",
	"RWc07dvLiWsvlYCkucl6qSEHp+Deq1vn7CtT8EZNX195eL5eO2Pfe47yrFKln3qw4TA+q6KVTR8WBb+i",
	"YsvlQVgrC4kESrhTyiWEZuBeYTJ0igAeqJ7XJHhvDq5SgNLjVu5PNn576C/D94WnhI0H8rHv+GR9Gu/3",
	"gvxTQsMD+fTlhBZ7ldwQwFAcZFqwxPA44JDWHiFaG6lPTDSuviO2/feylPfT8tMuwh+d4EJTHzWVKlIT",
	"FpEIW7TM1+jlnIAHIth+Rn4zK8ejE7GilbOP7ffnna685BMZeU+Jio2t5xROCVgkNLDeHGIWUFPR9wxJ",
	"ymBT4jbZEvBrofrBqr6xp0frt19atWuIqp4hE1RZU3ZLelPwvbH8JfyC7ByvcCsfeASQnvG7eHa1ctd+",
	"+xA5ol3/YMpFoHFcJknWDRoWhYNSoQCa0Z/xQC47RCklq2cvIThEmc60kJyhXAJHzRh8foArUe2RSlLO",
	"ceenBkpOkGSbXvVPnu0l+rZM3ICR4QHEpsQk4bo+pXpD0DtxWBS+a01Lxe8CLRWJlfEtUmVNAwqtcbpP",
	"QbQYG25uov+SRq8OVkY7+eJgBb4lhEN7sXM75gTPsSN5dogHk5ImEjoR8t+4h5Cm2w/Hh+q3nUvhPcWw",
	"9wIFaBLL1B2WpMuvry+/u9+49tieeBVuSJzm2DDsLiUPTiYyhjrc+qxrsH6zduApmiCtD+bdX1nxKNSe",
	"zNF10CLHHdJtziJI2KlpkjTeGu1amJ9SP7bvnIcoNWesiolifJ7ad867ZpC5xrVnTksCXMz6SAH8IDej",
	"F/SjsV0diV5s8LW4MGov3ILfh+6yvwiRRC3/Wnt11+kHnKDpVJOBhV6QSdOBgd4MTQcG+jM0GRjoTdBs",
	"YCA96qW5wMD4gy4CxegvqEZPmV6fLNrHKspA07Kw4xCmIVHrnUBmedO7mQyntZQz5OOxo8cczdm5K9dj",
	"i1DqACixk+JYhfrrEeSR4s4YKTmHVu3A4R5N0MDdZBeo9iaqFBKRUU34mlCgV4RlLS99QK2XoWihBlgh",
	"wKnKI/KiqPzJmqiVuCd1rcRmmkx0pq6V2K1KeZCPhO4lO6NQEB/Vkjw1t/x6Hp6Lc0BOqKR9aWn59Xwg",
	"YBIvJRTMl2whgbC+NMsgde7AYtwKpU09/p2hFJcKitZ0IogX39evPaNVQ00GL9jnK/oURAWrAnDCyQXJ",
	"4AR7glHsfn5Ogr0wFs3ksV89cOC34HkYDtn0i212uMU22wPFNju9Ypvt4WKbe3CxTWJVxLGHTiWEPJEI",
	"Fo2SLf1W8flyQZWMXlWlhbT9tmCfv4bLgTUcy+OiVZuzKlV8xkhfnPUCgdlB2PhxayRGPlwPWpg7ENHq",
	"yfTjUVuG0NHBv4nekrjI2SsVQa+mDmqA2tvJaT59b7Xy68rUGEOy5wpA0kD+B6eIALciWFSAhyGiNv/V",
	"XxxhHWyJzdT7g58FImj8TYPj3huliXpiNFWIsnxf7/CCDBlPFf9L6npDZxpBsrcf/vnS3N+Uc6Z7vzNf",
	"+BW7UfDZl5HDTx6LNyAXwB5V1fLpwvCIYSGU4Hg77vZJLzylUZzjhN+Y676Gm77GS74PSIWechFotOQX",
	"3AnRaxm4hjeC47vDNjiGocHrTOhZNXAwNcpdv+9w39qoZc6QjQut6mV7ZBrFHVNz1xV/c00ET7iooWbB",
	"kLhx12qOHXJBHhKg4nPvpX1xxDLnSK05UJQh2aqI8gwMnWNfLw44dxRzor9k5ovstmzbjm3ZL8lVogXw",
	"12g0F6sfOGxGjgCzD2WYlo1Y43EUXOKul8Fw/YVwNQtkBnqKbv6YZwxKGbqPz1n06JAbZhoOHo++FKmx",
	"69XzTog8Qwp3Hj0KcgYzIN6VRq5yHvSRYUemvfR89e6H1NHwUBZi6LTU3n5w3DMLhfZ5drxx46z99mGy",
	"3LoBuUgzdmDVxH770BVVd3AocILoZTodeXK7MbuwOnUnNhbXUW+9fborjaXnaNAWkxRoMVthAuiVNNrx",
	"U6fAQSrNJ0CEsjniagbipXERwooe47pyGPVz2hMl3tNdR9HMNWZCObF21vvi2sv6tWcb/KzYPD2jywDF",
	"fZKSh/yVF7pPujvtsw8bF39khPEfA6AkiH5vsJgAfgi/V84dK5cSQ799x564wIBeQlMlTB6Ia4aDOusE",
	"+uGQyjVqhwMld+P0FCTqm1XLfJqNuniaVc2o0ZHp+uV4FZvShjf5LXQiCoJb7mlYFIiuRMkABNvsUPSl",
	"Ufvcm+0YnzgV0j2bZiJL3c48tIDS2HON3Kk+t6HPHqehTyenoU+CQFOGB8AJ12QEMh1SDpxQgBbRvJ8y",
	"45nMBUcvqpiutwuqo9Oj9YnbOLkD3SH4fHciuKpvGRp7wI/RxKHQ/CDslPKII2RYFNDm+yCoVrr6MMSV",
	"yhnLXPA/Cx2/B1oM4SHR8dNCeClSMhzB+wcmhvU5Cj9GOclRcFFPWqxjrc7Nc+lwaBu1e5cbSseOT3Rf",
	"1o5Wcdcyb1kV003YWqhPjjZOT1nmPcu8ZJlj9dMT9qUXpArCwwOuVcQIZQjWQ6LmsZGTBaO7m+np1ZS3",
	"7LPTiue0+sM7EvgXlRm3H30XUcP2I6nWiZsNBSOdUTHicMYwt5OPvwe3kwxHh3U7x1D11tZ0jhEFoOew",
	"Q+a4pAyWJS0vwP0YGpAMvi4czGBIFvLETJpNESFHLYcWnyrbW5AUxem5FeVCKIZ6ZXakcfUdtgnguh4u",
	"snW1oEKc/b0s5flYId9mFN7pvBG9R2HmC/x6/DJl5aGIZykZrKAn7MuU6d8BdxQboPf6bQnA5LCaQyQr",
	"JYVbzNeqVLHJAGhOEKHT2+kaSn/HzTku22deLS9dQXFoc/bIjysz91OqTFI6E0fUNB8JdElg5+BkyTB6",
	"SAWSZJoz04S7VTVjoImvOGxVqvbF01bNRG39xq3aXLbtq507o2tOWyZ4d9oBe9MO6FtTIeI+AYKE6xSF",
	"9hgshhKV2AogQ13rSlf8MwQYjXYVL665sYtd0JM5Z+rqnu1NVvdMJdcCCjdVsomJLgA79JcWZ7xQn6ws",
	"vz63vDTulI6GrwqytvQcrtngeSb+o/9Aj1OKunp5ZWrWMqOtWnJEhZC0McLuUFqIjLPq+tU3lnndql6p",
	"T0827j5oXJ31Co9MoAfwK6v2wAlAMuQi0A2pSKmLgTdWv/GgfrOa+aLv2z1ff/31N/bSL/biRFBESQZo",
	"g/PQnjjHgaYz4tspyMYNGv0Yh0rVfVQ+zRwSdmzLbsseEjK4nAaheKB/oGocJ1St0EwE80E4zqMUGq6f",
	"+pYBLxo8Ugze2TyJZndNok8FfHI9JhcKjH5qduW8PfLAT1JkO8ROlpgq0MqV041H443fxlZnryQu7th5",
	"skRVObxpvF6Giadk1If0u7skmygcd4xm9RYskqiIx7vOVd0juaGRBBe3JsVaYmwIAhhm5qd2dVjVy8Hq",
	"Mnf9BQZumBOAExtlgxbPR1EJ0Hrnt/fCw396wevk2YqACvxg7AAlWsE0aqZs/dXzxP5Uyos1DoiDbHZ2",
	"CtnL1B75V+Plaat6edV8hCIObuCyeFyjED1PONnmWUai1O2EKE95UVDKhQLObDS0Moj6ub1jSjE1HjMs",
	"CgdKXjU7xr2JXIPOI7IBlEFZAZkOTTrRVZQGgTMNktdP0Bu7YtUe2T+eWa3NelwySttrsXG4w5N3Vg5O",
	"QrRYpppLyFbIPlgX3TFXNbKwGOp+hRtm8DOw1k7jtDR0ln2Kaa/vBlJ+swz27YxcDvvi2MrUGIoGj0nb",
	"wKtvuc0/mJzPNvv74EV3M3xSouXfR4VAF6qLORY1zYVdqcUjAftM0ky5SKN+/LcOcFQqF9Y2E+m7TzwR",
	"w+HvTIdd8akmi3jvic7ayR9NUQMqro6iKAl6eNGsgpF4FmcuYnHhsxBDpxxASQjdfNJzaThRDT8vrZBk",
	"YNu9LILV61cgE6Pku15efl2pn56wzDlcLpZx8wcD2btpnbbhBGBK3hGR74tsMmMoMTWcjQs3+uO4PYKY",
	"bvUyqjz8wI9plN0836YWiLOEE6VxRtOEI40R0WQiibi443aD6ejyihm0F3JcGBLNUok+hhibuGGZl2iB",
	"gMywN+ZrJVVR/rCQh8t0Z+YiJuRlim4NFZCsj51lV0/APZvieu8Qn3r+sB5st4gfBz+MBAgSM5IT8rfr",
	"hb1TyCAQk59S26fUL6GHSMWVL4koBb1NFY3DoXOpSqhgrRM0Vb4Fj4uC4zzgIhbnXsGFzz3CUJGWKMWS",
	"NVrC2Pw+SUNWKEUYPUniL1S4sgu3LActLDGX/MHgDQiv0/sH/lIjpWGi6jJZGSZadMNrepMw+1Irqpo7",
	"il6G5v2UU77Rz71vNo7JT9xnhjCRmfvDRNgQGceQDHR0KAsojhzGtSH1ckHCHp80psXQOAqgykX76eV6",
	"ZWalthQEtA9IRjOA0DgqoPqtSy6gSPUUfNA0vAbON4KJyIpjyJhebIh588Zx0smWDhoOWp0pbhjf6Oy4",
	"GGhFSZDJI1ij0JzFaLSvmE4t6upl129B1W0B1P7cvmbxmjYOnbcqVf81PWNVl7AJwXONpA6tD9VqoWRU",
	"DEpF8EOJSNpMWxKXzPmkCV5a0mf4hD1kUQ+XrOQRIu3Td1ce3oKqPcpSb1w4a5mz9u07q+YH9POco6Ky",
	"I57pPdfa0K8UvWcIFAxWcMequbBydcnVp2743pWsuFPckT1Mi0A4JhcKu1X1GMc4Xp9k9fFBbf+P4+4a",
	"STut+3hvYqiBtE2vlXyibvDh5CxiivBaRH9HVDpwpmSjqqvDnQPXbdmJz9T9dQcKYjKABgf919+ktn8c",
	"hv/Jtn3zw+F/+xPVyuZvn+O9qD3xWpYkJTA6dTVvofcobYf4lfg1ldRS2uWDmHRXvwZUhkp+8pfgG5wX",
	"GcSfT2QhDxrG9cS2adIkrac0ScdYovWIJVonLNF5tiWa6Amb2PgcTW5tos99PJ6Rv6AXfsjoH4omidkV",
	"o4UoY2etaOoe12Z3A/qIrsWt0GpmR5Zyja3DGmeT7zdUTRoEfdIJylt14kLj5Xio+3jkKAuqaiDEUf3k",
	"9sjP9cm7gc4drsOcETcfZbg+BFlJAQGFGSaHgPpTpCvfTd7AaJIQdV3nllbN1zgj2zJ/9JqAO9W8i9JJ",
	"/F5Ivgbnewp8fHoetu8tNl6OE6VMyUvgw6USP1FhLRQFMX8el1JojD5CGX1+mmbrtbqQPS9qH4Nwf8UR",
	"Cqi4BW6FT2h4QmdP5/6/CqLQ3t0N/3ews733QI8gCj0HejqpYTUBSyAXIqY1F1B/V8/e7k4MiT6xTL/A",
	"jpUvcsuOFNTcsV5Jj2WWu+GHOvzSSQdAI7+XwYlkI9GXYcdzkmsQKFUKT7sgJ0hd+BZ/5jps0ss9Hev6",
	"sTKEeBJ4yoKv5sSLH+fbYVE4ISWAd1AyGH4kR9SS+BWJ4yUPLLROf7PuInw00+4tpDGWtHborBXimd64",
	"fmPkcqi4Ma2enVttGQvkF8Ql3d0+MIAu6bddnd3wTdLe81fqZYWH0SHrhttYIuwBXnl4vXFtDFf6+31x",
	"JJQK+vvi6Fr7iJMlKsN7vII5MK4S0lqOe1DSSj3gpDGgyYODQKMqCfUnU6u3LtjPp12jzQ30MHhsVZ/g",
	"50nkzOCsvRo4zpvVHh1PPSvzxV9/9pL63G/bKbbRH/xkRXOalRTTFPPJk6jbetDcLAqAZt5NadQVBTli",
	"tU1jqyXHu8bYNCbY8B32bKyAYmOVw2ZVOd6s6mtHkbIi2GyKr9zyu58sc9xv92vOYB+h07quUl1+f35X",
	"5pCwM5vNDB4SMoeErzLH8A87MsXBQ4IQVMuzbd8c/vMXhw5twz99+X8yXxQH/2fwf44NfknR0YcRHo+i",
	"IkCGbEAyEvrKsqJnOvOyoWqZ9t4ugYgYFrIorHdYFNQSUKSSLOwSvkZ/wi8yRFXbpZK8/fgOeApFScm3",
	"Ifuj4543kjcaxAzfnrhuv4d3AdItTjDOC7sCjd50JDngeeolVdExqK+yWVz8WTHczlylUkHGOcrb/1vH",
	"ugKmjvgMBR8YgoXwFtzFwBDIQIICupEZkvSMXs7lAMiD/DasonghMC1ZUaemqRptGe1KpqyAkyWQM0A+",
	"A+BnGRcv23BfAGlQR64tEoPCYfguV/U0x7M0WR+5yD+YPRqQDOCY5YBu7Fbzp9blVDAq/AttaGUwHKGI",
	"HesIOyE1ZCQln5EyCjgBjwVVvEAfHAFAyeQQuvIZSc9I8J/LBeNjoZ5hkXHtt/8ThZgMY8IqACNNq9HR",
	"c6s3p/kk1oHnhOxHk4rAAJqOHqLw/Y2NRK6q7sW6BMlEJJAWr/kdjhDVv0f3MzAENJCR9YyiZpwDyxhq",
	"RgdKPnNU1TLGkKy75CFmjpSNjDEEMkMo6E/PFKVTmSMgU9bB0XJhW+bjYR/lFNyjfvtl/foz/tF+V8pL",
	"G320fwQ2ld18NvURsp28ppZiVQ1IhPNOtdOkqkaHppY2Rs/wIG0ZJcPHHU/DYJ0KXcPw51xX9cIDs9G6",
	"RQjwJ6ZYBCiGfr0TqRQMmmKoFD7Uz/rEH4NTlFMwCoYy4U+5NTSJlBwpu8kc6WPjMEABxVNxGkT92m+J",
	"FYdOOOHGaA4+qC2jOhDY4+gO4fOgqwzEXOuqM/hwNlppCEP+xLSGILEwLnUSvSFETwx1gQD3WV/4g7CH",
	"cjx3YOgJxFRbQ1FIy4aym82GPjq2Ihug2DaoqeUSz69BxNMQQR5cnaHLAEUUN7LuKoMHactoDD7uuO4M",
	"xqnQNQd/znVVHDwwG603hAB/YmpDgGLo1zuZ/4JOUwztwYf6WXn4Y3CKcgpGwVAi/Cm3hg6RkiNlN5kj",
	"fZQcJjYwgqDApEYHL053QxSIrWVy8HGXVIGINz34c667ArEphocQ4E9QgWC+D9IEQNBpiqNAfLY+/JE4",
	"RTkFo+AoEFvJCJGSI2U3mSN9jBwmmeoQqy5siKawpZSEpPoBRydYf3VgMzSBT1YJoN3OtJKfI+0/C/pN",
	"v+2xfHbl0YvGy2c8PrsXGJt4gtnNu+kfAS+P0+A4WtsWUtg2Q1fbUpREyIAiKqHLC0adQnHRF63aIldH",
	"w7V4111Lw2C2jJ7mYI0bd0ocAF1TcyZZV10Nw9hobY2E+onpaz5lRG9rsthSn24YOpsD4rPWtvl3P5b3",
	"cvU2Z6atork1ces/Cv5ejjljhvbmzLE19Lc0cuQzRSWVCyWpAAyDm1N0CRUXq3klpBispNeZab31OAfO",
	"llHkXLxxNTniDOianDvLuqpyDpCN1uUCYD8xZY6gDsqt3f5POR+jy/mUw9DlXAhplLk8V0SEizB81tto",
	"Vz2W23IVN3eqxJrbWo8su6nX+eNg3uWYE2Woae4kafS0Jo5zk+XBZwJKwd819SjQdbcpGZVVrJiv6g/m",
	"+SqZP826a2UeqK2jmBGHwNbNnGNgaGX+FOurmHlwNlw3C0H+1NSzAI3Qb3ASmxumIpaG5s/12eL2B+EF",
	"ZSYrYAl5f4atYY9Jy3Oym81zPkYewsm/aiwtNEYfxcn/0kZI/tJWkvnc9CoH6UxpX1p3OV/aBAlf+lRl",
	"e4l2I5PIc0wnbHn+OTdq8284h6vyTS9whq3iMUt9uz8Czl1mnitbNyttHa2stAn62NaiIYLjayAnl7ju",
	"sSeooPlVriLWh2dZb1UMg9kyypiDNa5jzMU+XSNzZlhXnQzD2GitjIT6iellPllE72my+CaHaBjqmTP/",
	"ZwVt8289n+VytTRnmq2ipzVx3z8Ktl7mHTBDXXMm2BoKWxrx8ZmckooD3K2nTR8CwOClEfJa5TEYC9GA",
	"bt0VunCzv61wXiT+uHmGjLOha3rkrOuq7gVaIG6szhcB/YkpfiHKYV33ZHmJjCaRdJWQhPxZL/yj8I1y",
	"CrbBUCXISbeGPpGaP2U3nT99fPzGkPmFjQI9/Rh6xIC8AUWMvMaDW+E8EMa4KoOLd7qOgMavq3KAGzBu",
	"rFbgw/zE1AGXHML3Mpn8dxtD0gU+mvuzpN/se85nr1z7D5pkq1h/Ut/xj4CFl3lHy1DX0PCtoaclFxWf",
	"yYjN+odFQQfacZcEgvN1gOOgoKJmpxn8lSAKZa0g7BKGDKO0a/v2gpqTCkOqbuz6S/YvWdS63QHxT5eE",
	"cOWDYdH7g5tGR/zJNUERfwp28iL+gWjPQfyVqKMZ+mv0W7JqN/FnjBPiD9ibGfyDF2hG/Dmg5pKfu6Hp",
	"w4eH/38AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
