// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1rVxRJtuhfqZV3PnSfSbTsPt417Ze7UKqVcxBZQLd37ujplVaFkMeqyprMLB8zh7Uqq7QBBfFtq7RK",
	"i4IiqK09vgB/TJJV8Kn/wl0RkY/IzIjIzKKAFv3SDZgRO2LHjr137Oc/haxSKClFUNQ1Yc8/BS07CAoS",
	"+rH9mJyXdRmgX3JAy6pySZeVorBHWK0tWefvWJVpQRRKqlICqvOdNAAHnYE//kkFx4U9wv/a6UHYaU+/",
	"s93+bEgUcuA4KGogakSH/RkacVoHagwoHe6HQ6KggaIm4fXzR/W5H8JRugqKA/pg5CDnuyFROCnrUhwk",
	"fO98NzQkCir4e1lWQU7Y8zdvAgI+uQESBaKLcg+VR0VBP1MCwh5BOfbfIKvDRbVns2VVyp4JH6Z1eWnl",
	"zXzj4rBZqaZNY8b6cG7lzbxpPDGNm2bF2JX2/iiIwnFFLUi6sEeQi/rXXwmiUJBOy4VyQdizK50WhYJc",
	"xL+l3TXIRR0MAJVcxF6lWNY4K1l9MFmff4DpKy7ANvQrDSacfZ+i6RQ6nhqzLlw3qy/N6luzNrLu7XnE",
	"74dTvz5RH39dr8yYlSqGuXb/R9OYs5ZerN37YBq3zOqFVmy1UFAoWF1cXr3xdHV23lq4Hb6vwRPh3lrf",
	"x0OiIBUKSr80EDnO/gzeXakgDYBY0DqIT4M3hJxGDGyCSv3eQmnIMasfzOpzQRRAEeL3b8I3hYIgCqp8",
	"PA/gzRsE+Tz6V6AOnPkhC3/zoGi6KhfR5trVgqJ2ePzMD2rtp1+tc69NYwH+sDxlnb/DPfJvvvkmkt50",
	"Xcqe2CfpYEBRaWR37X39Sq0xu2CNPCQ2921nX78gCn2HD/V2wP/3ZNp7BVE40N7dsf+7bkEUeju/7coI",
	"orCvvfsQ/H3vocP0/WL4SrlIuVu7IFJri2btpWlUTeOeWT1vGgt4Sdadu/XrzyMontj9Ltru90oawDRC",
	"OdZ77+qTT81axaxNwUVU30ThOhLZe/NK9oTWI2kaFeJa5fbq1JhZvWI9mjWNK2b1gmlcMI3HpvGjacDL",
	"bc94TFHyQCp6M34vg1MUzvToRuP1bbN6Zc1YiDWXopygEMDkU9NYYFx97YScz0fKNfgRmnxIFHRFl/KZ",
	"48cVVY8a1wuknFwcsD8OXl9yItp13afkFXXfoFQsgnx4V73797avjv5q1gyz9sCsjZu1Oasynfoi3fbV",
	"7t1fkgddlov6XwTaae5TCsckvUfJy9kz/ehfQ7gbebR28yez9rNZe2JWX0MqqlTN6iwk6NqPZvWB/V9j",
	"AX9Zv1WFuEbcvX7j7drwz5AYFm43lh+7DN65gRK6OPAPJ6Uc5DDyQFFRAfWS7VMKBamY65eO5SmrhLKr",
	"dhetaRQuCF64G2ZtLnTaoKir9o+yDgqR3JcEmynqKtKh7MVJqiqh34tSIVJxyxR1WT/TDb8MkgEaLrpL",
	"o1NCcBmxUeCc1YhZexJCxykglaJVQXLtonAKyAODeowx6pnD+NPghm2o7lRRO+6SaVoLa8Mrbyqrj2ZC",
	"W81JutTUsdNOHN1cl+OHOGrwooXEti4JvknoGChq5QKd3uv/Gln99b018Wy1tmRWfzGr0wgD99lsTpfU",
	"AaDvV5VyKWrz/cSncK/o1254ZeOMgx8OiUJZgyvvy4Ji5NX4jvg0iCpyGtG3CXJhNPR1+FWsAO0QIrGV",
	"WjZX60HKDlR9f5kj4ZvVK6vvl+pv7rRMAe4AJX2wC5ykSY212xetF9Nm7alZu4UZ5Lp0/Q7yERpQPm7N",
	"Nq7NmsZ1JDCeQfmBRUV1zqzNwYdWyzX/DlnKKxT1dmXx9urjF2ZtGGH8Q+hyFABSZ/4TRD5WD3pfBkmV",
	"mIRKj4qidinZE/2qPDAA1F6Jou7UR0fN2rxZqyF8jSCR+9SsLQqM+biTLJL7DQ9XlRJLmNacVdRutlSY",
	"ujC3UJIG1hB781wxWpDgJZDyEdMhMm+8ul//+ZJ1adysVBuP39VvDFvzN03jmf9LZHWoXqmfnbAuv3Tv",
	"R0grWr8sdpfOlcYu1hiimIG0Vohij1C3SA53lIsDQCnul3TAu7uIpb+E/Lw2Y9Zerhlv6ufvmtVfETJG",
	"om5zJg8KgPZ+tF+KL+7WKzOE6tx9qBs+Tb/t7IX/6z/wXXdHBr5e9x3o7OoSRKHnwKH+Q91UTTpTBIUz",
	"jKtfv/5bS2+8B2sLr3xwEVG75l51ACfrTrhmJMiQVI621bqiewgJvCZGlaTsiYPS6ahBPfZnzgi5GGuE",
	"XGwN4/EQ6c5GbJjAmLc8b2v8Y6YzqcApt4I3EVdpi5gTprIOcqMhG8qTp/WfLtZvDGOkdtmG/K9sjcr5",
	"fReVVbg0THl+BW0A1qVxP4jdsSC4FEJhqfRLaRoLa8PjpvHBrFSt6RnTGDeNs6bx3jQerxlvTOO5WR0z",
	"q2eh2DTOkmplTikfQ6ZMilJbLBeOYS0y8/eyXGI8HFYfnLOqt8zaJFrYebP6tiW+n8+eHIonh0rv8Gz6",
	"8orOPJrqW0cVGTErVWxtXqvNriyNp/6cqs8/sm7Nkt8QMvVApr0DCtNDvX2HBFFo7z3YZ9uD4f+7Mvvh",
	"/77NZPoFUTicae851L3L/ekr96ev3Z/+3f1pN10Qw71Aqc82XeM94eU3udL/yBzOdPX+lb4CVVVUxtV+",
	"jCj8KcLVz0izect6N3FnmELPmfeu+TmwCPojinr230rIh3UQwIvKsFa+Wl678RD5MabN2k3S2o8Hd4Oy",
	"rkp0v8W3skp7uRv3V1//vHbnF6yJRTiQ4vqOmnMbSSFPB3eg/2tvvCOSYgxGnw6JQtZ2HPL35roYXRdX",
	"1BjCezEkCsDTgrli1/4M6VUD0j/kIuiT/xEJ6yD5LaK7vCLl4hryiW+HxE02pwUuiUtsLpb9R+shMkQy",
	"9kmyTWkBlAawRL2WSl6WBgDjQk6PN67do1zItNi2S2z7+ihF/h4AUr69QHenWXfuWsuPrTvvrIXba8MT",
	"63ZnQVi9UAgxQY3+al2CkiS9I21WJnftSNMVCtdQFaFcQIByceB7KV9moAzDXRueQMbckcbCzfqNt9bi",
	"BMHMejK9+zLd/e374eOvfW/foa7v+uGP3d8dzPS2d1G52wFZ71FkO74lIGUql1benrMq02alivkbtjiY",
	"xmzj/ivrwXnb0GzMmcaTKEtdAOtUn2UnJNoeCWsh/rU0rr23ahNm7bpZnUI0M2fWLmPZw1deS5KuAxVO",
	"8V9/k9r+0d72/9Jt3/yw88iRtqN/PnJkh/e3o3/+E82U0lnUynkJc7B8jook69mVemVmtbbUAlOlB+4A",
	"kHQquPrty60Dp+1VNKohfBJJ+F+whLed1VFu1k6tJy+dATTVoXYTKQ3TZm0aifx55Jx8bFafxZ1bBwWa",
	"QuE5OcLC1w74iJKiSAQW5cJ/gjPxTRh9JVXWscE3/MQ7ZvubuSLOdhtnff4cvvfJ/RK9DnyPu2ibA/ka",
	"hELV95zhDve+HBKF47Y6xBuBVKYhUZCLx/NyVtc6mhD6pPE0TA4FkAfRkh191IQxCVHSSTkHNJsvR5pA",
	"Ap8TM3SXdVWOc0ruh7aQg68yl8iSUCMe1TcIgB7HItUX+By9BqXsiTgk2ed+CN+DUHhFjYD3GEk5bC6S",
	"1DhgDjvf+UxMUj5/6Liw529RY7Gd6ajI4R1rw+NQbWBYEclxYfSSx+QggaYQwZ0zooHIpdRHK/UxIyoA",
	"KJY41UHBVUXZAM3qcyROFyGTrlQDfmNr+F1jYhm91NDbORS1sT5LsLvGlhmCRUErH9NtFSoW6D77e8bp",
	"O9PxrcmBjcTHOM+qDFGY3Ki8uYbeeLfQZ/INXcWcDBWuY2X4655U484b69mya8rLKvk8yNr/9Mu7xsXh",
	"3xdH0lCj+X1xNHRoLsoI83E8Q7F7gqy4EvoBtsJg7N3ULbIXh+5CfPo1Fszqb2btBs26Qp4remM6J0l9",
	"isBFROMe4zvKBJUY/VuJeWb0GoHyVrrfXJhb6H0LrCH25n0G/4C08rHVK9ZEtXFuhiGnBiCxO6w1Ngtz",
	"9xviYCQw1pqsS+Ob7fNbvz/OQ1SEP457yDFYaot9cN692sKL/b2jEQeI5cGvq7++Xlmeqt9fjNTyIm1V",
	"XfBQMkW4V4p9wjo3Wn93yTTG6pOj1vm3ke9sNFuvlJOpKSjnRqFKOPJ8zbhmjZ+3ls/+vjjiMP45a/yn",
	"laVxKJTjGyZ2MXfUp5TVLGBtiGFvzyp57LngGm33721HMdToGewhjjfGh2RIDy6GIkfZyAxSkT2DaK/Z",
	"WwmNmA4G7NlB68pds/oUxZi8tBbeRhlAY5zAQfvxzbK32tFKH86tPorxVImE5jzmA7auD5frFx+23r/y",
	"2VsS8JZsW68F9SohPyHtEk0hxeISDsUK0BmZ7ck9PvfDlhsVs0RSRoxAdX8CBx7vBq+3UPOJYdqdMY1n",
	"jUmjcf0h9hggynZjcrnaDP4Kfu/E+2390o9jn3F/DBtD2Dc9JAqya3TnKjD4qyFRyPvFYaTAsT+FSqNy",
	"El2dHscJEmEv9X/urLcJ66nrBuDv0HYXbKGl86QMTnXImi4Vo5H7Pfkt48ljn61IcAy+xZDNolgxtR6b",
	"2oCnsM0dt0hnPugLuKds3AsZQWGzS+jnt8gGMY/5NuEN3BXpDTwK/5Nu++aHo/9Gdf7RLkQ4EuTnu2SO",
	"W2PmvXXhOvJO2hmehEFElYo5pYAMUbqqoOhqKZ8/UB5AIVDI7ychwXZKKuYA1Ap1oKqyrtix2NopSS1Q",
	"jSdB70HY5X7/7Nr0+ZXlqXU7x3s8+2LwiC7bSQrGQn2yYk3PROexRqqiPZ5tkg/t+URLoOWBrgMGtKdu",
	"cFjgiq3TFyfnok2vaF2d6PFRLGWxVpLLoSOX8j2+5cSYKGj58e4g3NnGzQ7JWcKn2cz8fjETmD1oCc6F",
	"XDcOdGeXNipprMi3Ey418C34yU5Wl/PrsbuhLaM5OFvqzPH309kRFa4bjqk4SsRWMHipDZ0l1Tz4rbD+",
	"ONd4i+RYj6Rp9JoaTiK8XVPDOn+/sXATh9igQiLTo9bYDbe6yG74N5SRh8ScM+rPu9PrZ+KqchxoGj00",
	"3HhdfzjfokdQS+IU4j+hvH2hsAUaBcS4k+4k+Fq6kBMugeVYaMKneULO55tZAipREF4DjXFQvd2kHotB",
	"u0dCpfwA+hm0ZY38XJ+8h8OYQ3TWBHbsyO/IKBYUIs7y88J/4++JxjrxhhIzzSjVM0BEXDzikAFuLFQ2",
	"jrnKi1BomQsoy+aR7gbpIgFvsCXCwGN1WyUPAteRsVnE4+fN2hw+VloFsWjehSBgthUrIAd9bzuMaFyB",
	"HdAC1TaKaXhpoTH6OCw8Whtgl1eyJ6CUjTSN+urSOCOdqjLRI9GXLZBiOSXaL+GkbtufE1nhcUYGksjh",
	"JKEM1ch5qDmtQ6IwGGkY9uKI12WxasLWROhafJXQ/s61G/UC9MaORYf2tyg2TlFj2OT78Gc2/k5Jaimj",
	"ZaVS3JM4HBxATNQNTusJpiE+JybpUcHJBJMQn6NJ4gfK2Zgj7yx5C1mMhS4UMHNpkVAobaE4CAaXUnMM",
	"zr+t352khDXHkeVEtgRyV9q5DFFDcNKDIzvimLhDmQuhLD/3X0Rn7c6CaMjxvLOs0lZhjES7Q4iKWVAI",
	"JB0wkHSAmmxA0DcsQJBwnaIg0bEknaKG7fsKfFjnZleWrpqVav+hg12+3AljwYlKGanPXFir3I+K6ySd",
	"R1rL6iW5Th2tNXUfgJt4rbUoWVt2AuO01gTzyU5YitaaSJZkL1PWe7SArP5aC7wEJVfT1Vqkn7v2yHWx",
	"dRVk5VICpPei72kzEc6cpMosGkQVOnISguiXabRAs7b66wxSSgDMr7xDlVZRIIdpPGm8nlh9Ml+/8yZh",
	"Eh3Vlm7jkMKlnqKSgdfCr5tiqawnPaROOGjjghjtNVGZMAGfvUscK9OkGA8E4rRsVzZ09q5Ydlp7Uxvg",
	"emRfuc3QyXoDWb/BfT9xZOsoeV9wQcuoYrUx/E590knQIenSDtd2us/BUJIC4+3xikwEoJ1xE3I64pUb",
	"54yPWbKCOUNf7PIVzBnilrJgTfB9zLoWjAkC5Pe9V+Sizyty0UcUueggily0u+XKOzjlyoOQ90q04oIu",
	"mZjGAi75y6hmGEmOrJLkHgR/5ZMmIBxUcvJxmRaYRW7DqbPyvnH+X/VzFxx3yZxZHTGrF1Y+LLBLNkYv",
	"oR9yCD78xsJNa/idaVw3q2Omca8xsWxNzjYNkBUePP4TZK8u2ErVPT2z9t7dpFl7b10aWZ0dgT9Xr9TH",
	"DNMIcwSHNOKFS1EJixLtfuddfXLUR1YoWsI7wubAuTOEQTplXM5GnPyQKLjn2Nwi8PDwCphnH7zxCGkE",
	"OpwV8W9yoaBwWD63TH37usrUt8erN+JbqV14pKM19eqdGf0TBhsiRKKPV8LeWLAmHljLZ3Ete5Q48t7J",
	"N7BfyzjYb+X9+/rZCVx+0Rq5aVavrM6+sBbesostemvwRad22LoPt+i8/xy7pGOgKcJFgPvPlACegXJ7",
	"pmYb0+8a13D5HVThFRkRigOgaXhoNLb4hOGh0O2dbpEciP+xd9bIj+h+2lalpnfZmaOAxDWcMGahpJj/",
	"yRp5aM1fClGbbYrCmxdtpPOJK7BfVjXG52cbsxfMShXOpO3QtRJUFZ8tWx8mMfWAYrlgGmPIvX8WFf03",
	"XDJ0WOoMoyj6wUxXJgOX3d69P9NBDQGjYyq8WBai4k3pEimbsFGl9xDB8abfq+TO9EiqfgBIeVr5j12m",
	"AcUvrngFicl4aL17jUVB6BrtU4o4sohmITOuEvPMrbz/aeXNRYenP4LHUr2Ap4WfnRu3Rm4KYsw3vrMZ",
	"vAl3FfGe6u7ofVIBqBJHFKBCyVNm7TFj+31ZKR9fg8fg8Bi4DPhDv9LscBzm/38TDu9RNBdTeIa/rmOG",
	"9UBvHm6AyWCMePiEy4LTeyjytno0mhxcOGxqsN7N1GdvUasQhaoNUY+PPTWKr31rVl8gVjUX0HfjgBkE",
	"2RNamRLG0Hegve2r3f/brBlmdcYO56z+hiMY2Oyimf4UTTaYIGG6tmzO7bQBM5oQ4FqY/vvKqqPJm4Ff",
	"LQ/NyKcql7IPSqU4RTxNYww/MNC6XiLELqLuIijy0VhAi63hEhJHitb8T9bkrJMOyxhhfIDCEAVum8as",
	"adw0jUfWpTnTWEaFOi+gmVY+/Awne7a8+mJqTyqYsVExUCQ8LoxuhwNbP57zJZZWDPx2WHkzzw2R8XV0",
	"a+rp4LPaUJQi12xDdKNKCsj3TKC8zMh3wpAo4AveBKCgGKLVT/HLIUo3lqQwqVeMoupF3rFQn4zEK3EG",
	"c9fBaLfhoT9QgTfhKojRXLpyK/l61TDb83n3BZIQ6kFJPQFULpFdflm/8dYuqgmPYBHRwiJZLTMhUDiM",
	"B5JebnNIFParco6okp4QLDGaT+rPkQW4ZtZGV96cN42FlaXxxtICKqDX0wTcAz08cI1r96zLkFc4lQH1",
	"wT5d0svNcCZyOBfBtkp8DbFiv4KN6tIFK3klXId/Ai6yiSYodghEOCc8IXRiNJewydxyCFTJIiMtih0t",
	"4SzxpJADU3AvMpZTiLSo7bTsKhPVK1BMVivkEjuLe6XsiRLUa5pfpDcJ/4BoIte5E2alWh+t1CdHVyvn",
	"Yu3Azf5OyqfgOC46w/njbnJde6kEJNXJ+ksM2T8F917dPm9dnYI3avrG6qML9do56/4LlLCVKI/VhQ2H",
	"8VkVrf76kCh4pRlbLg+CWllAJFDCnRIuITAD9wqToVMEcF8ZvibBu3NwlQKUZ7f6YLLx2yNvGZ4vPCFs",
	"PJCPfdsn69F4n5stkBAaHsinLztG2S0JhwAGAiqTgiWGRwGHtPYY0dpIfWKice09se2/l6Wcl9+fdBHe",
	"6BgXmvqoqVSRmrCIRNiiabxBL+cYPBDB9lL7m1k5Hh2LFa0OP7GWL9jtfcknMvKeEqUfW88p7FqySGhg",
	"vTnALKCmou0blIoDTYnbeEvAr4XqB7P61poerd95ZdauI6p6jkxQZbW4V9Kagu+O5S/hF2TneI17AsEj",
	"gPSM38Wza5V71rtHyBHt+AcTLgKN4zJJsgDRkCgclvJ50Iz+jAdy2SHKTVkbvozgEPU+k0Kyh3IJHHV1",
	"8PgBLmm1TypJWdudnxgoOUGcbbplRHm2l/DbMnYnR4YHEJsS44TrepTqDkHvxCFR+K41vRm/8/VmJFbG",
	"t0iVVRUUaR3YPQqixdhwkxy9lzR6dbBS48kXByvwLSYc2oud23rHf44d8dNMXJiUfJPAiZD/xj2EJG2D",
	"OD5Ur39dAu8phr0fFIEqsUzdQUm68ubGyvsHjetPrInXwc7GSY4Nw+4s5sDpWMZQm1sPOwbrt+sHnqCb",
	"0sZg3vmVFY9Cbe4cXgctctwm3eYsgoSdmiZJo63RjoX5GfVj6+4FiFJjxqwYKMbnmXX3gmMGmWtcf273",
	"NsBVsY/lwQ9yM3pBHxrb2RHrxQZfiwuj1sJt+H3gLnuLEEnU8q+1W8CdfsAxulc1GVjoBpk0HRjoztB0",
	"YKA3Q5OBge4EzQYG0qNemgsMjD7oAijqfXlF7y7TC52FG2KFGWhSFnYSwtQlauEUyCxvuTeT4bSWsrp8",
	"MnL0mK0523flRmQ1Sw2AYuSkOFah/mYEeaS4M4Zq16FV23C4R+M3cDfZTqq9iXKHRGRUE74mFOgVYlkr",
	"Sx9QD2coWqgBVghwojqLvCgqb7Imii7uS1x0sZluFZnERRe7FCkHcqHQvXhnFAjio1qSp+ZW3szDc7EP",
	"yA6VtC4vrbyZ9wVM4qUEgvniLcQX1pdkGaTO7VuMU+q0qce/PZTiUkHRmnYE8eJy/fpzWlnVePD8DcPC",
	"T0FU+coHJ5hcEA+Ov7kYxe7n5SRYC2PhTB7r9UMbfgueh8GQTa9qZ4dTtbPdV7Uz41btbA9W7dyHq3YS",
	"qyKOPXAqAeSJRLBomGzpt4rPl/OKpPcoCi2k7bcF68J1XFesYVseF83anFmp4jNG+uKsGwjMDsLGj1s9",
	"NvLhetDCnIGIVk8nH4/6OwSODv5NdJfERc5+qQB6VGVABdQmUXYX6/trlV9Xp8YYkj2bB5IKcj/Y1Qi4",
	"pcXCAjwI8RkyVv5iC2t/b22m3u//zBdB420anHTfKE0UJqOpQpTle3qHG2TIeKp4X1LXGzjTEJLd/fDP",
	"l+b+ppwz3fud+sIr/Y2Cz74MHX78WLx+OQ/2KYqaSxaGRwwLoATH23G3T3rhKR3nbCf85lz3ddz0dV7y",
	"A0DKd5cLQKUlv+CWim7vwXW8EWzfHbbBMQwNbotD16qBg6lR7voDm/vWRk1jhuyAaFavWCPTKO6Ymrte",
	"9DbXRPCEgxpqFgyJG2etxtgRB+QRASo+919Zl0ZMY47Umn1FGeKtiijPwNA5DvTggHNbMScaVaa+SO9I",
	"t+3akf6SXCVaAH+NenOx+r7DZuQIMBtaBmlZjzQeh8HFbp/pD9dfCFazQGagZ+jmj7nGoISh+/icRZcO",
	"uWGmweDx8EuRGrtevWCHyDOkcOb4cZDVmQHxjjRylHO/jww7Mq2lF2v3PiSOhoeyEEOnpfb2gZOuWSiw",
	"z+Hxxs1h692jeLl1/XKBZuzAqon17pEjqu7iUOAY0ct0OnLldmN2YW3qbmQsrq3euvt0VhpJz+GgLSYp",
	"0GK2ggTQI6m046dOgYNUmk+ACGRzRBUfxEvjIoQVPcZ15TDq57THSrynu47CmWvMhHJi7az3xfVX9evP",
	"N/lZsXV6RqcOCgekYg7yV17oPunutIYfNS79yAjjPwFASRC9JmMRAfwQfo+cPVEuxYZ+5641cZEBvYSm",
	"ipk8ENVVB7Xo8TXWIZVr1FcHSu7G2SlI1LeqpvEsHXbxNKuaUaMjkzXecSs2JQ1v8nrxhBQEp9zTkCgQ",
	"7Y3iAfD366HoS6PW+bc7MT5xKqRzNs1EljotfmgBpZHnGrpTvU5noH12Z6AMpzNQjEBThgfADtdkBDId",
	"KR46VQRqSPN+xoxnMhZsvahiON4uqI5Oj9Yn7uDkDnSH4PPdjuCqvmNo7D4/RhOHQvODsFPKQ46QIVFA",
	"m++FoFrp6sMQVyvnTGPB+yxw/C5oMYCHWMdPC+GlSMlgBO8fmBg25ii8GOU4R8FFPWmxjrQ6N8+lg6Ft",
	"1DZgTigdOz7ReVnbWsU907htVgwnYWuhPjnaODtlGvdN47JpjNXPTliXX5IqCA8PuFYRI5TBXw+JmsdG",
	"TuaP7m6mOVhT3rLPTiue0+oP70jgX1Rm3H74XUQN2w+lWsfuWuSPdEZVjYMZw9yWQN4enJY0HB3WaUFD",
	"1Vtb04JGFICWxQ6Zk1JxoCypOQHuR1eBpPN1YX8GQ7yQJ2bSbIIIOWo5tOhU2Z68VCzazbvCXAjFUK/O",
	"jjSuvcc2AVzXw0G2puQViLO/l6UcHyvk24zCO+03ovsoTH2BX49fJqw8FPIsxYPl94R9mTD92+eOYgN0",
	"X78tARgfVnOIZKWkcIv5mpUqNhkA1Q4itJtEXUfp77jLxxXr3OuVpasoDm3OGvlxdeZBQpVJSmbiCJvm",
	"Q4EuMewcnCwZRjMqX5JMc2aaYNurZgw00RWHzUrVunTWrBmoP+C4WZtLt321e3d4zUnLBO9NOmB/0gG9",
	"6ypE3CtAkHCdotAegcVAohJbAWSoa53Jin8GAKPRjuLFNTd2sgt6MudMXN2zvcnqnonkmk/hpko2MdYF",
	"YIf+0uKMF+qTlZU351eWxu3S0fBVQdaWnsM1G1zPxH/0Heq2S1FXr6xOzZpGuOdLlqgQkjRG2BlKC5Gx",
	"V12/9tY0bpjVq/Xpyca9h41rs27hkQn0AH5t1h7aAUi6XACaLhUodTHwxuo3H9ZvVVNf9H677+uvv/7G",
	"WvrFWpzwiyhJB21wHtoT5yRQNUZ8OwXZuNOjF+NQqTqPymepI8KuHekd6SNCCpfTIBQP9A9UjeOUouab",
	"iWA+DMe5lELD9TPPMuBGg4eKwdubJ9HsrEn0qIBPrifkfJ7RmM2qXLBGHnpJimyH2OkSUwVavXq28Xi8",
	"8dvY2uzV2MUdM6dLVJXDncZtihh7SkZ9SK9NTLyJgnHHaFZ3wSKJimi8a1zVPZQbGkpwcWpSrCfGhiCA",
	"IWZ+ameHWb3iry5zz1ug74bZATiRUTZo8XwUlQCtCX97Dzz8ZxfdlqCtCKjAD8YOUKIVTKNmytZfv4jt",
	"T6W8WKOA2MhmZ6eQTVGtkX81Xp01q1fWjMco4uAmLovHNQrR84TjbZ5lJErcl4jylBeFYjmfx5mNuloG",
	"YT+3e0wJpsZjhkThUMmtZse4N6FrkDkm66A4IBdBqkOVTnUWpAFgT4Pk9VP0xq6YtcfWj+fWarMulwzT",
	"9npsHM7w+C2a/ZMQvZqp5hKyp7IH1kF3xFUNLSyCul/jhhn8DKz10zgtDZ1ln2La67uAlNsqg307I5fD",
	"ujS2OjWGosEj0jbw6ltu8/cn57PN/h540dkMn5Ro+fdhIdCJ6mKOhU1zQVdq4ZjPPhM3Uy7U8R//rQMc",
	"l8r59c1E+u5jT8Rw+NvTYVd8oslC3nuiRXf8R1PYgIqroxSLMZqB0ayCoXgWey5iccGzEAOn7ENJAN18",
	"0nNoOFYNPzetkGRgO90sgrUbVyETo+S7Xll5U6mfnTCNOVwulnHzB3zZu0mdtsEEYEreEZHvi2wyYygx",
	"NZiNCzf647g1gphu9QqqPPzQi2mUnTzfphaIs4RjpXGG04RDHRbRZCKJuKjjdoLp6PKKGbQXcFzoEs1S",
	"iT6GGJu4aRqXaYGAzLA35mslUVH+oJCHy3Rm5iIm4GUKbw0VkKyPDbOrJ+CeTVG9d4hPXX9YN7ZbRI+D",
	"H4YCBIkZyQn523XD3ilk4IvJT6jtU+qX0EOkosqXhJSCnqaKxuHQuUQlVLDWCZoq34LHhcFxHnAhi3OP",
	"4MDnHmGgSEuYYskaLUFsfh+nsyuUIoyeJNEXKljZhVuWgxaWmI3/YHAHBNfp/gN/qaHSMGF1mawMEy66",
	"4Ta9iZl9qRYU1RlFL0OzPGWXb/Ry75uNY/IS95khTGTm/hARNkTGMcQDHR7KAoojh3FtSK2cl7DHJ4lp",
	"MTCOAqhyyXp2pV6ZWa0t+QEdAJLeDCA0jgqofvuyAyhUPQUfNA2vvvMNYSK04ggyphcbYt68cZx0sq2D",
	"hv1WZ4obxjM62y4GWlESZPLw1yg0ZjEarauGXYu6esXxW1B1WwC1P6evWbSmjUPnzUrVe03PmNUlbEJw",
	"XSOJQ+sDtVooGRUDUgH8UCKSNpOWxCVzPmmCl5b0GTxhF1nUwyUreQRI++y91Ue3oWqPstQbF4dNY9a6",
	"c3fN+IB+nrNVVHbEM73nWhv6laL3DIK8zgruWDMWVq8tOfrUTc+7khZ3i7vSR2kRCCfkfH6vopzgGMfr",
	"k6w+PgXpNG7EnqBlu4f3JobqSNt0e9LHaisfTM4ipgiuRfR2RKUDe0o2qjo7nDlw3Zbd+EydX3ehICYd",
	"qHDQf/1NavvHUfifdNs3Pxz9tz9RrWze9jnei9pTt2VJXAKjU1fzFnqX0naJX4lfU0ktoV3ej0ln9etA",
	"ZaDkJ38JnsF5kUH8uVgWcr9hXIttmyZN0lpCk3SEJVoLWaI1whKdY1uiiZ6wsY3P4eTWJhrmR+MZ+Qt6",
	"4IeM/qFokohdMVqIMnbWiqbuUW12N6GP6HrcCq1mdmQp18g6rFE2+T5dUaUB0CudorxVJy42Xo0Huo+H",
	"jjKvKDpCHNVPbo38XJ+85+vc4TjMGXHzYYbrQZCLCSCgMMP4EFB/imTlu8kbGE4Soq7r/NKa8QZnZJvG",
	"j24TcLuad0E6jd8L8ddgf0+Bj0/Pxfb9xcarcaKUKXkJPLhU4icqrAWiIOYv4FIKjdHHKKPPS9NsvVYX",
	"sOeF7WMQ7q84QgEVt8Ct8AkNT8h0Zw7+VRCF9q4u+L/DmfaeQ92CKHQf6s5Qw2p8lkAuRExrDqC+zu79",
	"XRkMiT6xTL/AtpUvdMuO5ZXsiR5Ji2SWe+GHGvzSTgdAI7+Xwal4I9GXQcdznGvgK1UKTzsvx0hd+BZ/",
	"5jhskss9Dev6kTKEeBK4yoKn5kSLH/vbIVE4JcWAd1jSGX4kW9SS+BWJ4yUPLLBOb7POIjw00+4tpDGW",
	"tLbprBXimd64fnPkcqC4Ma2enVNtGQvkl8Ql3dve348u6bedmS74Jmnv/iv1ssLD6JA13WksEfQArz66",
	"0bg+hiv9/b44EkgF/X1xdL19xMkSlcE9XsUcGFcJaS3HPSyppYyWlUqgX5UHBoBKVRNWz76wht85Npub",
	"6F3wxKw+xa+T0JHBSbvBaZ03Zf3p1Nrti9aL6USz9qjgJG9Wa3Q88axMM0L9+SuqDaFtt9hGtyKQZdJp",
	"pldMqMx3VKwW7n4btigAms04oaVYFOSQKTiJAZgc71h4k9h1g4zBNdwCiuFWDtpq5WhbradyhWqVYFss",
	"vscr738yjXGvh7Axgx2Pdj+8SnVl+cKe1BFhdzqdGjgipI4IX6VO4B92pQoDRwTBr+un2745+ucvjhzZ",
	"gX/68v+kvigM/M/A/5wY+JKi+A8hPB5HlYV0WYdkJPSW5aKWyuRkXVFT7T2dAhGGLKRRrPCQKCglUJRK",
	"srBH+Br9CT/zEFXtlEryzpO74CkUpGKuDRk1bZ+/Hr97IZYi1sQNaxneBUi3OGs5J+zxdY/TkDiC56mV",
	"lKKGQX2VTuOK0kXdafdVKuVlnPi88781rIBg6ohOe/CAIVgIb/5d9A+CFCQooOmpQUlLaeVsFoAcyO3A",
	"eo8bV9OSFWVUVVFpy2gvpspFcLoEsjrIpQD8LOXgZQduNiANaMhfRmJQOAof+4qW5HiWJusjl/gHs08F",
	"kg5sWx/Q9L1K7syGnApGhXehdbUMhkIUsWsDYcekhpRUzKWkVBGcgseCymigD44BUExlEbpyKUlLSfCf",
	"y3n9Y6GeIZFx7Xf+E8WtDGHCygM9Sf/S0fNrt6b5JNaB54TsR5UKQAeqhl638FGPLU+O/u8G0PjJRCSQ",
	"Fq1OHg0R1b+H99M/CFSQkrVUUUnZB5bSlZQGirnUcUVN6YOy5pCHmDpW1lP6IEgNokhCLVWQzqSOgVRZ",
	"A8fL+R2pj4d9lBNwj/qdV/Ubz/lH+10pJ2320f4R2FR669nUR8h2cqpSilQ1IBHO2yVU46oaHapS2hw9",
	"w4W0bZQMD3c8DYN1KnQNw5tzQ9ULF8xm6xYBwJ+YYuGjGPr1jqVSMGiKoVJ4UD/rE38MTlFOwCgYyoQ3",
	"5fbQJBJypPQWc6SPjcOAIiicidIg6td/i604ZOCEm6M5eKC2jepAYI+jOwTPg64yEHNtqM7gwdlspSEI",
	"+RPTGvzEwrjUcfSGAD0x1AUC3Gd94Q/CHsrR3IGhJxBTbQ9FISkbSm81G/ro2Iqsg0LbgKqUSzy/BhGk",
	"Q0SOcHWGTh0UUDDKhqsMLqRtozF4uOO6MxinQtccvDk3VHFwwWy23hAA/ImpDT6KoV/veP4LOk0xtAcP",
	"6mfl4Y/BKcoJGAVDifCm3B46REKOlN5ijvRRcpjIwAiCAuMaHdzg301RILaXycHDXVwFItr04M254QrE",
	"lhgeAoA/QQWC+T5IEgBBpymOAvHZ+vBH4hTlBIyCo0BsJyNEQo6U3mKO9DFymHiqQ6S6sCmawrZSEuLq",
	"BxydYOPVga3QBD5ZJYB2O5NKfo60/yzot/y2R/LZ1ccvG6+e8/jsfqBv4Qmmt+6mfwS8PEqD42ht20hh",
	"2wpdbVtREiEDCqguLy8YdQrFRV8ya4tcHQ0X+N1wLQ2D2TZ6mo01btwpcQB0Tc2eZEN1NQxjs7U1Euon",
	"pq95lBG+rfFiSz26YehsNojPWtvW3/1I3svV2+yZtovm1sSt/yj4eznijBnamz3H9tDfksiRzxQVVy6U",
	"pDzQdW5O0WVUsazm1qVisJIee6aN1uNsONtGkXPwxtXkiDOga3LOLBuqytlANluX84H9xJQ5gjoot3bn",
	"P+VchC7nUQ5Dl3MgJFHmclwRESzC8Flvo131SG7LVdycqWJrbus9svSWXuePg3mXI06UoaY5kyTR05o4",
	"zi2WB58JKAF/V5XjQNOcTmdUVrFqvK4/nOerZN40G66VuaC2j2JGHAJbN7OPgaGVeVNsrGLmwtl03SwA",
	"+VNTz3w0Qr/BcWxumIpYGpo312eL2x+EF5SZrIAl5L0Ztoc9JinPSW81z/kYeQgn/6qxtNAYfRwl/0ub",
	"IflL20nmc9OrbKQzpX1pw+V8aQskfOlTle0l2o2MI88xnbDl+efcqK2/4Ryuyje9wBm2i8cs8e3+CDh3",
	"mXmubN2stH20stIW6GPbi4YIjq+CrFziuseeoirp17iKWC+eZaNVMQxm2yhjNta4jjEH+3SNzJ5hQ3Uy",
	"DGOztTIS6ieml3lkEb6n8eKbbKJhqGf2/J8VtK2/9XyWy9XS7Gm2i57WxH3/KNh6mXfADHXNnmB7KGxJ",
	"xMdncoorDnALoDZtEACdl0bI67/HYCxEV7sNV+iCHQS3w3mR+OPmGTLOhq7pkbNuqLrn66u4uTpfCPQn",
	"pvgFKId13ePlJTI6T9JVQhLyZ73wj8I3ygnYBkOVICfdHvpEYv6U3nL+9PHxG13mFzbyNQpk6BH98iYU",
	"MXK7GW6H80AY46oMDt7pOgIav6HKAe7quLlagQfzE1MHHHII3st48t/pNkkX+Gjuz5J+q+85n71y7T9o",
	"ku1i/Ul8xz8CFl7mHS1DXUPDt4eeFl9UfCYjNusfEgUNqCcdEvDP1wFOgryCmp2m8FeCKJTVvLBHGNT1",
	"0p6dO/NKVsoPKpq+5y/pv6RRP3gbxD8dEsKVD4ZE9w9OGh3xJ8cERfzJ38mL+AeiPQfxV6KOZuCv4W/J",
	"qt3EnzFOiD9gb6b/D26gGfFnn5pLfu6Epg8dHfr/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
