// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1rUxTZluhfqcg7H86ZLlvoM0ZMG3FjAoVW7kFlgG7jTLe3I6lKIKerMmuysrQ9PURUZskbBLHFFz5Q",
	"FBQtQO0GQfDD/SeTZBX1af7CjbV3PnZm7nzxHGwjOtqiaj/XWnvttdfzFyYlZnOiwAlynjn5C5NP9XBZ",
	"Fn1s6OQzvMxz6I80l09JfE7mRYE5yWyXNvTh+3pxlkkyOUnMcZLZju2GTlfh4z9IXBdzkvlfx+0ZjhvD",
	"H28wmvUmmTTXxQl5LqxHo9EM9fhZ5qQIszRaDXuTTJ4T8ixef3Cvdqsh9JIlTuiWe0I7me16k8xlXmaj",
	"AOE7s11vb5KRuP8o8BKXZk5+bw9AzE9ugARB0gK5DcpLSUa+muOYk4zY+e9cSoZFNaRSBYlNXfUiU7+x",
	"sbX6unp9QCuqdZoyp3/s21p9rSkvNeW2VlTq6+wvmSSTZX/ms4Usc7K+ri7JZHkB/1VnTckLMtfNSeSc",
	"p0ShkA+YePvpdOX1U0xOPuMfq6/zmQIGOy3mZQqVzozqI7c09a2mvtdKg3EXb1Oyc9jKrfHK2EqlOKcV",
	"VTxF7XG/pizoG8u1Rx815a6mjuxgI9msSAHRh83tqVfb86/18j3vWXODN/DEORr3Jhk2mxU72O7QfkYz",
	"OHdslu3mIs3WSDR1Uzc5TNK1CSrl2gulAUdTP2rqEpNkOAHg+z3zdTbLJBmJ78pwcGp6uEwG/cpJ3Vd/",
	"TMFf9ix5WeIFtLkGKStKjTYvck5Vu/NG71vRlDJ82JzRh++TGP76669DqUmW2dRPp1mZ6xYlGlH9ul6Z",
	"LFXny/rgM2Iv3zS3dzBJpv3ihbZG+Le1qaGNSTJnG843nvn2PJNk2pq/aWlikszphvMX4O9TFy7St4fn",
	"FwsC5aDUAwxLH7TSW01RNeWRpg5rShkvSb//sHJryUnPxGbraZs9xWZYIcV9iW+Qq+0pUeICLhGtqGql",
	"21rplabOaqVZWIlSRme2Hz4Dft8zgfNE421w9GIyAXOGU6wsZ7hznCzxKQryXj/X787/v9uVW78B3Aaf",
	"127f0dQVrfRIKz2DfcEuVrTSnFZ6W/1tovJw2nOW07nQM2WupbG1HZbGCVz2atQ+p8VsJyuzgnyezaI7",
	"lM+3sUI3l446AG79TQZzglyGvcpJO578CsfmRCFq94uoNe7rYiXGOqwRTagkETyJXdL4Cn15XuQidOo3",
	"Z/SJMQqlqtcw1hMSeyXBpxOaOlkZHdCUuwzlFJIo9J7C6tyk4/xdn9fL97RSUSvNoJlWmSTTJUpZVmZO",
	"Mmmx0IkYHIWAhUK200m/mB975yRHrw2MM1HPQyPHyj2IGiiHYX1rbQZkB+WRpoxoygtN6deUERsenaKY",
	"4VjBOV5O7qGMtbKsrz3Xiqo+vbS1Oqypk/WaMo+v2Nq96/rybIwV5+SedpmlsT9jGqVc/W15e36wUurT",
	"Hy97j6i5xkiHFDXuTTJZLs2zgg3/SJ1xa6v32daoPc+2kr1OcV2ixJ3l2MyO+nNsBug2alejud2/IHRH",
	"ZxJGa6v3X/lMpqMgCZHZot3BGgNzjp3CPnciLtxzJ3YO89yJncIrd2J3sMqd2CWcvo4PqK93A6mvdw6q",
	"r3cLq693Cax8IZ3mBMQ+21iZi379yt7bDzMkgkkYNGuihMoIPFTqxYZ3ldQD5aEcL3i8h9lJri6MuDgH",
	"cShIrLt4qptdBV31TSAddLCdGc7nrr/1myF0lqa00oI+MRZ0i9ujtRUEmlStzMI17hwTHoqLm/gKiysj",
	"7oxqkphQ8r7Xq/IrulSN249JMrzMZfOxbjp0sfZasGIliUVKlyz7c+Nurs0d9RUM3Ebp5KII2ILEs5lG",
	"VmYpL5YXz7dnRm14/fpIKw3gJ0pcqHXALG1cvpChwg0tIt5g+G3n5hEIFgQerKGdIE4SxGXRCwmLwFP1",
	"c45LyVza53VZmX6kb/bpxRH8jtyhBPsNm0KPyeY0ZYapje351/jxnODTQWfWHKZFFKmSIDESCPUZUZQT",
	"+mC/vlryHMcuY6ioWCJ2AEgSxSzlSNZK8/ryiL7xXh96YxEaWkZcCmsTxSza5X6SlwUDgq7wzoII5myr",
	"d+NnWxNYFVCZLuqzc/BZvYY5Evo8uT2DBP+iuj0/WC3fhi+Vxe03jzVlAXSV8GTqB56qlDVlrnptRh/8",
	"vfruGvrV0Mj5Pw4IUdelP7j/UN98EedlZIsmzpGqL9a2+97ra88DF9Isc1n61aSpT9Cjs18rPcYvUUSb",
	"5NdxX6Ew2XdsphAym6aU9advtt+sbG3OGDraSJBwSFquAztZqj5+pykL288V8yo0NFCGsinSDEDesAmf",
	"Z50bNghg1iXnPMycm4exmcyFLubk9xGvEUf33ktJD2N5+sjxtid5Yswry6KRXrSJzvirxXJB8CLr9eLI",
	"1vqzrdVhfWBNU0eqT9aq1weQecMkmXiT2tTmndlBXz5XGNpq0oUoczVB3KYVKYmahS6Rpv8I0Tv66AIi",
	"mrmoitDoNi//7hENYH4D9OTiPbnikKdH2xfZ8Oa32qg2OHp/OjX15PbSuEbRknpvduXx9sqD2v0nWFsc",
	"WTVmCvyuEzP0Rp8YBK32l3XH6r+sowtWlqY7opDVxuVEicJKO43f/z0vCgnEvopbq8NbG2OVuZFa8TGo",
	"RQOfMnrf/NbGTesS9xynTkK9no+oXwe15aBWeqmpi9g+EEs6cij0KRISZ70L8qHPREtOC33PxVqi83lJ",
	"e1yJ6R3wYYzjc2KaxojRwh+gnQ3CCwfboxwa/3izEcyXNlsI99WKavXXR5XBCaROfqkp17TSE7S6IU2Z",
	"05TF6rSiKeOmPE0X6p0yPSlS25J9LMQ43hAUvNjmjXiwwqoTH1iZXKOMb6TIkHGxP0QzTvJOuo4fActA",
	"XmfT0clfIpFRgCja5ou9eueLKPhJZqExSJrdlbbDIXJScC+JmZ2cSVHMtkFPL97J7XuwiWYzdxCILHOC",
	"wAdnyNuZeAf6qEZsY3Ek+R0NGGSYMRUuZdtEs6fGmbhyUE9up0rrnh1qrPfMVGoqi5Hg49gHYT01VhlE",
	"SQhnzUKa+9lfP1ZGp+0tUo6V8P0Mkoo+N6Ipm5o6HI9ADC1ZAHX46ktNtWd81VygVjPNRzec25ZSsLqb",
	"cIu8DgxphEs21cOld6IRdVECXoRrRGNTlu4viASIe8pHVPM/pyzhqhFJljfbW/5H8W0ucV4vASfIeDmk",
	"TbODtZVwWPlYGxCssDIHf96ZNifP+Zn39UdrlelXLhcC0m0p1G/pFJdO0zVjiw/0vhXsmQbCyPRjpHyb",
	"15QxOJEPZqrTj/Xh9+B6o05Wltc0VcFaOCc9/EchkquksYx/LdAdJs1RqJhwdvXZiHvNRRX5PY4CBNem",
	"QKQqKrWFOyBnKeua8qL66LWmjFdWljVlHO19FO8uBJoZMfVTvpXN56noqhXvAUNTJ/Xn85oyiQAa9kpE",
	"I37Hc1co7Pj5VHXlnqZO1pRypLFE8Sea+v6VppR9XBDzP/GZ0JuwHRqhwYGXijKbaerqMt6ZQf3aOBYw",
	"ZzR245wciIb302JGlE73sILAZby7ajtzqmF76I1WUrTSU600Bta+4mziT3XHvjpx4s/ka7rAC/I/U5W2",
	"WNPRKmb41NUO9CvddwiJwi/Ra/ADeirPo8uxX1OfGv83H7WVuyrAGjmVVqbe1wYeADGU71U3X1habNM1",
	"kEUeffDFZRbJ9Hy3IEoc1fvvtJjNskIaCfw08fitVnqI1jREvms92OYEWXJL2kEIJKdtEmTpKu0y5UOv",
	"0iZBBrNJY1RejttTeTgScA1Gbu6GTjzulUeGmole0E14IBhNnCM3fIXju3vkCD2kqxdxU/eeLenOGCps",
	"vy18Xo6+3a3V4vbzOa/sZRhQY9MJ1VwlysTDw30QPe7FMss4+tA3LKR52BocXJ/r+c16Fc7jHFxp6sjW",
	"6tj2y4/4NVubedjcqBXV2sv5yvAdTb2mDw5o6rCurqC3+Au4ux0zJCzDSYuhyqynHlMhX8jSD2nl98Ht",
	"N+v6+OJ2acMlJvjwZpmVujn5jCQWQl85HURTgDf683whG60fNOxNMoU8rLw9xQmhJ/Rboqkbf+QwSccm",
	"yIX54FTmBHvHLgAOb9SUVX3sztYGSCiVB4/81QcRqRZN1y4XurpoVJvjU5TrFL79ESlRLWGppqxqyu/Y",
	"GKQVVdQCZPPE8QT6LApcAit1tjY+auq4oe/Bhs5ppXrrmT6+SF5ZvCD/5SvqlZWXr2ZCsYMA2I5aupGD",
	"+wdpHEyosDKXyfA01TUrpHpEKVG9v4ocYYCDVFcmNWWhulHWlPHtmfuVO4+QIXiNdJapzPbpryeM81VU",
	"Kw8ewfahyzVNeV659VRfLW2tjVRu9YHEc+eNpkx4EPwTL6TDI3kKXV1/hYa9SUbs6spzcmya+I6jKpVR",
	"x6is3wV5tHQ8hL2sIAQgsvRKu/1920/7kNZ1RSv9CqqVWt9YdaNcGR2ozq5532vZeAbRRj5F02Jh1Bok",
	"rpThRaLOaur77Zn57fk7sOzYqMll2BSX5YTQu7HVahgXBUkmb5JxfLZg9qRriHd7qTvIwUBSADUAQXpd",
	"EtAJ1NfmKvPIrwIfPKWcME4oPBjUIaTOeamVbmnqOqhzQKO7AIxI6YdObx5jT4yt1eHj+srzytR7feKG",
	"h4yQ0iMCf7oaqZ0LFqDMoL/9Thc6uXNiukCXel8jSw2WY55o6qr554L1qt1+2ld9UDQ8FJR5fflWbWqk",
	"NnBdn/odBIHFa/r9N5o6WV19Xpl/ubVa1DdHgGWtlfDrzQMGCeyDkQKo2uyW7u0Sg9D23OiM0vL3999F",
	"1F0jLEFq4S7Tnlb62HLt7hr226/+NlpTrlduP0PnHsgJVAHKJgZOnEicwNAsFJEF+HqyQO4QDI7rG5XV",
	"+zsNymvkchnxKl0gw7RhkYqDnJQyJpXqi7Xa1E1NWXUREjpNTzGxYYsNjKPehZ/AnvNcL41pyrhTzpsD",
	"3wzofhOa+dtSbY1NBI0K7DIDHKZdLEipUNGghWiKxAlRiqCSa8fN2tgriJi9JEv6M7iI6e589dd5TbmF",
	"QLwI72j8ZFYXtNICaGp2G3jZyLMZkaLg2vpwb/vFMung6YRzlkNanL9yocqrc3ZLjznO/ol6lvmUT9AO",
	"cXsCtaGLtTI6gGlRv7+ml+8htzk1UZ+uR9KmOohUPwuV+6tAWkU1JQp5Of9lKyvlOZgIyZilG2i77y1o",
	"cj+z2RzQP1Of/ssX9QAGVpY5CRbyf7+vP/b1pe/rjn196R/TxOc/ff/FMfzxiz//yz/QlJaNfJ7N57ls",
	"Z4aG88H+7bmnhtqjqALBg3ptsjKqaMpsAtCgldbhMk5oyiJcYR+n9ZVnSIs3hztbrzbv8WDzXENouAKx",
	"vlO4Q2+S6TR5aiQ5gBzCjLn1PmzFDBkTGvjWItvCVclzmfSOlvM36Oldjke/RsyXNOFmzUsnVzfUfHAL",
	"JPtorTp7XV95hh89WNtamb9bWZsiw1EXQEjZuOk93C7ldT39aLtQ4L8crTSNphzW1PfVX5+Cz1tRzfIC",
	"0l2CJJTI8sIZiU3DMSnrSzfQQ2QccWJ1a7VYmXqPtfRwAjGbL6pbqzOVqffmlxAQpz9+B247yiL+Cbqs",
	"FVGg3F39Yx/yhhzFbN5DuKm9EcTR3oIE8Xj6OBMq0RcGdIy7eFdnnGJ1yXCggatxFF14Zb04i90R4dWH",
	"EaQs6MOP4T2sjhhLaTfV0dGWgppjKca7lsqLR5UnS8AK4WZfiLwQmsYx5SufEyQKuuoU50ej5lRl7IgJ",
	"stXdTX2wH5wyfe+8sFMBuPDlvxgXRVUf7K/NPISdI06LSJ5AkMmXvQSLmUcchbGbx7n5ZbdJahEJzIUL",
	"YkXmWCE4wazSn20YWCFUvnCxIkQmsGoGXHGewHVcefjYCyIL5RFZt0Ejvcn/kewgJumLogQioVdTNzSk",
	"lV4j8rKFL293ib3CSYb45RaQXpiK6odogEVQ+I2PV39dr009wVutKauV4YfobINR5owIfD2RRoPmscCE",
	"flLm6/XFzXqQLAzyN5h7T0FG4sfslH5jXn+qoGthXF8e0YrKD0IikUiIOQ4UfYu16Tf6LNIJA/YTWN8C",
	"KqypJXQrXMNLA5H+97eagl8BY5ryWFNuYJ6TAKNPQlPmE951GjeJsgo8SBl0Gol6CjKTZGAhVLtQoyTm",
	"/IxCJYyEEnLS20OjkDXn0bIIuZYdGV6B5qAsC+8eNhMyHCK56rvHlQcT2Fug+mKtMjWgv76tKYvOlihp",
	"jzpZuTau33jrjnyxEb97BZS19EC7kgU1H6OSD9D2wqhkTX1AFqWmjKWNpKV20ZcfVopzxNE8f+F8E5Nk",
	"vmlug386zn57vrGpjUkyp882t7QwSab17IWOC+epx9b2DA71Td71cbXnOlrn1b3uMEAFntOYMjH7M1aQ",
	"hZIooUbDAuyO+uXY1E+7lgTqq5uzjgilW7/5ygS75x4Ii8Yw5MZJ4BkbC0Yuna+4cLsX7MSe8qD4CaKo",
	"RnJfHhXky1eVO9crU8YLwDQtf2W8AYJMzRa9nvyF7Hoiak+/IEW3awsOoY89g0U4lCuDfmZBpBsY05SP",
	"8GKZRdof01cL2VeXkA7pGhKvrsUPQ276jwKf81EibD/tA90toUHYk7SIn5McUuKwqCcFcNOeEWVf1Kjv",
	"TTEDQqZwMrdaaX5rYyzxRcJ0vbTbELf02aaGRrieL7S1X2CSTEPbuXYj/xr829J0Bv75pqmpg0kyF5sa",
	"Wi+cr7c+fWV9+ov16Z+sTyfoVzvsBeQI/1RxeE94+Ttc6f9putjU0vY3+gokSZR8jvYLROGvEKwewNGj",
	"kLqh0g4cYQb5ha9bLqmuRdCV5FTcf0ME4bve6NNL1SF4deH4n/rqfBnnbKgMTujlp9vzRa2ognOtMpcw",
	"w9gNa2n+uPkFxE3AK2u++m5CU55hxTmfb+8RcwkUZDNSefAR2ApY05+iXSHVpTqJn4BIZXNXX7tdfbsO",
	"9q+iksuwgsBJ6F04dVMfn4LrFnjaWyMayvU0VebMN5/REy0HbrSBd1pRsQN5YETXvZfA28NLqSxfR5aU",
	"0cqrN+jZeQM4orKU+IGRCryQ/5GVOPYHBjkb37lenV2zXrr69JJ+/y1yNLqjj69opXXkObmuD8xsbY6g",
	"5JfglLE9M496lQ3oKosQcAWWrjkEkjWklL+J/lvFL12KdEpKtlEFrnjiGUYfcU8TLrAGjCO4FAgCVj70",
	"Jpm/i0IMgdqk2H8TBS5UCY/kJGPB9urI+C3GnD/odBh0HTE2bmt1XS9D6hrsLKLPDsHZKarYg0pT5iCz",
	"DXZa2nFSDBIhl1mJZwU5zpvE7hwIvi47PYU1SRCc2uhJOahQ0p89AyipC+jIvwadaFHFcVSQhiSFQQ6H",
	"VSsqjmbKQvXajKZcs2La0CF5YZqDJ3DQzJ6AtovNZDqN50HUPlZmkki4AJCZ5BUDHdbCgtCBjogPNsA3",
	"f2CtOm54hwGPGl3TlHlMpIYoWFrffj5emZ9JdLMyZxh0cixSyumr6vbMbX16CRF8cXtzzdLwm07hbzV1",
	"sXJrydT2l0m9nMFT0WT64ub28oyZh2SEmNJ7OeIFRPSGsd9ZERr/XQz3u8Q8x4UV1NH5GkNr9MEMYOEc",
	"B3Kxj8/7u83a1DMUvzurlW6TyWxx5/NcQZZYehbeb3iJCwqdR6qUkHTIUTMh7ywJMutJ5BvY0dna7m8+",
	"FSN0Rk2Rxj8f3sVOhx0jYMoKIOpNMlwmklOdqe1C6o5u9u+8wLXzfw+d6xzZFtFhRmTTUcNBiLa9yQP2",
	"b3YdGovYyIAwAl82ID0kY2DS37fZBVIXlKjHkpe4dpmVZGrmIWWhOl+2HJUqQ0VksAM3I3giI4ek2r2n",
	"levWoV0AQXmgVL32AUnQC1VlQVMnUTq7G+ARiIKdaspNZKu1/ZC8yxIzPNvN+fCJ2TFIoOblE3XJY/XJ",
	"Y3+5RHmFE57JlOfFEro+PyA9eBmzZnBH/AAy+9bHB9vzHwgXxnnTSFSEhEp9ffoM7FEf7Ed7JG0olj82",
	"k2RMf2zzI92sAmG1DVl6oDTOKIU9dIy8UnHi8WDoNngg+45MJAbRitO7Tg1ipMZCmXvoiLRyZKEXAuTm",
	"wlAnQNja1Ha66XxHwxlQdTecar/Q8m0HfDz/7bmmtoYWPyDKbWyap2lcqv3LIIENLtWUX/WxYX3zGsrM",
	"rKCnxk14jMGHW/jSQOKXQdjY/T+mwRxWYrvHeVZSWZuwHUY/3oBzZKS0eo3ECHiDbm1c39q4WVl9Aa+r",
	"xeuWgwuGnWWncXuLmrsP4lEEnEBkYKWs3BOlz0Xc0utdioayRqKxG6K7D0DgmUlsc2t1BHvEEnDAGHmI",
	"837gkxBTJ3eWl1tF3ng4uHQkxYmt9304oZw+NAyxOYMDFusCV96nw3bMZhyfomZg9q0sdeu/ruulcSTM",
	"zxh8tHQDq0iCtbOkRx177O8Nx/6t7tjXPx7/4Ydjl7744Ycv7e8ufUH1pmsW8oUMi29+mrvCdnFCX5ys",
	"FOe2SxvxHSTt0QHv1NEr927sfHTQ8YmS7xPVHbFQVM0HwCZC5a/GC0vZRH5Ui/hdhpOvLpA2e8/56obb",
	"JLZjvy1F7MIM5n3m085Zc77VSrsTnDnHYjXqonHowoJ9IYlJcKYUSixIVgzbIkjKMDwr8Nm/clejQ7c9",
	"J/EyZ2hU3KDtNCKTA8VYI8A45QiiC0Go2RL6OWIFAvvZLXFyXcJHPFhTb7XsdZnfotANaQqC/k4X2ogO",
	"RK6epgNYxN6oOTwSHNaQwKXbLUEdYTzvAvVjvMSZbQmZNppxkxSEKd5OSBIOkYFdou+DIki/ljtxfG2j",
	"0JXhU3K+cQdvMZdjfjQQOFz0vV6NE2sQXt43BJd0UTXsI2ZcQkK8gnTT6mS1bw7F/tzFLzzbTSXaIs6Z",
	"PSgreDCx/Rbc5PTxxepACeooKfMGyPuXQYxUJ/Wl61jVjttoykujl1ImORRw++ml2oMnZvAgRAKaGLuN",
	"Tdno8wKMpryHXwdKyAp430Bmlstw4a9W1GgHvguIg17m01w+YjGFVldzYoTzBVnio3ALq6HxBEF3TZZL",
	"Xw1/YKNWYBC0mHEcro17tfdwnFVKJbyv3RxGkNluriWiLdJqamXntzKTBnUk8pCizEdSFNZ90Wzn0MpF",
	"OwumC4TnJJCkXBsYAxk4yNuF7OwFNom0oKyosH2fHF7kejCHdFV+iiQfy1zWJwLbcXTJ13pRdfyklA3N",
	"rvVa9yTB2J1Pk7XGQ3JpSjL5Qqd8NRfayVpou9E+iD7MMYP9olx7j46kvfOP2ht/JX15mfRXCvJhjnti",
	"HZ5LnpnTPLy8Ogvw50kjjN1yPUmJmQyXMn5Cnvr//WEQVR777w9DIW5Qvu5OFs78UnPQUbYXbk/W1Afk",
	"9eSh+OgECrLBb2D4ppgeSJwhBayJJarqCRYRDmoM3jB3iNjQPkBA++YDIiC8l76k1pxHy5XUtezI8HKF",
	"hfhz1kl9XAWBm3678elYnMuAjje2ipgj4AxBDtBD8GE9GJfSQOxGYK577FNqTX2AZ96n4IOVgb/y+INb",
	"5As1SrSwQjrLSpRsN/r1R7WB6/CmVt/r0/PewBy6WxZGIzLTI0nQvF4VHPcCPwSF81g+U9hKbwfL2H5T",
	"PQX54vGegnwWxjJa/G8c0mMn5sHxPPriauXtLU2Z21qf0pTFOnDiksRcHrlw4VgedKhwdA9sxplXw/AE",
	"czlR7ZnLFF57eDSEGS2FktHKZyN6FQCcIjaNKQQCCCOflFZJzLXn/NJtR/aSCGQZBiCNPRtQMhdKO05I",
	"09IkwAGmxQhiHYsyWpke0offhypk0Wh+Bi+9b8hl8PrvD4MuqxYImPEMWy1O/RJt/T6+FilIrhiqTzhz",
	"qgFlYcQJ9S04hWqvTJgCuiLZwEjY+Rq08JrtldBQes7ly+DWuj/U1FcoU8xbvfzeZb6NAPBzbO5M5mqO",
	"Yjva+rhYfbjkYhL1WFuJvDgXDX/W0rpp/jDSqltxigZvM702u2Ei6FhvhoqZrKeogNCDuSt4cKKYMiNm",
	"EQEJfjLZVBl8PYuKKKU5ye4C3yPeBd6fpoeoxc3cfqITY/rQmFZarz3u19fATAwEu1qEyNO+VSvCuPJh",
	"HHmklrc+PqjdXUsUhJ8E8Qpy1jKdadFqZ6cQ8yxbbH6hUh6hccb4RNptIsfzJNiZYOoZBoFxx6wKL8+S",
	"WU2CxoPSydkvvjBcC6uUocrWwBqZ7QlaTt01GyxaStmfuq2nuPnjKtZogb37+n0UyPrc0ur+IGytjiG9",
	"btkcYnHro1q5tVQHQfVoEtOdbsjIdldUcQu4ro1yJKhgGEkKuvIO+K0Zjm4+/i5euNAIAXUNrTjAruVC",
	"x1nkEt/QcRZ909rScB7c4r/BDU/hyLwLzRCGd/pCQwtu0t7RfJpJMueaOtA37R242ZmWhnZwrT/d9rd2",
	"/MvppraGc6htS/O/ftvcSH1jmqjx8xMxwj1RUgiPGi6Uz5habZelFnkn7L0T3WeXOJdL3CfrmkZlMsgZ",
	"lHZbziBhf0IrffDSGarRZPwRiD6r4Z5blVNE/uYIKWqduZ5xfyttbfPePNIj2PWN4i446ye4XCCLrpnD",
	"KliTilpBezM2+nCX3YUdgjsiaMK9jsexL+WdpznLipfRgWk1/XRCzIXO5uZqd2A8tLw/ArUIppfIIRru",
	"LvPclUY+L0dJZ/Id2TZIJ2fziGBzlz9T8ss6YDOmfVDi4qkPSKVzzpGFjrJPO84O5aDfMNO7GflNnL5p",
	"9aG+aZfgf+Cddukfqa5oNNr3+vM/eEjmu6/Oresjt5CvnOEvSAhvEiukxSxOOyeJKN0Em8mcLXSjuFHk",
	"lsaim+sKK6TR813mJImXRSM5RR78GKkSmNtO7pWRH1+rzQ5vbc7EddJtZTOcLFMfkDdQ4iQjyNRFZLt0",
	"CArnhsa6cAFiIYdL7bFpnKaczbQ6lhNhILca3yZLS7uzL6MDhlle2On4TibrGp3Gj5yWd3N2c5cGKGmn",
	"07GTQGrYpXnVgVmZz+zaLILGCNhSczp4P82NYWH/XqfXS4Tzqw97MWb34+v2/HuhnjcmOyBODlVhTot5",
	"2b8szFt0Rw3qw4+N+tdFFd7L+uyQPjplpP4pKifqUB7PuwajN3t9caIuNhsjM2y7lmTovcvo/2OQgApl",
	"JcJPdr38u963oj8cQcmkpVQPB4MnKrefoESIq9sTG5oy44yySHGCzEkGe2eSTFchk0EhyXC+OFb6MS0i",
	"ZUcXK/3YJYlZ829JvELl7kSIrnf1UQKvrZxgRNx1aFKwzjyKC8ex1lCkcOiNZQGw0n3Z08fI+EWuwpvy",
	"C+c+3n7eDztC+AZ7BVYIqpM42sRTQaZHLOSRJCWLEvybyvACn2KSTGc+R4epKHNC6qp/qYyyoVNCRZNQ",
	"Ss+yXhwj6ynhDJ9aUalHdIrjH+q/PKEXx2KTpyR2cfk8PTOKslJ59nqPXp27vZiRt2wsW4exL+Q8uzMz",
	"uT0IvhPilbYgevt4JOzA5QmSbe5kCTipZ6RIeaqnHPmMwFNbKKHyYRf4fWhLH3xQmX6E/Wc9dLYD6Bjp",
	"S0J9qVGeE5/SdGiQ4D01p/02FPvGDnsKuIgoEI6GQ3ZQ9EEqin7Q9m7cvXuIpWX3vbGtDdLlEbzBPZFE",
	"rJkOShhxnT6fvVnZcTEWcS2BuLIrmgFzqUgOvGTWXhoT8Pd9hScCRdO+Ua4OvfDeFXsbwRI7K38nVPYD",
	"oTC0j6OooNnTLAkY3hO1PNyAFDHcTmdmiwWfBEc8Zlico63GC6/2a0cUHqB2cQd6QeKpEPyAMdpZOr42",
	"TkhzUjRKNtrurMwDih/Nned+ljskvjuCP9hFZ3NikFaJuxxjEKK5WXAijke9sWvy/JEnClGRH2+hXwOY",
	"v+zRNZA7uAsAO9xES66MfZ/q9eKI5f9kpTk2nQ1wGz4Nblw/H09fhe/wS8FwlfIpN+SFWdRqQumrERtG",
	"P4KU4E2TmH5m0Iw+0HRHAVFj94ff0+pY2zW4Qnhdhoj4MXMEhHXByQTMuzeKKcaTEcCT2c/6xSpNZS6I",
	"BhzbA8OvSqsXIuHmOqL4K1yJcTt0x+0gxevgApnEwJSwziTD0qHkKB3lX8rKKDyES1Mp5a0Pq5ryVn/f",
	"B/oZVKZKUye9laosVzKXq8FXoXWZ2tgrtBU587frffNbGze1otpx4VyLI0BeKZvOx4OVuZFa8XFYrA9p",
	"dM3vWYVRyyCa35v80nZ+tvweZZg1cmfxO8g0FzCclfEw9qC+Ob/ssdtiJRJz5mCjDZthLzvyBEQzW7sT",
	"DFA84/vmsU+d3rdcK94zErIZBS7ASLj9tK/2dNPOPGBXT5yv3n+3tTarKbf1vnmUNG8VisHM3dGUBeS0",
	"/Bor57ALX/X+u8r1Z/qHW8gZ1C7iifWDiQTvXGo+gTSTKCsceEMt6n3PkIfcPZTvABUjWVIhqaO7nBjW",
	"IxoFNXEUsnPk6C7qbuh58cKbITv5vYkq4k2v+PzeONLHU335Kbwyho979JEsr3jKaFnDETT6aJbrKG00",
	"ZHHO74GFOme9+/N7pJyI7+dNr5ya4nMxCKINtaeNlE8hLda/xcrZ2W53oo5pOyfEVRegTrQxwQAXo3AO",
	"n6EnE/XKEY6i+pSU4q+31qBMnFmO6mV1ZXz75evK/dXgbFVUP0QDDRTxwOCgu4wk5YVcQY5LFc3QaS90",
	"2gEvS2NhVEGOWIQ/YLD75w6fAi7f0j2o4hNQYRbvx88ia2xnH9xs/I/4PjyH21x5Ct3bfGkKvEPk0YFM",
	"GyO39OH7McME2qx0DXQzGyqHXZzDxrYOiWNBVFAWDHufcpesVo8iTmYq00VNVZFEcg2lRlIn8WCV1UGI",
	"rFIWcDcPSnK2yS+QbxvNAPpoPXGyKrkK8YcWJsQTJK21URFGpKX1vrZx6l6lbKTrnRiDjGCeytj64ibl",
	"+WGNGT2fbrg7Biy3TaQUXEedk9a0flttE2mBvLXSPNSjIvdZVE1REFmVYfjzWD/jqLQIuXJZXjgOKXqR",
	"7ga86/v7YEAscSpzCYm98qUsZjMJLJyihA2jplj7SFMVfWJBUxX8DWF27mRRpv9OLi2JyLMrJWbsj5LE",
	"p5FhPy2BUCF0GzVIeQH5ev1oNOzmhJ9YgYG64XKqh4NPGf4ybi52dfEpgFquh5Wy2BNa4vKy0dXUZuJP",
	"nPGtLPIZTkb+B7wM49AM4IYc4FtRBmrQG6owHLojcV2k6guysTtqNxVHkYxuvgaKEIhjBz86chkXlU6+",
	"G77d2hir3l+tPP6AyuHP6aujtYFBjDYjTmZ2DiUvgnTzdgFzXKwM/1LWb8yjtAkL+uI1TR2urKxrSr++",
	"NI5K7L5AZp2PLk2et5Iq301Pom7UWPdAbwfF1Pcn7k9CVdOtwL9OnsS2fbBIqY/iQzKCHlmPIPZp4wmq",
	"mAPo19RN7MPoCN5KSCKbzvNp7vgVPpOG6CyJzecbOSHPy1ePA1yNzyio9MGT6osxR3KLxX5UT9sI0sqI",
	"IvbNRzhdhpAo9B060qguLkpth3WtRmQ7GhhR0tb6HRzeStArKv+OorfUa5i+YNbyPSPgJjDMKm4WAMch",
	"ohd5tEDjwK6VFdKTCTKmqcYEX9x41TiLosZvkTtzDkmuKjgbQTtZ4sXFgK492n6OCkDf2NhafY2qY8/r",
	"9x/WlI97USm7vYfLyH5pv2tKefvXDWo63xPJ+jpaNl9kyD1lpPZzazQNw3Jl+pVPpBJyVTAK0Ec1F9s4",
	"2UFXHAVj2cMjmbTdogsxhHstSXtHVLQbQ/qDas8dOIjt+8+K9GR3cXaQOPX88fO3kcvJPfTRQfX1AhHT",
	"II71r6ws62vPScKqT36VpOaJbifDIAKH3h8v+HaXsTV4CaVXZiLqDz60njbBFK5QwBA9tFAQF8EHZynD",
	"26JSu90vAgpXsAFhD9ywcmw4nO0MwD6WwBwbviu/ZCP0ne2F8ThM37T3j+Z2Ly1F226EonFxD6Q7W6Bn",
	"LfWV8m+1e5CqpHZrRVNuQcIepGKv/jZaU64TJelx/ZeFytRSrVz+r/5JffipPjr1X/2T230TlVu3IZNo",
	"8Y2mQh4TswS0kV7TbHDbehORHLMuXDFAeFh4H7Xj16vvxryFk50kA1LG6T0pHY1dvhw5A2n51ywooFif",
	"xXpTANvL8EPvUqwCAFb0umUiAOLCCY4u7lUiRwP0SrkyXdRn5yqPP1TfjflkdLTnpR4ZohKfy4vk9Yg+",
	"fB+gOfSiOtGProsZI7Br14KdXOjq+isvpP0c/SujAzizg5FyoqhiF3/IRjH4XB98od9U4DOUH1s3rGWl",
	"9eoGsuZOjGrKHaiwp8xVhpY1pd++wpmugiTwcgG5nwNVIL0AfsWnuRTSA8gSS/dG73AGWbtZC67D9sYM",
	"r7GTXBHTN51vOvc3Jsk0tLT8zSrMxyRxbV7/OY3w7MAZsSHdnKi9+fyZliY8E31gnp6JzTDLex/fR807",
	"sAvXAgm1AhMlQw4iDyd+0oTencTLZ5e+dFdYOYofmzVbZPc1P381l1ubuWNzJTZmaPwIyNJPVDFIcy9k",
	"E7r5al+EEkhh7l9bUx/s3557qq88A+amlHFiGuIc56SrmDvlwCKZx5BPFWRfjSFMd0Zi01zoXIhFvTKM",
	"CEW1tnDHLmBbfKQp4/rsPfj/5m0Xj/9LmNTwbR7uvfYUR9NjbW18hFAlFJNvCmBk/O2pho6OFlyovKkF",
	"XpgN5+l1Q79zhYA7p2lo3n4+Vb01ikuy7EXyqu+IArTuLd3EV+XZ1l1fjRS3VK/a5dVM7d51fXlWKy0a",
	"eRRxzkf1FX5beoiQ4qfqJY+hsdij+mpnKkvv6JWWTiSP0ZUzF4nM2LT6s5hifN+rXZyQD+XFDVJWlBqN",
	"tmaglLv4bWhEjKMDMgq7q6EEO7g4Wjv6m/VOovVHrT1MydgdbXOepXrmpjEwv8LYRr6loooPFNbyYkuD",
	"PngbhK/RASsKENIpbY6cTPzAnKirS3T/wCR+YL5K/IQ/1Cey3T8wjPORharP/Amq0aBPf/6XxJ+y3f/Z",
	"/Z8/df+Z+uKia83JqotGyUbTq8qU180y3uqk0QBFuEKYY1ExZEnj+7JRsYEo14jlTZRTchVMG8p9yDuF",
	"26uTqN5YkUwLLF4RZPGKgA1EfJoTZJw1gBfSBdgLtUxhLy7rgNxrZV6GM8K0QQndRFOal0Up0dDaDHEo",
	"nISDE5m6L+u+rAOgiDlOYHM8c5L5C/oK6wrQkTnO5vjjl+uPG/6Nx2TLA6qbrgN5i/yvsSO2Oy2pPj6l",
	"b8JBh0OJyAleWgzpBZlH1zrad04U8niqr+rqXEZONpfL8Ck0xPF/z2PZD5N+HJdLNBeCm3MXHT1cAk4L",
	"l5cTPWw+kS+kUhyX5tJfYpGziy1k5D1bEa5sTVlGg5AoCNzPOS4lc+kEB80SJly+xG40bHceCMYBQeYS",
	"aIzEfBz0bExXBieCEXMa7NucoR/m8vIpMX11z2DgdIR1citZKnC9Hoqo38e5I1JDghXSCTYhcFcALShw",
	"BjXo5DghkULgSifYfIKFnwsZ+ahQT2/S59gf/4UX0tzPvZiwMpzMRScxfWi4dnc2mMQa8ZjAfiQ2y8nI",
	"efD7XxgeBs5h+zx+TDFoIYybTJIE0Dxi+SUPDf2Td/kdPZzEJfh8QhCtWsmymMhzQjrRJUoJuYfPm9SQ",
	"THQW5ITcwyV6ODYNQfBZ9mqik0sU8lxXIfNl4uhwi0IMZlG5/64ytRSMyW9zaXafMfk/gQnVHT4TOoJM",
	"BaIaQgUJoLnXSGd1O7IgYcU+7LsUYc30yYgQNuyC5Ac/rNDlB3vMfRUeiJCXg5UcXBP/wcQGB8XQj3ck",
	"gcGHpnwEBnvWz9LCoTCGQgy+4CMq2EMeSTkhJr+pO2R+c9T4BwpSDJMPkE0volhgRzDuu1xgT/XJCAYE",
	"9AIkAzc+6AIBMda+SgRkzOrBigTumf9gMoGTWHwOdRSpwEVPPsIAMd1naeBwuEEhnBn4SAHEUEdSDIjL",
	"ZOoOm8kcOaYBRvpjdjl8H4tDUJVJH4nACvTed4HAWSPzU8CWDbtAQ4MPVuhygT3mvooFRHz/wUoFron/",
	"YEKBg2LoxzuaZYFOUz6ygT3rZ9HgUBhDIQZf8BER7CGPpIQQk9/UHTK/OZL8I9QhIahOaoB4cDD6AmeV",
	"108FWRH8EHyw4i8eHIDWoNlO13Pw4sEfV2fgoBj68Y4tHoSrDuxZP4sHh8IYCjH4QoB4cIQVCDH5Td0h",
	"85ujyD+iCQahwsCByAGflAgQ9fYPuPH3/7I/jHv+D3vF005n3Hs94C7/fI0f9OEOZavbL95W3y0FsdUz",
	"nHxwCKs7vHN8BDh1mDgWIIIdXenrMASvT4pwCIZOZHvt5iKVN/XhDDgN7L6LXEQp1k8BIwbUAp03CQTQ",
	"xS5jkH0VvPAcBy16kbP+wYQvmzK8pzWag6ZNNz4CmDHFZxHswI96KKsNFMKMkY6oGLaDM30kuHchBKU+",
	"opgxxpEUxuJcCp8JKCqTz+FKwUEymbs0sQ+jMGoO77tQRhZS/hTQYsItUCwjcEAXy8xR9lUuMyY5aMHM",
	"Me0fTDIjqINyao//wqdDBDObcnwEM3OGOJJZOsqNYCUd+CyV0Y56KLcNFMvMoSLLZbtFWd2hHuejwbwL",
	"IRj1kcrMQeKIZTtA5yHfB58JKAZ/dxYzorIKskazH5Owh9l3qcxZUfqTQA2BBH/ZzECDj1RmD7G/gpk1",
	"z4HLZq6Z/2jimYNG6Cc4igLNqCjvI6HZY31Wnx3O0S/4nny/O90e4UhqW+JylLrD5ihHkUMExCyRpbf9",
	"b/fcQdzruU/pRg8MSTKA7nuX5/b9Fs8dwv2d+6Pe3DnaiYxyW2M68b+tP8cTHfiBDmCiwXoUGOGIGrdi",
	"n90jwJcLvmj0F7RyR1bEyh2CcPVpkQzBvolKyz66VUdJVx+GgIuz7rtcRdSe/RTQYUAt0IZlQp8uXhkj",
	"7KuAhec4aBGLnPUPJmTZZOE9p9H8igyi8ZG1jPE/S1sHfsiDOWygyGUMc0SFrh2c5iPBtANruvvIXsYA",
	"R1L6inMXfKaeqLwdl+w5lu/hODkosC6oWKAP2yBq8u27dOYud/gp4IuEX2DknQ9u6GIbOeq+ym7ERAct",
	"wHmm/oNJcS7K8Tvu0SL1fOpm0uU7cubPQt4hsYlCDC7hIyiQgx5JaSE296k7dO5z9LiJzAen6XGU7fOR",
	"EqAe376LB1ZtwU8BHwhigQKBCXe6BID67+vV38EffL4de84/2GVvkoP7XEa73c3KiPTrHI39+R4/4GMd",
	"zE0DVTVokCOqqIl9go8Agy4EYdJH9kLdj6TQFZ3vf6Yafz7em2TynHTZxLhzvEbuMpcRUXHPBG7FJJmC",
	"lGFOMj2ynDt5/HhGTLGZHjEvn/znun+uQyXkjSl+MSkGR/r3Jq0vzEgz4itTW0R85Sz/RPxAVH3oTTpm",
	"MVI8ur71tiXTRRNfd/CuL7AV0fmF5a1FfO2QWcnmpvd276Xe/z8A",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
