[[chunk]]
name = '50x50_boss_floor'
weight = 100
palettes = ['boss', 'standard']
map = """
##################################################
#.....#!.........................................#
#.<...+!.........................................#
#.....#!.........................................#
#.....#..........................................#
#.....#..........................................#
#######..........................................#
#................................................#
#................................................#
#................................................#
#................................................#
#.........I...........I...........I..............#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#.........I...........I...........I..............#
#................................................#
#................................................#
#................................................#
#.......................M........................#
#................................................#
#................................................#
#................................................#
#.........I...........I...........I..............#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#.........I...........I...........I..............#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
#................................................#
##################################################
"""
placements = []

[chunk.Size]
W = 50
H = 50

[[chunk.spawn_points]]
x = 2
y = 3
