[[chunk]]
  map      = "..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rrrrrrrrrrrrrrrrr#################rrrrrrrrr.....\n..r#############rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....\n..r#@@@@@@@@@@@#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....\n..r#@@@@@@@@@@@#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....\n..r#@@@@@@@@@@@#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....\n..r#@@@@@@@@@@@#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....\n..r#@@@@@@@@@@@#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....\n..r#@@@@@@@@@@A#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....\n..r######+######rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....\n..rr............rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....\n..rr............rrr#@@@@@@@@@@@@@@B#rrrrrrrrr.....\n..rrrrrrrrrrrrrrrrr########+########rrrrrrrrr.....\n..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rr#############rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rr#@@@@@@@@@@@#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rr#@@@@@@@@@@@#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rr#@@@@@@@@@@@#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rr#@@@@@@@@@@@#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rr#@@@@@@@@@@@#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rr#@@@@@@@@@@C#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rr######+######rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rr.............rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n..................................................\n"
  name     = '50x50_small_town'
  palettes = ['town', 'standard']
  weight   = 100

  [chunk.Size]
    H = 0
    W = 0

  [[chunk.placements]]
    chunks = ['11x6_small_office']
    id     = 'A'

  [[chunk.placements]]
    chunks = ['15x10_office_building']
    id     = 'B'

  [[chunk.placements]]
    chunks = ['11x6_small_office']
    id     = 'C'

  [[chunk.spawn_points]]
    x = 20
    y = 28
