[[chunk]]
name = '50x50_small_town'
weight = 100
palettes = ['standard', 'town']
map = """
..................................................
..................................................
..................................................
..................................................
..................................................
..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rrrrrrrrrrrrrrrrr#################rrrrrrrrr.....
..r#############rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....
..r#@@@@@@@@@@@#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....
..r#@@@@@@@@@@@#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....
..r#@@@@@@@@@@@#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....
..r#@@@@@@@@@@@#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....
..r#@@@@@@@@@@@#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....
..r#@@@@@@@@@@A#rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....
..r######+######rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....
..rr............rrr#@@@@@@@@@@@@@@@#rrrrrrrrr.....
..rr............rrr#@@@@@@@@@@@@@@B#rrrrrrrrr.....
..rrrrrrrrrrrrrrrrr########+########rrrrrrrrr.....
..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rr#############rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rr#@@@@@@@@@@@#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rr#@@@@@@@@@@@#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rr#@@@@@@@@@@@#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rr#@@@@@@@@@@@#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rr#@@@@@@@@@@@#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rr#@@@@@@@@@@C#rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rr######+######rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rr.............rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
"""

[chunk.Size]
W = 50
H = 50

[[chunk.placements]]
chunks = ['11x6_small_office']
id = 'A'

[[chunk.placements]]
chunks = ['15x10_office_building']
id = 'B'

[[chunk.placements]]
chunks = ['11x6_small_office']
id = 'C'

[[chunk.spawn_points]]
x = 20
y = 28
