[[chunk]]
  map = """
#...........rrr........rrr........rrr............#
#rrr........rrr........rrr........rrr.........rrr#
#rrr........rrr........rrr........rrr.........rrr#
#rrL........rrr........rrr........rrr.........Lrr#
#...........rrr........rrr........rrr............#
#..$........rrrrr.....rrrrr.....rrrrr............#
#..........rrrrrrr...rrrrrrr...rrrrrrr...........#
#.........rrrrrrrrr.rrrrrrrrr.rrrrrrrrr..........#
#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#
#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#
#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#
#.........rrrrrrrrrrrrrrrrrrrrrrrrrrrrr..........#
#..........rrrrrrr.............rrrrrrr...........#
#...1.......rrrrr...............rrrrr............#
#...........rrr...2..............rrr.............#
#...........rrr......I.....I.....rrr.............#
#rrL........rrr...................rrr.........Lrr#
#rrr........rrr......I.rrr.I......rrr.........rrr#
#rrr........rrr........rGr........rrr.........rrr#
#...........rrr......I.rrr.I......rrr............#
"""
  name = '50x20_town_plaza'
  palettes = ['standard', 'town']
  placements = []
  weight = 1

  [chunk.Size]
    H = 20
    W = 50

  [[chunk.spawn_points]]
    x = 24
    y = 10
