[[chunk]]
  map        = "##..........rrr........rrr........rrr...........##\n#rrr........rrr........rrr........rrr.........rrr#\n#rrr........rrr........rrr........rrr.........rrr#\n#rrL........rrr........rrr........rrr.........Lrr#\n#...........rrr........rrr........rrr............#\n#..$........rrrrr.....rrrrr.....rrrrr............#\n#..........rrrrrrr...rrrrrrr...rrrrrrr...........#\n#.........rrrrrrrrr.rrrrrrrrr.rrrrrrrrr..........#\n#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#\n#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#\n#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#\n#.........rrrrrrrrrrrrrrrrrrrrrrrrrrrrr..........#\n#..........rrrrrrr.............rrrrrrr...........#\n#...1.......rrrrr...............rrrrr............#\n#...........rrr...2..............rrr.............#\n#...........rrr......I.....I.....rrr.............#\n#rrL........rrr...................rrr.........Lrr#\n#rrr........rrr......I.rrr.I......rrr.........rrr#\n#rrr........rrr........rGr........rrr.........rrr#\n##..........rrr......I.rrr.I......rrr...........##\n"
  name       = '50x20_town_plaza'
  palettes   = ['standard', 'town']
  placements = []
  weight     = 1

  [chunk.Size]
    H = 0
    W = 0

  [[chunk.spawn_points]]
    x = 24
    y = 10
