// Code generated by gen; DO NOT EDIT.

package components

import ecs "github.com/x-hgg-x/goecs/v2"

// GetAI はエンティティのAIコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetAI(entity ecs.Entity) *AI {
	return c.AI.Get(entity).(*AI)
}

// GetAbilities はエンティティのAbilitiesコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetAbilities(entity ecs.Entity) *Abilities {
	return c.Abilities.Get(entity).(*Abilities)
}

// GetActivity はエンティティのActivityコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetActivity(entity ecs.Entity) *Activity {
	return c.Activity.Get(entity).(*Activity)
}

// GetAmmo はエンティティのAmmoコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetAmmo(entity ecs.Entity) *Ammo {
	return c.Ammo.Get(entity).(*Ammo)
}

// GetBook はエンティティのBookコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetBook(entity ecs.Entity) *Book {
	return c.Book.Get(entity).(*Book)
}

// GetCamera はエンティティのCameraコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetCamera(entity ecs.Entity) *Camera {
	return c.Camera.Get(entity).(*Camera)
}

// GetCharModifiers はエンティティのCharModifiersコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetCharModifiers(entity ecs.Entity) *CharModifiers {
	return c.CharModifiers.Get(entity).(*CharModifiers)
}

// GetCommandTable はエンティティのCommandTableコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetCommandTable(entity ecs.Entity) *CommandTable {
	return c.CommandTable.Get(entity).(*CommandTable)
}

// GetConsumable はエンティティのConsumableコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetConsumable(entity ecs.Entity) *Consumable {
	return c.Consumable.Get(entity).(*Consumable)
}

// GetDescription はエンティティのDescriptionコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetDescription(entity ecs.Entity) *Description {
	return c.Description.Get(entity).(*Description)
}

// GetDialog はエンティティのDialogコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetDialog(entity ecs.Entity) *Dialog {
	return c.Dialog.Get(entity).(*Dialog)
}

// GetDoor はエンティティのDoorコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetDoor(entity ecs.Entity) *Door {
	return c.Door.Get(entity).(*Door)
}

// GetDropTable はエンティティのDropTableコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetDropTable(entity ecs.Entity) *DropTable {
	return c.DropTable.Get(entity).(*DropTable)
}

// GetDungeonState はエンティティのDungeonStateコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetDungeonState(entity ecs.Entity) *Dungeon {
	return c.DungeonState.Get(entity).(*Dungeon)
}

// GetFire はエンティティのFireコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetFire(entity ecs.Entity) *Fire {
	return c.Fire.Get(entity).(*Fire)
}

// GetGameLog はエンティティのGameLogコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetGameLog(entity ecs.Entity) *GameLog {
	return c.GameLog.Get(entity).(*GameLog)
}

// GetGameProgress はエンティティのGameProgressコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetGameProgress(entity ecs.Entity) *GameProgress {
	return c.GameProgress.Get(entity).(*GameProgress)
}

// GetGridElement はエンティティのGridElementコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetGridElement(entity ecs.Entity) *GridElement {
	return c.GridElement.Get(entity).(*GridElement)
}

// GetHP はエンティティのHPコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetHP(entity ecs.Entity) *HP {
	return c.HP.Get(entity).(*HP)
}

// GetHealthStatus はエンティティのHealthStatusコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetHealthStatus(entity ecs.Entity) *HealthStatus {
	return c.HealthStatus.Get(entity).(*HealthStatus)
}

// GetHunger はエンティティのHungerコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetHunger(entity ecs.Entity) *Hunger {
	return c.Hunger.Get(entity).(*Hunger)
}

// GetInflictsDamage はエンティティのInflictsDamageコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetInflictsDamage(entity ecs.Entity) *InflictsDamage {
	return c.InflictsDamage.Get(entity).(*InflictsDamage)
}

// GetInteractable はエンティティのInteractableコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetInteractable(entity ecs.Entity) *Interactable {
	return c.Interactable.Get(entity).(*Interactable)
}

// GetLastActivity はエンティティのLastActivityコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetLastActivity(entity ecs.Entity) *LastActivity {
	return c.LastActivity.Get(entity).(*LastActivity)
}

// GetLightSource はエンティティのLightSourceコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetLightSource(entity ecs.Entity) *LightSource {
	return c.LightSource.Get(entity).(*LightSource)
}

// GetLocationEquipped はエンティティのLocationEquippedコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetLocationEquipped(entity ecs.Entity) *LocationEquipped {
	return c.LocationEquipped.Get(entity).(*LocationEquipped)
}

// GetLocationInBackpack はエンティティのLocationInBackpackコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetLocationInBackpack(entity ecs.Entity) *LocationInBackpack {
	return c.LocationInBackpack.Get(entity).(*LocationInBackpack)
}

// GetLocationInStorage はエンティティのLocationInStorageコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetLocationInStorage(entity ecs.Entity) *LocationInStorage {
	return c.LocationInStorage.Get(entity).(*LocationInStorage)
}

// GetMelee はエンティティのMeleeコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetMelee(entity ecs.Entity) *Melee {
	return c.Melee.Get(entity).(*Melee)
}

// GetName はエンティティのNameコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetName(entity ecs.Entity) *Name {
	return c.Name.Get(entity).(*Name)
}

// GetPassCost はエンティティのPassCostコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetPassCost(entity ecs.Entity) *PassCost {
	return c.PassCost.Get(entity).(*PassCost)
}

// GetPosition はエンティティのPositionコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetPosition(entity ecs.Entity) *Position {
	return c.Position.Get(entity).(*Position)
}

// GetProfession はエンティティのProfessionコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetProfession(entity ecs.Entity) *Profession {
	return c.Profession.Get(entity).(*Profession)
}

// GetProvidesHealing はエンティティのProvidesHealingコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetProvidesHealing(entity ecs.Entity) *ProvidesHealing {
	return c.ProvidesHealing.Get(entity).(*ProvidesHealing)
}

// GetProvidesNutrition はエンティティのProvidesNutritionコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetProvidesNutrition(entity ecs.Entity) *ProvidesNutrition {
	return c.ProvidesNutrition.Get(entity).(*ProvidesNutrition)
}

// GetRecipe はエンティティのRecipeコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetRecipe(entity ecs.Entity) *Recipe {
	return c.Recipe.Get(entity).(*Recipe)
}

// GetSkills はエンティティのSkillsコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetSkills(entity ecs.Entity) *Skills {
	return c.Skills.Get(entity).(*Skills)
}

// GetSpatialIndex はエンティティのSpatialIndexコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetSpatialIndex(entity ecs.Entity) *SpatialIndex {
	return c.SpatialIndex.Get(entity).(*SpatialIndex)
}

// GetSpriteRender はエンティティのSpriteRenderコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetSpriteRender(entity ecs.Entity) *SpriteRender {
	return c.SpriteRender.Get(entity).(*SpriteRender)
}

// GetSquadMember はエンティティのSquadMemberコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetSquadMember(entity ecs.Entity) *SquadMember {
	return c.SquadMember.Get(entity).(*SquadMember)
}

// GetStackable はエンティティのStackableコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetStackable(entity ecs.Entity) *Stackable {
	return c.Stackable.Get(entity).(*Stackable)
}

// GetStateChangeRequest はエンティティのStateChangeRequestコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetStateChangeRequest(entity ecs.Entity) *StateChangeRequest {
	return c.StateChangeRequest.Get(entity).(*StateChangeRequest)
}

// GetTileTemperature はエンティティのTileTemperatureコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetTileTemperature(entity ecs.Entity) *TileTemperature {
	return c.TileTemperature.Get(entity).(*TileTemperature)
}

// GetTurnBased はエンティティのTurnBasedコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetTurnBased(entity ecs.Entity) *TurnBased {
	return c.TurnBased.Get(entity).(*TurnBased)
}

// GetTurnState はエンティティのTurnStateコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetTurnState(entity ecs.Entity) *TurnState {
	return c.TurnState.Get(entity).(*TurnState)
}

// GetValue はエンティティのValueコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetValue(entity ecs.Entity) *Value {
	return c.Value.Get(entity).(*Value)
}

// GetVisualEffect はエンティティのVisualEffectコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetVisualEffect(entity ecs.Entity) *VisualEffects {
	return c.VisualEffect.Get(entity).(*VisualEffects)
}

// GetWallet はエンティティのWalletコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetWallet(entity ecs.Entity) *Wallet {
	return c.Wallet.Get(entity).(*Wallet)
}

// GetWearable はエンティティのWearableコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetWearable(entity ecs.Entity) *Wearable {
	return c.Wearable.Get(entity).(*Wearable)
}

// GetWeight はエンティティのWeightコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetWeight(entity ecs.Entity) *Weight {
	return c.Weight.Get(entity).(*Weight)
}

// GetWeightCapacity はエンティティのWeightCapacityコンポーネントを取得する。
// 保持していない場合はpanicする。呼び出し側が保持を保証している場合に使う。
func (c *Components) GetWeightCapacity(entity ecs.Entity) *WeightCapacity {
	return c.WeightCapacity.Get(entity).(*WeightCapacity)
}
