// Code generated by genspec. DO NOT EDIT.

package components

import "github.com/mlange-42/ark/ecs"

// EntitySpec はエンティティ作成用の仕様定義。
// 付与するコンポーネントのセットを定義し、AddEntity でECSエンティティに変換される。
type EntitySpec struct {
	Name               *Name               // 表示名を保持する
	Description        *Description        // 説明文を保持する
	HP                 *HP                 // 生命力を表す。尽きると死亡する
	Consumable         *Consumable         // 一度使うと消費される消耗品を表す
	WeightCapacity     *WeightCapacity     // 所持・格納の重量容量を表す
	Melee              *Melee              // 近接攻撃の性能を保持する
	Fire               *Fire               // 遠距離攻撃の性能と弾薬を保持する
	Value              *Value              // アイテムの基本価値を表す
	Weight             *Weight             // アイテムの重量を表す
	Recipe             *Recipe             // 合成に必要な素材を保持する
	Wearable           *Wearable           // 装備品の性能を保持する
	Abilities          *Abilities          // エンティティの能力値を保持する
	Ammo               *Ammo               // 弾薬アイテムの性能を保持する
	Stackable          *Stackable          // スタック可能で所持数を持つことを表す
	Material           *Material           // 合成・売却の素材であることを示す
	LocationInBackpack *LocationInBackpack // バックパック内にあることを表す
	LocationEquipped   *LocationEquipped   // 装備中であることを表す
	LocationOnField    *LocationOnField    // フィールド上にあることを表す
	LocationInStorage  *LocationInStorage  // 収納内にあることを表す
	Tile               *Tile               // タイルエンティティであることを示す
	SoloAI             *SoloAI             // 単独行動AIの設定を保持する
	SquadAI            *SquadAI            // 隊員AIの設定を保持する
	Camera             *Camera             // カメラの位置とズームを保持する
	Position           *Position           // フィールド上のピクセル座標を保持する
	GridElement        *GridElement        // フィールド上のグリッド座標を保持する
	SpriteRender       *SpriteRender       // スプライト描画情報を保持する
	BlockView          *BlockView          // 視界を遮ることを示す
	BlockPass          *BlockPass          // 通行不可であることを示す
	PassCost           *PassCost           // タイルの移動コスト修正を保持する
	Door               *Door               // 開閉可能な扉であることを表す
	Prop               *Prop               // 置物であることを示す
	LightSource        *LightSource        // 光源であることを表す
	Interactable       *Interactable       // 相互作用可能であることを示す
	VisualEffect       *VisualEffects      // 紐づくビジュアルエフェクトを管理する
	TileTemperature    *TileTemperature    // タイルの気温修正値を保持する
	Player             *Player             // 操作対象の主人公であることを示す
	Profession         *Profession         // 選択した職業を保持する
	Hunger             *Hunger             // プレイヤーの空腹度を保持する
	Wallet             *Wallet             // プレイヤーの資金を保持する
	FactionAlly        *FactionAllyData    // 味方派閥であることを示す
	FactionEnemy       *FactionEnemyData   // 敵性派閥であることを示す
	FactionNeutral     *FactionNeutralData // 中立派閥であることを示す
	Boss               *Boss               // ボスエンティティであることを示す
	Dialog             *Dialog             // 会話データを保持する
	Dead               *Dead               // 死亡状態であることを示す
	TurnBased          *TurnBased          // アクションポイントを管理する
	HealthStatus       *HealthStatus       // 部位ごとの健康状態を保持する
	Skills             *Skills             // スキルセットを保持する
	CharModifiers      *CharModifiers      // 効果倍率を集約する
	StateChangeRequest *StateChangeRequest // ステート遷移リクエストを運ぶ
	StatsChanged       *StatsChanged       // ステータス再計算が必要なことを示すダーティフラグ
	WeightDirty        *WeightDirty        // 重量再計算が必要なことを示すダーティフラグ
	ProvidesHealing    *ProvidesHealing    // HP回復の性質を保持する
	ProvidesNutrition  *ProvidesNutrition  // 空腹度回復の性質を保持する
	InflictsDamage     *InflictsDamage     // ダメージを与える性質を保持する
	Book               *Book               // 読書可能な本であることを表す
	CommandTable       *CommandTable       // AI用の戦闘コマンドテーブル名を保持する
	DropTable          *DropTable          // ドロップテーブル名を保持する
	SquadMember        *SquadMember        // 隊員であることを示す
	Activity           *Activity           // 実行中のアクティビティを保持する
	LastActivity       *LastActivity       // 直近のアクティビティ実行結果を保持する
	GameLog            *GameLog            // ゲームログストレージを保持するシングルトン
	DungeonState       *Dungeon            // ダンジョン状態を保持するシングルトン
	GameProgress       *GameProgress       // ゲーム進行データを保持するシングルトン
	TurnState          *TurnState          // ターン状態を保持するシングルトン
	SpatialIndex       *SpatialIndex       // 空間インデックスを保持するシングルトン
}

// Components はECSコンポーネントのハンドル束。
// 各コンポーネント型の型付き *ecs.Map[T] を保持し、Add/Has/Get やクエリに使用される。
type Components struct {
	Name               *ecs.Map[Name]               // 表示名を保持する
	Description        *ecs.Map[Description]        // 説明文を保持する
	HP                 *ecs.Map[HP]                 // 生命力を表す。尽きると死亡する
	Consumable         *ecs.Map[Consumable]         // 一度使うと消費される消耗品を表す
	WeightCapacity     *ecs.Map[WeightCapacity]     // 所持・格納の重量容量を表す
	Melee              *ecs.Map[Melee]              // 近接攻撃の性能を保持する
	Fire               *ecs.Map[Fire]               // 遠距離攻撃の性能と弾薬を保持する
	Value              *ecs.Map[Value]              // アイテムの基本価値を表す
	Weight             *ecs.Map[Weight]             // アイテムの重量を表す
	Recipe             *ecs.Map[Recipe]             // 合成に必要な素材を保持する
	Wearable           *ecs.Map[Wearable]           // 装備品の性能を保持する
	Abilities          *ecs.Map[Abilities]          // エンティティの能力値を保持する
	Ammo               *ecs.Map[Ammo]               // 弾薬アイテムの性能を保持する
	Stackable          *ecs.Map[Stackable]          // スタック可能で所持数を持つことを表す
	Material           *ecs.Map[Material]           // 合成・売却の素材であることを示す
	LocationInBackpack *ecs.Map[LocationInBackpack] // バックパック内にあることを表す
	LocationEquipped   *ecs.Map[LocationEquipped]   // 装備中であることを表す
	LocationOnField    *ecs.Map[LocationOnField]    // フィールド上にあることを表す
	LocationInStorage  *ecs.Map[LocationInStorage]  // 収納内にあることを表す
	Tile               *ecs.Map[Tile]               // タイルエンティティであることを示す
	SoloAI             *ecs.Map[SoloAI]             // 単独行動AIの設定を保持する
	SquadAI            *ecs.Map[SquadAI]            // 隊員AIの設定を保持する
	Camera             *ecs.Map[Camera]             // カメラの位置とズームを保持する
	Position           *ecs.Map[Position]           // フィールド上のピクセル座標を保持する
	GridElement        *ecs.Map[GridElement]        // フィールド上のグリッド座標を保持する
	SpriteRender       *ecs.Map[SpriteRender]       // スプライト描画情報を保持する
	BlockView          *ecs.Map[BlockView]          // 視界を遮ることを示す
	BlockPass          *ecs.Map[BlockPass]          // 通行不可であることを示す
	PassCost           *ecs.Map[PassCost]           // タイルの移動コスト修正を保持する
	Door               *ecs.Map[Door]               // 開閉可能な扉であることを表す
	Prop               *ecs.Map[Prop]               // 置物であることを示す
	LightSource        *ecs.Map[LightSource]        // 光源であることを表す
	Interactable       *ecs.Map[Interactable]       // 相互作用可能であることを示す
	VisualEffect       *ecs.Map[VisualEffects]      // 紐づくビジュアルエフェクトを管理する
	TileTemperature    *ecs.Map[TileTemperature]    // タイルの気温修正値を保持する
	Player             *ecs.Map[Player]             // 操作対象の主人公であることを示す
	Profession         *ecs.Map[Profession]         // 選択した職業を保持する
	Hunger             *ecs.Map[Hunger]             // プレイヤーの空腹度を保持する
	Wallet             *ecs.Map[Wallet]             // プレイヤーの資金を保持する
	FactionAlly        *ecs.Map[FactionAllyData]    // 味方派閥であることを示す
	FactionEnemy       *ecs.Map[FactionEnemyData]   // 敵性派閥であることを示す
	FactionNeutral     *ecs.Map[FactionNeutralData] // 中立派閥であることを示す
	Boss               *ecs.Map[Boss]               // ボスエンティティであることを示す
	Dialog             *ecs.Map[Dialog]             // 会話データを保持する
	Dead               *ecs.Map[Dead]               // 死亡状態であることを示す
	TurnBased          *ecs.Map[TurnBased]          // アクションポイントを管理する
	HealthStatus       *ecs.Map[HealthStatus]       // 部位ごとの健康状態を保持する
	Skills             *ecs.Map[Skills]             // スキルセットを保持する
	CharModifiers      *ecs.Map[CharModifiers]      // 効果倍率を集約する
	StateChangeRequest *ecs.Map[StateChangeRequest] // ステート遷移リクエストを運ぶ
	StatsChanged       *ecs.Map[StatsChanged]       // ステータス再計算が必要なことを示すダーティフラグ
	WeightDirty        *ecs.Map[WeightDirty]        // 重量再計算が必要なことを示すダーティフラグ
	ProvidesHealing    *ecs.Map[ProvidesHealing]    // HP回復の性質を保持する
	ProvidesNutrition  *ecs.Map[ProvidesNutrition]  // 空腹度回復の性質を保持する
	InflictsDamage     *ecs.Map[InflictsDamage]     // ダメージを与える性質を保持する
	Book               *ecs.Map[Book]               // 読書可能な本であることを表す
	CommandTable       *ecs.Map[CommandTable]       // AI用の戦闘コマンドテーブル名を保持する
	DropTable          *ecs.Map[DropTable]          // ドロップテーブル名を保持する
	SquadMember        *ecs.Map[SquadMember]        // 隊員であることを示す
	Activity           *ecs.Map[Activity]           // 実行中のアクティビティを保持する
	LastActivity       *ecs.Map[LastActivity]       // 直近のアクティビティ実行結果を保持する
	GameLog            *ecs.Map[GameLog]            // ゲームログストレージを保持するシングルトン
	DungeonState       *ecs.Map[Dungeon]            // ダンジョン状態を保持するシングルトン
	GameProgress       *ecs.Map[GameProgress]       // ゲーム進行データを保持するシングルトン
	TurnState          *ecs.Map[TurnState]          // ターン状態を保持するシングルトン
	SpatialIndex       *ecs.Map[SpatialIndex]       // 空間インデックスを保持するシングルトン
}

// InitializeComponents は全コンポーネント型を Ark のワールドに登録し、
// 各フィールドに型付き Map ハンドルを割り当てる。
func (c *Components) InitializeComponents(world *ecs.World) error {
	c.Name = ecs.NewMap[Name](world)
	c.Description = ecs.NewMap[Description](world)
	c.HP = ecs.NewMap[HP](world)
	c.Consumable = ecs.NewMap[Consumable](world)
	c.WeightCapacity = ecs.NewMap[WeightCapacity](world)
	c.Melee = ecs.NewMap[Melee](world)
	c.Fire = ecs.NewMap[Fire](world)
	c.Value = ecs.NewMap[Value](world)
	c.Weight = ecs.NewMap[Weight](world)
	c.Recipe = ecs.NewMap[Recipe](world)
	c.Wearable = ecs.NewMap[Wearable](world)
	c.Abilities = ecs.NewMap[Abilities](world)
	c.Ammo = ecs.NewMap[Ammo](world)
	c.Stackable = ecs.NewMap[Stackable](world)
	c.Material = ecs.NewMap[Material](world)
	c.LocationInBackpack = ecs.NewMap[LocationInBackpack](world)
	c.LocationEquipped = ecs.NewMap[LocationEquipped](world)
	c.LocationOnField = ecs.NewMap[LocationOnField](world)
	c.LocationInStorage = ecs.NewMap[LocationInStorage](world)
	c.Tile = ecs.NewMap[Tile](world)
	c.SoloAI = ecs.NewMap[SoloAI](world)
	c.SquadAI = ecs.NewMap[SquadAI](world)
	c.Camera = ecs.NewMap[Camera](world)
	c.Position = ecs.NewMap[Position](world)
	c.GridElement = ecs.NewMap[GridElement](world)
	c.SpriteRender = ecs.NewMap[SpriteRender](world)
	c.BlockView = ecs.NewMap[BlockView](world)
	c.BlockPass = ecs.NewMap[BlockPass](world)
	c.PassCost = ecs.NewMap[PassCost](world)
	c.Door = ecs.NewMap[Door](world)
	c.Prop = ecs.NewMap[Prop](world)
	c.LightSource = ecs.NewMap[LightSource](world)
	c.Interactable = ecs.NewMap[Interactable](world)
	c.VisualEffect = ecs.NewMap[VisualEffects](world)
	c.TileTemperature = ecs.NewMap[TileTemperature](world)
	c.Player = ecs.NewMap[Player](world)
	c.Profession = ecs.NewMap[Profession](world)
	c.Hunger = ecs.NewMap[Hunger](world)
	c.Wallet = ecs.NewMap[Wallet](world)
	c.FactionAlly = ecs.NewMap[FactionAllyData](world)
	c.FactionEnemy = ecs.NewMap[FactionEnemyData](world)
	c.FactionNeutral = ecs.NewMap[FactionNeutralData](world)
	c.Boss = ecs.NewMap[Boss](world)
	c.Dialog = ecs.NewMap[Dialog](world)
	c.Dead = ecs.NewMap[Dead](world)
	c.TurnBased = ecs.NewMap[TurnBased](world)
	c.HealthStatus = ecs.NewMap[HealthStatus](world)
	c.Skills = ecs.NewMap[Skills](world)
	c.CharModifiers = ecs.NewMap[CharModifiers](world)
	c.StateChangeRequest = ecs.NewMap[StateChangeRequest](world)
	c.StatsChanged = ecs.NewMap[StatsChanged](world)
	c.WeightDirty = ecs.NewMap[WeightDirty](world)
	c.ProvidesHealing = ecs.NewMap[ProvidesHealing](world)
	c.ProvidesNutrition = ecs.NewMap[ProvidesNutrition](world)
	c.InflictsDamage = ecs.NewMap[InflictsDamage](world)
	c.Book = ecs.NewMap[Book](world)
	c.CommandTable = ecs.NewMap[CommandTable](world)
	c.DropTable = ecs.NewMap[DropTable](world)
	c.SquadMember = ecs.NewMap[SquadMember](world)
	c.Activity = ecs.NewMap[Activity](world)
	c.LastActivity = ecs.NewMap[LastActivity](world)
	c.GameLog = ecs.NewMap[GameLog](world)
	c.DungeonState = ecs.NewMap[Dungeon](world)
	c.GameProgress = ecs.NewMap[GameProgress](world)
	c.TurnState = ecs.NewMap[TurnState](world)
	c.SpatialIndex = ecs.NewMap[SpatialIndex](world)
	return nil
}

// AddEntity は EntitySpec から新しいエンティティを生成し、非nilな各フィールドを
// 対応するコンポーネントとして付与する。
func (c *Components) AddEntity(world *ecs.World, spec *EntitySpec) ecs.Entity {
	entity := world.NewEntity()
	addComp(c.Name, entity, spec.Name)
	addComp(c.Description, entity, spec.Description)
	addComp(c.HP, entity, spec.HP)
	addComp(c.Consumable, entity, spec.Consumable)
	addComp(c.WeightCapacity, entity, spec.WeightCapacity)
	addComp(c.Melee, entity, spec.Melee)
	addComp(c.Fire, entity, spec.Fire)
	addComp(c.Value, entity, spec.Value)
	addComp(c.Weight, entity, spec.Weight)
	addComp(c.Recipe, entity, spec.Recipe)
	addComp(c.Wearable, entity, spec.Wearable)
	addComp(c.Abilities, entity, spec.Abilities)
	addComp(c.Ammo, entity, spec.Ammo)
	addComp(c.Stackable, entity, spec.Stackable)
	addComp(c.Material, entity, spec.Material)
	addComp(c.LocationInBackpack, entity, spec.LocationInBackpack)
	addComp(c.LocationEquipped, entity, spec.LocationEquipped)
	addComp(c.LocationOnField, entity, spec.LocationOnField)
	addComp(c.LocationInStorage, entity, spec.LocationInStorage)
	addComp(c.Tile, entity, spec.Tile)
	addComp(c.SoloAI, entity, spec.SoloAI)
	addComp(c.SquadAI, entity, spec.SquadAI)
	addComp(c.Camera, entity, spec.Camera)
	addComp(c.Position, entity, spec.Position)
	addComp(c.GridElement, entity, spec.GridElement)
	addComp(c.SpriteRender, entity, spec.SpriteRender)
	addComp(c.BlockView, entity, spec.BlockView)
	addComp(c.BlockPass, entity, spec.BlockPass)
	addComp(c.PassCost, entity, spec.PassCost)
	addComp(c.Door, entity, spec.Door)
	addComp(c.Prop, entity, spec.Prop)
	addComp(c.LightSource, entity, spec.LightSource)
	addComp(c.Interactable, entity, spec.Interactable)
	addComp(c.VisualEffect, entity, spec.VisualEffect)
	addComp(c.TileTemperature, entity, spec.TileTemperature)
	addComp(c.Player, entity, spec.Player)
	addComp(c.Profession, entity, spec.Profession)
	addComp(c.Hunger, entity, spec.Hunger)
	addComp(c.Wallet, entity, spec.Wallet)
	addComp(c.FactionAlly, entity, spec.FactionAlly)
	addComp(c.FactionEnemy, entity, spec.FactionEnemy)
	addComp(c.FactionNeutral, entity, spec.FactionNeutral)
	addComp(c.Boss, entity, spec.Boss)
	addComp(c.Dialog, entity, spec.Dialog)
	addComp(c.Dead, entity, spec.Dead)
	addComp(c.TurnBased, entity, spec.TurnBased)
	addComp(c.HealthStatus, entity, spec.HealthStatus)
	addComp(c.Skills, entity, spec.Skills)
	addComp(c.CharModifiers, entity, spec.CharModifiers)
	addComp(c.StateChangeRequest, entity, spec.StateChangeRequest)
	addComp(c.StatsChanged, entity, spec.StatsChanged)
	addComp(c.WeightDirty, entity, spec.WeightDirty)
	addComp(c.ProvidesHealing, entity, spec.ProvidesHealing)
	addComp(c.ProvidesNutrition, entity, spec.ProvidesNutrition)
	addComp(c.InflictsDamage, entity, spec.InflictsDamage)
	addComp(c.Book, entity, spec.Book)
	addComp(c.CommandTable, entity, spec.CommandTable)
	addComp(c.DropTable, entity, spec.DropTable)
	addComp(c.SquadMember, entity, spec.SquadMember)
	addComp(c.Activity, entity, spec.Activity)
	addComp(c.LastActivity, entity, spec.LastActivity)
	addComp(c.GameLog, entity, spec.GameLog)
	addComp(c.DungeonState, entity, spec.DungeonState)
	addComp(c.GameProgress, entity, spec.GameProgress)
	addComp(c.TurnState, entity, spec.TurnState)
	addComp(c.SpatialIndex, entity, spec.SpatialIndex)
	return entity
}
