// Code generated by "ruins gencomponents". DO NOT EDIT.

package components

import "github.com/mlange-42/ark/ecs"

// EntitySpec is the specification used to create an entity.
// It defines the set of components to attach, which AddEntity converts into an ECS entity.
type EntitySpec struct {
	Name               *Name
	RawID              *RawID
	Description        *Description
	HP                 *HP
	Consumable         *Consumable
	Material           *Material
	FireStarter        *FireStarter
	Perishable         *Perishable
	WeightCapacity     *WeightCapacity
	Melee              *Melee
	Fire               *Fire
	Value              *Value
	Weight             *Weight
	Recipe             *Recipe
	Wearable           *Wearable
	Abilities          *Abilities
	Ammo               *Ammo
	LocationInBackpack *LocationInBackpack
	LocationEquipped   *LocationEquipped
	LocationOnField    *LocationOnField
	LocationInStorage  *LocationInStorage
	Tile               *Tile
	SoloAI             *SoloAI
	Camera             *Camera
	Position           *Position
	GridElement        *GridElement
	SpriteRender       *SpriteRender
	BlockView          *BlockView
	BlockPass          *BlockPass
	PassCost           *PassCost
	Door               *Door
	Fixed              *Fixed
	Pushable           *Pushable
	LightSource        *LightSource
	Interactable       *Interactable
	VisualEffects      *VisualEffects
	TileEnvironment    *TileEnvironment
	HeatSource         *HeatSource
	Burning            *Burning
	StageBound         *StageBound
	StageField         *StageField
	SeamlessBand       *SeamlessBand
	PortalConnection   *PortalConnection
	DungeonEntrance    *DungeonEntrance
	Suspended          *Suspended
	Player             *Player
	Profession         *Profession
	Hunger             *Hunger
	Wallet             *Wallet
	FactionAlly        *FactionAlly
	FactionEnemy       *FactionEnemy
	FactionNeutral     *FactionNeutral
	Dialog             *Dialog
	Dead               *Dead
	TurnBased          *TurnBased
	HealthStatus       *HealthStatus
	Skills             *Skills
	StateChangeRequest *StateChangeRequest
	StatsChanged       *StatsChanged
	WeightDirty        *WeightDirty
	ProvidesHealing    *ProvidesHealing
	ProvidesNutrition  *ProvidesNutrition
	InflictsDamage     *InflictsDamage
	Remedy             *Remedy
	Book               *Book
	CommandTable       *CommandTable
	DropTable          *DropTable
	Activity           *Activity
	LastActivity       *LastActivity
	GameLog            *GameLog
	Dungeon            *Dungeon
	TurnState          *TurnState
	SpatialIndex       *SpatialIndex
	WeaponSelection    *WeaponSelection
	GameTime           *GameTime
	VisionState        *VisionState
	UserSettings       *UserSettings
	AuctionHistory     *AuctionHistory
	RunStats           *RunStats
	AuctionListing     *AuctionListing
	AuctionSold        *AuctionSold
	AuctionStation     *AuctionStation
}

// Components is the bundle of ECS component handles.
// It holds a typed *ecs.Map[T] for each component type, used by Add/Has/Get and queries.
type Components struct {
	Name               *ecs.Map[Name]
	RawID              *ecs.Map[RawID]
	Description        *ecs.Map[Description]
	HP                 *ecs.Map[HP]
	Consumable         *ecs.Map[Consumable]
	Material           *ecs.Map[Material]
	FireStarter        *ecs.Map[FireStarter]
	Perishable         *ecs.Map[Perishable]
	WeightCapacity     *ecs.Map[WeightCapacity]
	Melee              *ecs.Map[Melee]
	Fire               *ecs.Map[Fire]
	Value              *ecs.Map[Value]
	Weight             *ecs.Map[Weight]
	Recipe             *ecs.Map[Recipe]
	Wearable           *ecs.Map[Wearable]
	Abilities          *ecs.Map[Abilities]
	Ammo               *ecs.Map[Ammo]
	LocationInBackpack *ecs.Map[LocationInBackpack]
	LocationEquipped   *ecs.Map[LocationEquipped]
	LocationOnField    *ecs.Map[LocationOnField]
	LocationInStorage  *ecs.Map[LocationInStorage]
	Tile               *ecs.Map[Tile]
	SoloAI             *ecs.Map[SoloAI]
	Camera             *ecs.Map[Camera]
	Position           *ecs.Map[Position]
	GridElement        *ecs.Map[GridElement]
	SpriteRender       *ecs.Map[SpriteRender]
	BlockView          *ecs.Map[BlockView]
	BlockPass          *ecs.Map[BlockPass]
	PassCost           *ecs.Map[PassCost]
	Door               *ecs.Map[Door]
	Fixed              *ecs.Map[Fixed]
	Pushable           *ecs.Map[Pushable]
	LightSource        *ecs.Map[LightSource]
	Interactable       *ecs.Map[Interactable]
	VisualEffects      *ecs.Map[VisualEffects]
	TileEnvironment    *ecs.Map[TileEnvironment]
	HeatSource         *ecs.Map[HeatSource]
	Burning            *ecs.Map[Burning]
	StageBound         *ecs.Map[StageBound]
	StageField         *ecs.Map[StageField]
	SeamlessBand       *ecs.Map[SeamlessBand]
	PortalConnection   *ecs.Map[PortalConnection]
	DungeonEntrance    *ecs.Map[DungeonEntrance]
	Suspended          *ecs.Map[Suspended]
	Player             *ecs.Map[Player]
	Profession         *ecs.Map[Profession]
	Hunger             *ecs.Map[Hunger]
	Wallet             *ecs.Map[Wallet]
	FactionAlly        *ecs.Map[FactionAlly]
	FactionEnemy       *ecs.Map[FactionEnemy]
	FactionNeutral     *ecs.Map[FactionNeutral]
	Dialog             *ecs.Map[Dialog]
	Dead               *ecs.Map[Dead]
	TurnBased          *ecs.Map[TurnBased]
	HealthStatus       *ecs.Map[HealthStatus]
	Skills             *ecs.Map[Skills]
	StateChangeRequest *ecs.Map[StateChangeRequest]
	StatsChanged       *ecs.Map[StatsChanged]
	WeightDirty        *ecs.Map[WeightDirty]
	ProvidesHealing    *ecs.Map[ProvidesHealing]
	ProvidesNutrition  *ecs.Map[ProvidesNutrition]
	InflictsDamage     *ecs.Map[InflictsDamage]
	Remedy             *ecs.Map[Remedy]
	Book               *ecs.Map[Book]
	CommandTable       *ecs.Map[CommandTable]
	DropTable          *ecs.Map[DropTable]
	Activity           *ecs.Map[Activity]
	LastActivity       *ecs.Map[LastActivity]
	GameLog            *ecs.Map[GameLog]
	Dungeon            *ecs.Map[Dungeon]
	TurnState          *ecs.Map[TurnState]
	SpatialIndex       *ecs.Map[SpatialIndex]
	WeaponSelection    *ecs.Map[WeaponSelection]
	GameTime           *ecs.Map[GameTime]
	VisionState        *ecs.Map[VisionState]
	UserSettings       *ecs.Map[UserSettings]
	AuctionHistory     *ecs.Map[AuctionHistory]
	RunStats           *ecs.Map[RunStats]
	AuctionListing     *ecs.Map[AuctionListing]
	AuctionSold        *ecs.Map[AuctionSold]
	AuctionStation     *ecs.Map[AuctionStation]
}

// InitializeComponents registers every component type with the Ark world
// and assigns a typed Map handle to each field.
func (c *Components) InitializeComponents(world *ecs.World) error {
	c.Name = ecs.NewMap[Name](world)
	c.RawID = ecs.NewMap[RawID](world)
	c.Description = ecs.NewMap[Description](world)
	c.HP = ecs.NewMap[HP](world)
	c.Consumable = ecs.NewMap[Consumable](world)
	c.Material = ecs.NewMap[Material](world)
	c.FireStarter = ecs.NewMap[FireStarter](world)
	c.Perishable = ecs.NewMap[Perishable](world)
	c.WeightCapacity = ecs.NewMap[WeightCapacity](world)
	c.Melee = ecs.NewMap[Melee](world)
	c.Fire = ecs.NewMap[Fire](world)
	c.Value = ecs.NewMap[Value](world)
	c.Weight = ecs.NewMap[Weight](world)
	c.Recipe = ecs.NewMap[Recipe](world)
	c.Wearable = ecs.NewMap[Wearable](world)
	c.Abilities = ecs.NewMap[Abilities](world)
	c.Ammo = ecs.NewMap[Ammo](world)
	c.LocationInBackpack = ecs.NewMap[LocationInBackpack](world)
	c.LocationEquipped = ecs.NewMap[LocationEquipped](world)
	c.LocationOnField = ecs.NewMap[LocationOnField](world)
	c.LocationInStorage = ecs.NewMap[LocationInStorage](world)
	c.Tile = ecs.NewMap[Tile](world)
	c.SoloAI = ecs.NewMap[SoloAI](world)
	c.Camera = ecs.NewMap[Camera](world)
	c.Position = ecs.NewMap[Position](world)
	c.GridElement = ecs.NewMap[GridElement](world)
	c.SpriteRender = ecs.NewMap[SpriteRender](world)
	c.BlockView = ecs.NewMap[BlockView](world)
	c.BlockPass = ecs.NewMap[BlockPass](world)
	c.PassCost = ecs.NewMap[PassCost](world)
	c.Door = ecs.NewMap[Door](world)
	c.Fixed = ecs.NewMap[Fixed](world)
	c.Pushable = ecs.NewMap[Pushable](world)
	c.LightSource = ecs.NewMap[LightSource](world)
	c.Interactable = ecs.NewMap[Interactable](world)
	c.VisualEffects = ecs.NewMap[VisualEffects](world)
	c.TileEnvironment = ecs.NewMap[TileEnvironment](world)
	c.HeatSource = ecs.NewMap[HeatSource](world)
	c.Burning = ecs.NewMap[Burning](world)
	c.StageBound = ecs.NewMap[StageBound](world)
	c.StageField = ecs.NewMap[StageField](world)
	c.SeamlessBand = ecs.NewMap[SeamlessBand](world)
	c.PortalConnection = ecs.NewMap[PortalConnection](world)
	c.DungeonEntrance = ecs.NewMap[DungeonEntrance](world)
	c.Suspended = ecs.NewMap[Suspended](world)
	c.Player = ecs.NewMap[Player](world)
	c.Profession = ecs.NewMap[Profession](world)
	c.Hunger = ecs.NewMap[Hunger](world)
	c.Wallet = ecs.NewMap[Wallet](world)
	c.FactionAlly = ecs.NewMap[FactionAlly](world)
	c.FactionEnemy = ecs.NewMap[FactionEnemy](world)
	c.FactionNeutral = ecs.NewMap[FactionNeutral](world)
	c.Dialog = ecs.NewMap[Dialog](world)
	c.Dead = ecs.NewMap[Dead](world)
	c.TurnBased = ecs.NewMap[TurnBased](world)
	c.HealthStatus = ecs.NewMap[HealthStatus](world)
	c.Skills = ecs.NewMap[Skills](world)
	c.StateChangeRequest = ecs.NewMap[StateChangeRequest](world)
	c.StatsChanged = ecs.NewMap[StatsChanged](world)
	c.WeightDirty = ecs.NewMap[WeightDirty](world)
	c.ProvidesHealing = ecs.NewMap[ProvidesHealing](world)
	c.ProvidesNutrition = ecs.NewMap[ProvidesNutrition](world)
	c.InflictsDamage = ecs.NewMap[InflictsDamage](world)
	c.Remedy = ecs.NewMap[Remedy](world)
	c.Book = ecs.NewMap[Book](world)
	c.CommandTable = ecs.NewMap[CommandTable](world)
	c.DropTable = ecs.NewMap[DropTable](world)
	c.Activity = ecs.NewMap[Activity](world)
	c.LastActivity = ecs.NewMap[LastActivity](world)
	c.GameLog = ecs.NewMap[GameLog](world)
	c.Dungeon = ecs.NewMap[Dungeon](world)
	c.TurnState = ecs.NewMap[TurnState](world)
	c.SpatialIndex = ecs.NewMap[SpatialIndex](world)
	c.WeaponSelection = ecs.NewMap[WeaponSelection](world)
	c.GameTime = ecs.NewMap[GameTime](world)
	c.VisionState = ecs.NewMap[VisionState](world)
	c.UserSettings = ecs.NewMap[UserSettings](world)
	c.AuctionHistory = ecs.NewMap[AuctionHistory](world)
	c.RunStats = ecs.NewMap[RunStats](world)
	c.AuctionListing = ecs.NewMap[AuctionListing](world)
	c.AuctionSold = ecs.NewMap[AuctionSold](world)
	c.AuctionStation = ecs.NewMap[AuctionStation](world)
	return nil
}

// AddEntity creates a new entity from an EntitySpec and attaches each non-nil field
// as its corresponding component.
func (c *Components) AddEntity(world *ecs.World, spec *EntitySpec) ecs.Entity {
	entity := world.NewEntity()
	addComp(c.Name, entity, spec.Name)
	addComp(c.RawID, entity, spec.RawID)
	addComp(c.Description, entity, spec.Description)
	addComp(c.HP, entity, spec.HP)
	addComp(c.Consumable, entity, spec.Consumable)
	addComp(c.Material, entity, spec.Material)
	addComp(c.FireStarter, entity, spec.FireStarter)
	addComp(c.Perishable, entity, spec.Perishable)
	addComp(c.WeightCapacity, entity, spec.WeightCapacity)
	addComp(c.Melee, entity, spec.Melee)
	addComp(c.Fire, entity, spec.Fire)
	addComp(c.Value, entity, spec.Value)
	addComp(c.Weight, entity, spec.Weight)
	addComp(c.Recipe, entity, spec.Recipe)
	addComp(c.Wearable, entity, spec.Wearable)
	addComp(c.Abilities, entity, spec.Abilities)
	addComp(c.Ammo, entity, spec.Ammo)
	addComp(c.LocationInBackpack, entity, spec.LocationInBackpack)
	addComp(c.LocationEquipped, entity, spec.LocationEquipped)
	addComp(c.LocationOnField, entity, spec.LocationOnField)
	addComp(c.LocationInStorage, entity, spec.LocationInStorage)
	addComp(c.Tile, entity, spec.Tile)
	addComp(c.SoloAI, entity, spec.SoloAI)
	addComp(c.Camera, entity, spec.Camera)
	addComp(c.Position, entity, spec.Position)
	addComp(c.GridElement, entity, spec.GridElement)
	addComp(c.SpriteRender, entity, spec.SpriteRender)
	addComp(c.BlockView, entity, spec.BlockView)
	addComp(c.BlockPass, entity, spec.BlockPass)
	addComp(c.PassCost, entity, spec.PassCost)
	addComp(c.Door, entity, spec.Door)
	addComp(c.Fixed, entity, spec.Fixed)
	addComp(c.Pushable, entity, spec.Pushable)
	addComp(c.LightSource, entity, spec.LightSource)
	addComp(c.Interactable, entity, spec.Interactable)
	addComp(c.VisualEffects, entity, spec.VisualEffects)
	addComp(c.TileEnvironment, entity, spec.TileEnvironment)
	addComp(c.HeatSource, entity, spec.HeatSource)
	addComp(c.Burning, entity, spec.Burning)
	addComp(c.StageBound, entity, spec.StageBound)
	addComp(c.StageField, entity, spec.StageField)
	addComp(c.SeamlessBand, entity, spec.SeamlessBand)
	addComp(c.PortalConnection, entity, spec.PortalConnection)
	addComp(c.DungeonEntrance, entity, spec.DungeonEntrance)
	addComp(c.Suspended, entity, spec.Suspended)
	addComp(c.Player, entity, spec.Player)
	addComp(c.Profession, entity, spec.Profession)
	addComp(c.Hunger, entity, spec.Hunger)
	addComp(c.Wallet, entity, spec.Wallet)
	addComp(c.FactionAlly, entity, spec.FactionAlly)
	addComp(c.FactionEnemy, entity, spec.FactionEnemy)
	addComp(c.FactionNeutral, entity, spec.FactionNeutral)
	addComp(c.Dialog, entity, spec.Dialog)
	addComp(c.Dead, entity, spec.Dead)
	addComp(c.TurnBased, entity, spec.TurnBased)
	addComp(c.HealthStatus, entity, spec.HealthStatus)
	addComp(c.Skills, entity, spec.Skills)
	addComp(c.StateChangeRequest, entity, spec.StateChangeRequest)
	addComp(c.StatsChanged, entity, spec.StatsChanged)
	addComp(c.WeightDirty, entity, spec.WeightDirty)
	addComp(c.ProvidesHealing, entity, spec.ProvidesHealing)
	addComp(c.ProvidesNutrition, entity, spec.ProvidesNutrition)
	addComp(c.InflictsDamage, entity, spec.InflictsDamage)
	addComp(c.Remedy, entity, spec.Remedy)
	addComp(c.Book, entity, spec.Book)
	addComp(c.CommandTable, entity, spec.CommandTable)
	addComp(c.DropTable, entity, spec.DropTable)
	addComp(c.Activity, entity, spec.Activity)
	addComp(c.LastActivity, entity, spec.LastActivity)
	addComp(c.GameLog, entity, spec.GameLog)
	addComp(c.Dungeon, entity, spec.Dungeon)
	addComp(c.TurnState, entity, spec.TurnState)
	addComp(c.SpatialIndex, entity, spec.SpatialIndex)
	addComp(c.WeaponSelection, entity, spec.WeaponSelection)
	addComp(c.GameTime, entity, spec.GameTime)
	addComp(c.VisionState, entity, spec.VisionState)
	addComp(c.UserSettings, entity, spec.UserSettings)
	addComp(c.AuctionHistory, entity, spec.AuctionHistory)
	addComp(c.RunStats, entity, spec.RunStats)
	addComp(c.AuctionListing, entity, spec.AuctionListing)
	addComp(c.AuctionSold, entity, spec.AuctionSold)
	addComp(c.AuctionStation, entity, spec.AuctionStation)
	return entity
}
