// Code generated by "ruins gencomponents". DO NOT EDIT.

package components

import "github.com/mlange-42/ark/ecs"

// EntitySpec is the specification used to create an entity.
// It defines the set of components to attach, which AddEntity converts into an ECS entity.
type EntitySpec struct {
	Name               *Name               // holds the display name
	Description        *Description        // holds the description text
	HP                 *HP                 // represents life force; death when it runs out
	Consumable         *Consumable         // represents a consumable used up on use
	WeightCapacity     *WeightCapacity     // represents carry and storage weight capacity
	Melee              *Melee              // holds melee attack stats
	Fire               *Fire               // holds ranged attack stats and ammo
	Value              *Value              // represents the base value of an item
	Weight             *Weight             // represents the weight of an item
	Recipe             *Recipe             // holds the materials required for crafting
	Wearable           *Wearable           // holds equipment stats
	Abilities          *Abilities          // holds the entity's ability scores
	Ammo               *Ammo               // holds ammo item stats
	Stackable          *Stackable          // represents a stackable item with a count
	Material           *Material           // marks a material for crafting or selling
	LocationInBackpack *LocationInBackpack // marks being in the backpack
	LocationEquipped   *LocationEquipped   // marks being equipped
	LocationOnField    *LocationOnField    // marks being on the field
	LocationInStorage  *LocationInStorage  // marks being in a container
	Tile               *Tile               // marks a tile entity
	SoloAI             *SoloAI             // holds solo AI settings
	SquadAI            *SquadAI            // holds squad member AI settings
	Camera             *Camera             // holds camera position and zoom
	Position           *Position           // holds pixel coordinates on the field
	GridElement        *GridElement        // holds grid coordinates on the field
	SpriteRender       *SpriteRender       // holds sprite rendering info
	BlockView          *BlockView          // marks blocking of vision
	BlockPass          *BlockPass          // marks being impassable
	PassCost           *PassCost           // holds a tile's movement cost modifier
	Door               *Door               // represents an openable door
	Fixed              *Fixed              // marks a fixed object anchored in the world that cannot be picked up
	Pushable           *Pushable           // marks being pushable; the base cube is the first user but the marker is generic
	LightSource        *LightSource        // represents a light source
	Interactable       *Interactable       // marks being interactable
	VisualEffects      *VisualEffects      // manages the associated visual effect
	TileTemperature    *TileTemperature    // holds a tile's temperature modifier
	StageBound         *StageBound         // holds the bound stage; used to identify stages you travel between
	StageField         *StageField         // holds per-stage field state; the current stage is looked up via CurrentStage
	SeamlessBand       *SeamlessBand       // holds the persistent overworld band and front state; its presence also marks the overworld
	PortalConnection   *PortalConnection   // holds a portal's destination stage and landing coordinates
	DungeonEntrance    *DungeonEntrance    // holds the ruin definition name a ruin entrance leads to
	Suspended          *Suspended          // marks belonging to a non-current stage and being inactive
	Player             *Player             // marks the player-controlled protagonist
	Profession         *Profession         // holds the chosen profession
	Hunger             *Hunger             // holds the player's hunger
	Wallet             *Wallet             // holds the player's funds
	FactionAlly        *FactionAlly        // marks the ally faction
	FactionEnemy       *FactionEnemy       // marks the enemy faction
	FactionNeutral     *FactionNeutral     // marks the neutral faction
	Boss               *Boss               // marks a boss entity
	Dialog             *Dialog             // holds dialogue data
	Dead               *Dead               // marks a dead state
	TurnBased          *TurnBased          // manages action points
	HealthStatus       *HealthStatus       // holds per-body-part health status
	Skills             *Skills             // holds the skill set
	CharModifiers      *CharModifiers      // aggregates effect multipliers
	StateChangeRequest *StateChangeRequest // carries a state transition request
	StatsChanged       *StatsChanged       // dirty flag marking that stats need recalculation
	WeightDirty        *WeightDirty        // dirty flag marking that weight needs recalculation
	ProvidesHealing    *ProvidesHealing    // holds HP healing properties
	ProvidesNutrition  *ProvidesNutrition  // holds hunger recovery properties
	InflictsDamage     *InflictsDamage     // holds damage-dealing properties
	Book               *Book               // represents a readable book
	CommandTable       *CommandTable       // holds the combat command table name for AI
	DropTable          *DropTable          // holds the drop table name
	SquadMember        *SquadMember        // marks a squad member
	Activity           *Activity           // holds the running activity
	LastActivity       *LastActivity       // holds the latest activity result
	GameLog            *GameLog            // singleton holding the game log storage
	Dungeon            *Dungeon            // singleton holding dungeon state
	GameProgress       *GameProgress       // singleton holding game progress data
	TurnState          *TurnState          // singleton holding turn state
	SpatialIndex       *SpatialIndex       // singleton holding the spatial index
	WeaponSelection    *WeaponSelection    // singleton holding the selected weapon slot
	GameTime           *GameTime           // singleton holding in-game time
	VisionState        *VisionState        // singleton holding temporary vision-calculation state
	UserSettings       *UserSettings       // singleton holding global settings changed on the settings screen
}

// Components is the bundle of ECS component handles.
// It holds a typed *ecs.Map[T] for each component type, used by Add/Has/Get and queries.
type Components struct {
	Name               *ecs.Map[Name]               // holds the display name
	Description        *ecs.Map[Description]        // holds the description text
	HP                 *ecs.Map[HP]                 // represents life force; death when it runs out
	Consumable         *ecs.Map[Consumable]         // represents a consumable used up on use
	WeightCapacity     *ecs.Map[WeightCapacity]     // represents carry and storage weight capacity
	Melee              *ecs.Map[Melee]              // holds melee attack stats
	Fire               *ecs.Map[Fire]               // holds ranged attack stats and ammo
	Value              *ecs.Map[Value]              // represents the base value of an item
	Weight             *ecs.Map[Weight]             // represents the weight of an item
	Recipe             *ecs.Map[Recipe]             // holds the materials required for crafting
	Wearable           *ecs.Map[Wearable]           // holds equipment stats
	Abilities          *ecs.Map[Abilities]          // holds the entity's ability scores
	Ammo               *ecs.Map[Ammo]               // holds ammo item stats
	Stackable          *ecs.Map[Stackable]          // represents a stackable item with a count
	Material           *ecs.Map[Material]           // marks a material for crafting or selling
	LocationInBackpack *ecs.Map[LocationInBackpack] // marks being in the backpack
	LocationEquipped   *ecs.Map[LocationEquipped]   // marks being equipped
	LocationOnField    *ecs.Map[LocationOnField]    // marks being on the field
	LocationInStorage  *ecs.Map[LocationInStorage]  // marks being in a container
	Tile               *ecs.Map[Tile]               // marks a tile entity
	SoloAI             *ecs.Map[SoloAI]             // holds solo AI settings
	SquadAI            *ecs.Map[SquadAI]            // holds squad member AI settings
	Camera             *ecs.Map[Camera]             // holds camera position and zoom
	Position           *ecs.Map[Position]           // holds pixel coordinates on the field
	GridElement        *ecs.Map[GridElement]        // holds grid coordinates on the field
	SpriteRender       *ecs.Map[SpriteRender]       // holds sprite rendering info
	BlockView          *ecs.Map[BlockView]          // marks blocking of vision
	BlockPass          *ecs.Map[BlockPass]          // marks being impassable
	PassCost           *ecs.Map[PassCost]           // holds a tile's movement cost modifier
	Door               *ecs.Map[Door]               // represents an openable door
	Fixed              *ecs.Map[Fixed]              // marks a fixed object anchored in the world that cannot be picked up
	Pushable           *ecs.Map[Pushable]           // marks being pushable; the base cube is the first user but the marker is generic
	LightSource        *ecs.Map[LightSource]        // represents a light source
	Interactable       *ecs.Map[Interactable]       // marks being interactable
	VisualEffects      *ecs.Map[VisualEffects]      // manages the associated visual effect
	TileTemperature    *ecs.Map[TileTemperature]    // holds a tile's temperature modifier
	StageBound         *ecs.Map[StageBound]         // holds the bound stage; used to identify stages you travel between
	StageField         *ecs.Map[StageField]         // holds per-stage field state; the current stage is looked up via CurrentStage
	SeamlessBand       *ecs.Map[SeamlessBand]       // holds the persistent overworld band and front state; its presence also marks the overworld
	PortalConnection   *ecs.Map[PortalConnection]   // holds a portal's destination stage and landing coordinates
	DungeonEntrance    *ecs.Map[DungeonEntrance]    // holds the ruin definition name a ruin entrance leads to
	Suspended          *ecs.Map[Suspended]          // marks belonging to a non-current stage and being inactive
	Player             *ecs.Map[Player]             // marks the player-controlled protagonist
	Profession         *ecs.Map[Profession]         // holds the chosen profession
	Hunger             *ecs.Map[Hunger]             // holds the player's hunger
	Wallet             *ecs.Map[Wallet]             // holds the player's funds
	FactionAlly        *ecs.Map[FactionAlly]        // marks the ally faction
	FactionEnemy       *ecs.Map[FactionEnemy]       // marks the enemy faction
	FactionNeutral     *ecs.Map[FactionNeutral]     // marks the neutral faction
	Boss               *ecs.Map[Boss]               // marks a boss entity
	Dialog             *ecs.Map[Dialog]             // holds dialogue data
	Dead               *ecs.Map[Dead]               // marks a dead state
	TurnBased          *ecs.Map[TurnBased]          // manages action points
	HealthStatus       *ecs.Map[HealthStatus]       // holds per-body-part health status
	Skills             *ecs.Map[Skills]             // holds the skill set
	CharModifiers      *ecs.Map[CharModifiers]      // aggregates effect multipliers
	StateChangeRequest *ecs.Map[StateChangeRequest] // carries a state transition request
	StatsChanged       *ecs.Map[StatsChanged]       // dirty flag marking that stats need recalculation
	WeightDirty        *ecs.Map[WeightDirty]        // dirty flag marking that weight needs recalculation
	ProvidesHealing    *ecs.Map[ProvidesHealing]    // holds HP healing properties
	ProvidesNutrition  *ecs.Map[ProvidesNutrition]  // holds hunger recovery properties
	InflictsDamage     *ecs.Map[InflictsDamage]     // holds damage-dealing properties
	Book               *ecs.Map[Book]               // represents a readable book
	CommandTable       *ecs.Map[CommandTable]       // holds the combat command table name for AI
	DropTable          *ecs.Map[DropTable]          // holds the drop table name
	SquadMember        *ecs.Map[SquadMember]        // marks a squad member
	Activity           *ecs.Map[Activity]           // holds the running activity
	LastActivity       *ecs.Map[LastActivity]       // holds the latest activity result
	GameLog            *ecs.Map[GameLog]            // singleton holding the game log storage
	Dungeon            *ecs.Map[Dungeon]            // singleton holding dungeon state
	GameProgress       *ecs.Map[GameProgress]       // singleton holding game progress data
	TurnState          *ecs.Map[TurnState]          // singleton holding turn state
	SpatialIndex       *ecs.Map[SpatialIndex]       // singleton holding the spatial index
	WeaponSelection    *ecs.Map[WeaponSelection]    // singleton holding the selected weapon slot
	GameTime           *ecs.Map[GameTime]           // singleton holding in-game time
	VisionState        *ecs.Map[VisionState]        // singleton holding temporary vision-calculation state
	UserSettings       *ecs.Map[UserSettings]       // singleton holding global settings changed on the settings screen
}

// InitializeComponents registers every component type with the Ark world
// and assigns a typed Map handle to each field.
func (c *Components) InitializeComponents(world *ecs.World) error {
	c.Name = ecs.NewMap[Name](world)
	c.Description = ecs.NewMap[Description](world)
	c.HP = ecs.NewMap[HP](world)
	c.Consumable = ecs.NewMap[Consumable](world)
	c.WeightCapacity = ecs.NewMap[WeightCapacity](world)
	c.Melee = ecs.NewMap[Melee](world)
	c.Fire = ecs.NewMap[Fire](world)
	c.Value = ecs.NewMap[Value](world)
	c.Weight = ecs.NewMap[Weight](world)
	c.Recipe = ecs.NewMap[Recipe](world)
	c.Wearable = ecs.NewMap[Wearable](world)
	c.Abilities = ecs.NewMap[Abilities](world)
	c.Ammo = ecs.NewMap[Ammo](world)
	c.Stackable = ecs.NewMap[Stackable](world)
	c.Material = ecs.NewMap[Material](world)
	c.LocationInBackpack = ecs.NewMap[LocationInBackpack](world)
	c.LocationEquipped = ecs.NewMap[LocationEquipped](world)
	c.LocationOnField = ecs.NewMap[LocationOnField](world)
	c.LocationInStorage = ecs.NewMap[LocationInStorage](world)
	c.Tile = ecs.NewMap[Tile](world)
	c.SoloAI = ecs.NewMap[SoloAI](world)
	c.SquadAI = ecs.NewMap[SquadAI](world)
	c.Camera = ecs.NewMap[Camera](world)
	c.Position = ecs.NewMap[Position](world)
	c.GridElement = ecs.NewMap[GridElement](world)
	c.SpriteRender = ecs.NewMap[SpriteRender](world)
	c.BlockView = ecs.NewMap[BlockView](world)
	c.BlockPass = ecs.NewMap[BlockPass](world)
	c.PassCost = ecs.NewMap[PassCost](world)
	c.Door = ecs.NewMap[Door](world)
	c.Fixed = ecs.NewMap[Fixed](world)
	c.Pushable = ecs.NewMap[Pushable](world)
	c.LightSource = ecs.NewMap[LightSource](world)
	c.Interactable = ecs.NewMap[Interactable](world)
	c.VisualEffects = ecs.NewMap[VisualEffects](world)
	c.TileTemperature = ecs.NewMap[TileTemperature](world)
	c.StageBound = ecs.NewMap[StageBound](world)
	c.StageField = ecs.NewMap[StageField](world)
	c.SeamlessBand = ecs.NewMap[SeamlessBand](world)
	c.PortalConnection = ecs.NewMap[PortalConnection](world)
	c.DungeonEntrance = ecs.NewMap[DungeonEntrance](world)
	c.Suspended = ecs.NewMap[Suspended](world)
	c.Player = ecs.NewMap[Player](world)
	c.Profession = ecs.NewMap[Profession](world)
	c.Hunger = ecs.NewMap[Hunger](world)
	c.Wallet = ecs.NewMap[Wallet](world)
	c.FactionAlly = ecs.NewMap[FactionAlly](world)
	c.FactionEnemy = ecs.NewMap[FactionEnemy](world)
	c.FactionNeutral = ecs.NewMap[FactionNeutral](world)
	c.Boss = ecs.NewMap[Boss](world)
	c.Dialog = ecs.NewMap[Dialog](world)
	c.Dead = ecs.NewMap[Dead](world)
	c.TurnBased = ecs.NewMap[TurnBased](world)
	c.HealthStatus = ecs.NewMap[HealthStatus](world)
	c.Skills = ecs.NewMap[Skills](world)
	c.CharModifiers = ecs.NewMap[CharModifiers](world)
	c.StateChangeRequest = ecs.NewMap[StateChangeRequest](world)
	c.StatsChanged = ecs.NewMap[StatsChanged](world)
	c.WeightDirty = ecs.NewMap[WeightDirty](world)
	c.ProvidesHealing = ecs.NewMap[ProvidesHealing](world)
	c.ProvidesNutrition = ecs.NewMap[ProvidesNutrition](world)
	c.InflictsDamage = ecs.NewMap[InflictsDamage](world)
	c.Book = ecs.NewMap[Book](world)
	c.CommandTable = ecs.NewMap[CommandTable](world)
	c.DropTable = ecs.NewMap[DropTable](world)
	c.SquadMember = ecs.NewMap[SquadMember](world)
	c.Activity = ecs.NewMap[Activity](world)
	c.LastActivity = ecs.NewMap[LastActivity](world)
	c.GameLog = ecs.NewMap[GameLog](world)
	c.Dungeon = ecs.NewMap[Dungeon](world)
	c.GameProgress = ecs.NewMap[GameProgress](world)
	c.TurnState = ecs.NewMap[TurnState](world)
	c.SpatialIndex = ecs.NewMap[SpatialIndex](world)
	c.WeaponSelection = ecs.NewMap[WeaponSelection](world)
	c.GameTime = ecs.NewMap[GameTime](world)
	c.VisionState = ecs.NewMap[VisionState](world)
	c.UserSettings = ecs.NewMap[UserSettings](world)
	return nil
}

// AddEntity creates a new entity from an EntitySpec and attaches each non-nil field
// as its corresponding component.
func (c *Components) AddEntity(world *ecs.World, spec *EntitySpec) ecs.Entity {
	entity := world.NewEntity()
	addComp(c.Name, entity, spec.Name)
	addComp(c.Description, entity, spec.Description)
	addComp(c.HP, entity, spec.HP)
	addComp(c.Consumable, entity, spec.Consumable)
	addComp(c.WeightCapacity, entity, spec.WeightCapacity)
	addComp(c.Melee, entity, spec.Melee)
	addComp(c.Fire, entity, spec.Fire)
	addComp(c.Value, entity, spec.Value)
	addComp(c.Weight, entity, spec.Weight)
	addComp(c.Recipe, entity, spec.Recipe)
	addComp(c.Wearable, entity, spec.Wearable)
	addComp(c.Abilities, entity, spec.Abilities)
	addComp(c.Ammo, entity, spec.Ammo)
	addComp(c.Stackable, entity, spec.Stackable)
	addComp(c.Material, entity, spec.Material)
	addComp(c.LocationInBackpack, entity, spec.LocationInBackpack)
	addComp(c.LocationEquipped, entity, spec.LocationEquipped)
	addComp(c.LocationOnField, entity, spec.LocationOnField)
	addComp(c.LocationInStorage, entity, spec.LocationInStorage)
	addComp(c.Tile, entity, spec.Tile)
	addComp(c.SoloAI, entity, spec.SoloAI)
	addComp(c.SquadAI, entity, spec.SquadAI)
	addComp(c.Camera, entity, spec.Camera)
	addComp(c.Position, entity, spec.Position)
	addComp(c.GridElement, entity, spec.GridElement)
	addComp(c.SpriteRender, entity, spec.SpriteRender)
	addComp(c.BlockView, entity, spec.BlockView)
	addComp(c.BlockPass, entity, spec.BlockPass)
	addComp(c.PassCost, entity, spec.PassCost)
	addComp(c.Door, entity, spec.Door)
	addComp(c.Fixed, entity, spec.Fixed)
	addComp(c.Pushable, entity, spec.Pushable)
	addComp(c.LightSource, entity, spec.LightSource)
	addComp(c.Interactable, entity, spec.Interactable)
	addComp(c.VisualEffects, entity, spec.VisualEffects)
	addComp(c.TileTemperature, entity, spec.TileTemperature)
	addComp(c.StageBound, entity, spec.StageBound)
	addComp(c.StageField, entity, spec.StageField)
	addComp(c.SeamlessBand, entity, spec.SeamlessBand)
	addComp(c.PortalConnection, entity, spec.PortalConnection)
	addComp(c.DungeonEntrance, entity, spec.DungeonEntrance)
	addComp(c.Suspended, entity, spec.Suspended)
	addComp(c.Player, entity, spec.Player)
	addComp(c.Profession, entity, spec.Profession)
	addComp(c.Hunger, entity, spec.Hunger)
	addComp(c.Wallet, entity, spec.Wallet)
	addComp(c.FactionAlly, entity, spec.FactionAlly)
	addComp(c.FactionEnemy, entity, spec.FactionEnemy)
	addComp(c.FactionNeutral, entity, spec.FactionNeutral)
	addComp(c.Boss, entity, spec.Boss)
	addComp(c.Dialog, entity, spec.Dialog)
	addComp(c.Dead, entity, spec.Dead)
	addComp(c.TurnBased, entity, spec.TurnBased)
	addComp(c.HealthStatus, entity, spec.HealthStatus)
	addComp(c.Skills, entity, spec.Skills)
	addComp(c.CharModifiers, entity, spec.CharModifiers)
	addComp(c.StateChangeRequest, entity, spec.StateChangeRequest)
	addComp(c.StatsChanged, entity, spec.StatsChanged)
	addComp(c.WeightDirty, entity, spec.WeightDirty)
	addComp(c.ProvidesHealing, entity, spec.ProvidesHealing)
	addComp(c.ProvidesNutrition, entity, spec.ProvidesNutrition)
	addComp(c.InflictsDamage, entity, spec.InflictsDamage)
	addComp(c.Book, entity, spec.Book)
	addComp(c.CommandTable, entity, spec.CommandTable)
	addComp(c.DropTable, entity, spec.DropTable)
	addComp(c.SquadMember, entity, spec.SquadMember)
	addComp(c.Activity, entity, spec.Activity)
	addComp(c.LastActivity, entity, spec.LastActivity)
	addComp(c.GameLog, entity, spec.GameLog)
	addComp(c.Dungeon, entity, spec.Dungeon)
	addComp(c.GameProgress, entity, spec.GameProgress)
	addComp(c.TurnState, entity, spec.TurnState)
	addComp(c.SpatialIndex, entity, spec.SpatialIndex)
	addComp(c.WeaponSelection, entity, spec.WeaponSelection)
	addComp(c.GameTime, entity, spec.GameTime)
	addComp(c.VisionState, entity, spec.VisionState)
	addComp(c.UserSettings, entity, spec.UserSettings)
	return entity
}
