[[entity]]

[entity.components.Text]
id = "title"
text = "キャンプ"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 640 }

# ================

[[entity]]

[entity.components.Text]
id = "description"
text = ""
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 500 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.components.Text]
id = "item"
text = "[使]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 340 }

[[entity]]

[entity.components.Text]
id = "cursor_item"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 400 }

# ================

[[entity]]

[entity.components.Text]
id = "equip"
text = "[装]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 300, y = 340 }

[[entity]]

[entity.components.Text]
id = "cursor_equip"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 300, y = 400 }