[[entity]]

[entity.components.SpriteRender]
sprite_sheet_name = "bg_black1"
sprite_number = 0

[entity.components.Transform]
translation = { x = 0, y = 0 }
origin = "Middle"

# ================

[[entity]]

[entity.components.Text]
id = "title"
text = "デバッグメニュー"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 640 }

# ================

[[entity]]

[entity.components.Text]
id = "spawn_item_potion"
text = "アイテムスポーン(回復薬)"
font_face = { font = "kappa", options.size = 16.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 220, y = 500 }
pivot = "TopLeft"

[[entity]]

[entity.components.Text]
id = "cursor_spawn_item_potion"
text = "\u25ba"
font_face = { font = "hack", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 500 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.components.Text]
id = "spawn_item_grenade"
text = "アイテムスポーン(手榴弾)"
font_face = { font = "kappa", options.size = 16.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 220, y = 480 }
pivot = "TopLeft"

[[entity]]

[entity.components.Text]
id = "cursor_spawn_item_grenade"
text = "\u25ba"
font_face = { font = "hack", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 480 }
pivot = "TopLeft"