[[entity]]

[entity.components.SpriteRender]
sprite_sheet_name = "bg_black1"
sprite_number = 0

[entity.components.Transform]
translation = { x = 0, y = 0 }
origin = "Middle"

# ================

[[entity]]

[entity.components.Text]
id = "title"
text = "デバッグメニュー"
font_face = { font = "kappa", options.size = 30.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 640 }

# ================

[[entity]]

[entity.components.Text]
id = "spawn_item"
text = "アイテムスポーン(回復薬)"
font_face = { font = "kappa", options.size = 40.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 450 }

[[entity]]

[entity.components.Text]
id = "cursor_spawn_item"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 295, y = 450 }