[[entity]]

[entity.components.SpriteRender]
sprite_sheet_name = "bg_black1"
sprite_number = 0

[entity.components.Transform]
translation = { x = 0, y = 0 }
origin = "Middle"

# ================

[[entity]]

[entity.components.Text]
id = "description"
text = ""
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 500 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.components.Text]
id = "forest"
text = "森の遺跡"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 300, y = 220 }

[[entity]]

[entity.components.Text]
id = "cursor_forest"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 220 }

# ================

[[entity]]

[entity.components.Text]
id = "mountain"
text = "山の遺跡"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 300, y = 160 }

[[entity]]

[entity.components.Text]
id = "cursor_mountain"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 160 }

# ================

[[entity]]

[entity.components.Text]
id = "tower"
text = "塔の遺跡"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 300, y = 100 }

[[entity]]

[entity.components.Text]
id = "cursor_tower"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 100 }