[[entity]]

[entity.components.Text]
id = "title"
text = "フィールドメニュー"
font_face = { font = "kappa", options.size = 30.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 640 }

# ================

[[entity]]

[entity.components.Text]
id = "exit"
text = "終了"
font_face = { font = "kappa", options.size = 40.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 450 }


[[entity]]

[entity.components.Text]
id = "cursor_exit"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 295, y = 450 }
