[[entity]]

[entity.components.SpriteRender]
sprite_sheet_name = "bg_black1"
sprite_number = 0

[entity.components.Transform]
translation = { x = 0, y = 0 }
origin = "Middle"

# ================

[[entity]]

[entity.components.Text]
id = "title"
text = "フィールドメニュー"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 640 }

# ================

[[entity]]

[entity.components.Text]
id = "item"
text = "アイテム"
font_face = { font = "kappa", options.size = 40.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 500 }

[[entity]]

[entity.components.Text]
id = "cursor_item"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 295, y = 500 }

# ================

[[entity]]

[entity.components.Text]
id = "close"
text = "閉じる"
font_face = { font = "kappa", options.size = 40.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 400 }

[[entity]]

[entity.components.Text]
id = "cursor_close"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 295, y = 400 }
