[[entity]]

[entity.components.Text]
id = "title"
text = "拠点メニュー"
font_face = { font = "kappa", options.size = 75.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 640 }

# ================

[[entity]]

[entity.components.Text]
id = "description"
text = ""
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 500 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.components.Text]
id = "dungeon"
text = "[出]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 340 }

[[entity]]

[entity.components.Text]
id = "cursor_dungeon"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 400 }

# ================

[[entity]]

[entity.components.Text]
id = "buy"
text = "[買]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 300, y = 340 }


[[entity]]

[entity.components.Text]
id = "cursor_buy"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 300, y = 400 }

# ================

[[entity]]

[entity.components.Text]
id = "equip"
text = "[装]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 400, y = 340 }


[[entity]]

[entity.components.Text]
id = "cursor_equip"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 400, y = 400 }

# ================

[[entity]]

[entity.components.Text]
id = "party"
text = "[仲]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 500, y = 340 }


[[entity]]

[entity.components.Text]
id = "cursor_party"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 500, y = 400 }

# ================

[[entity]]

[entity.components.Text]
id = "system"
text = "[設]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 600, y = 340 }


[[entity]]

[entity.components.Text]
id = "cursor_system"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 600, y = 400 }

# ================

[[entity]]

[entity.components.Text]
id = "exit"
text = "[終]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 700, y = 340 }


[[entity]]

[entity.components.Text]
id = "cursor_exit"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 700, y = 400 }
