[[entity]]

[entity.components.Text]
id = "title"
text = "拠点"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 640 }

# ================

[[entity]]

[entity.components.Text]
id = "description"
text = ""
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 500 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.components.Text]
id = "dungeon"
text = "[出]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 340 }

[[entity]]

[entity.components.Text]
id = "cursor_dungeon"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 400 }

# ================

[[entity]]

[entity.components.Text]
id = "mix"
text = "[合]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 300, y = 340 }


[[entity]]

[entity.components.Text]
id = "cursor_mix"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 300, y = 400 }

# ================

[[entity]]

[entity.components.Text]
id = "party"
text = "[仲]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 400, y = 340 }


[[entity]]

[entity.components.Text]
id = "cursor_party"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 400, y = 400 }

# ================

[[entity]]

[entity.components.Text]
id = "camp"
text = "[隊]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 500, y = 340 }


[[entity]]

[entity.components.Text]
id = "cursor_camp"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 500, y = 400 }

# ================

[[entity]]

[entity.components.Text]
id = "exit"
text = "[終]"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 600, y = 340 }

# ================

[[entity]]

[entity.components.Text]
id = "cursor_exit"
text = "▼"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 600, y = 400 }

# ================

[[entity]]

[entity.Components.Text]
id = "party_line"
text = "───────────────"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 270 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.Components.Text]
id = "party_1_name"
text = ""
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 260 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.Components.Text]
id = "party_1_hp_label"
text = ""
font_face = { font = "kappa", options.size = 24.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 220 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.Components.Text]
id = "party_1_sp_label"
text = ""
font_face = { font = "kappa", options.size = 24.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 200 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.Components.Text]
id = "party_2_name"
text = ""
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 500, y = 260 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.Components.Text]
id = "party_2_hp_label"
text = ""
font_face = { font = "kappa", options.size = 24.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 500, y = 220 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.Components.Text]
id = "party_2_sp_label"
text = ""
font_face = { font = "kappa", options.size = 24.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 500, y = 200 }
pivot = "TopLeft"