[[entity]]

[entity.components.Text]
id = "title"
text = "拠点メニュー"
font_face = { font = "kappa", options.size = 75.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 650 }