[[entity]]

[entity.components.Text]
id = "body"
text = "DUMMY"
font_face = { font = "bizu", options.size = 40.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 650 }