[[entity]]

[entity.components.Text]
id = "title"
text = "インベントリ"
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 640 }

# ================

[[entity]]

[entity.components.Text]
id = "description"
text = ""
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 100 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.components.Text]
id = "item_list"
text = ""
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]
[entity.components.UITransform]

translation = { x = 240, y = 500 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.components.Text]
id = "cursor"
text = "\u25ba"
font_face = { font = "hack", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 200, y = 480 }
pivot = "TopLeft"

# ================

[[entity]]

[entity.components.Text]
id = "count"
text = ""
font_face = { font = "kappa", options.size = 32.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 600, y = 600 }
pivot = "TopLeft"