[[entity]]

[entity.components.Text]
id = "title"
text = "フィールドメニュー"
font_face = { font = "kappa", options.size = 30.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 640 }