[[entity]]

[entity.components.Text]
id        = "level"
text      = "1F"
font_face = { font = "kappa", options.size = 25.0 }
color     = [ 255, 255, 255, 255 ]

[entity.components.UITransform]
translation = { x = 10, y = -68 }
origin      = "TopLeft"
pivot       = "Dot"
