[[entity]]

[entity.components.Text]
id = "title"
text = "this is title"
font_face = { font = "hack", options.size = 75.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 650 }

[[entity]]

[entity.components.Text]
id = "hello"
text = "hello, another text"
font_face = { font = "hack", options.size = 40.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 550 }