[[chunk]]
  map          = "...\n.B.\n...\n"
  name         = '3x3_bedroom'
  palettes     = ['standard']
  placements   = []
  spawn_points = []
  weight       = 100

  [chunk.Size]
    H = 0
    W = 0

[[chunk]]
  map          = ".....\n.....\n.CTC.\n.....\n.....\n"
  name         = '5x5_meeting_room'
  palettes     = ['standard']
  placements   = []
  spawn_points = []
  weight       = 100

  [chunk.Size]
    H = 0
    W = 0

[[chunk]]
  map          = "....\n.XX.\n.XX.\n....\n"
  name         = '4x4_storage'
  palettes     = ['standard']
  placements   = []
  spawn_points = []
  weight       = 100

  [chunk.Size]
    H = 0
    W = 0

[[chunk]]
  map          = ".....\n.D.C.\n.....\n.....\n"
  name         = '5x4_office'
  palettes     = ['standard']
  placements   = []
  spawn_points = []
  weight       = 100

  [chunk.Size]
    H = 0
    W = 0
