[[chunk]]
name = '3x3_bedroom'
weight = 100
palettes = ['standard']
map = """
...
.e.
...
"""
placements = []
spawn_points = []

[chunk.Size]
W = 3
H = 3

[[chunk]]
name = '5x5_meeting_room'
weight = 100
palettes = ['standard']
map = """
.....
.....
.CTC.
.....
.....
"""
placements = []
spawn_points = []

[chunk.Size]
W = 5
H = 5

[[chunk]]
name = '4x4_storage'
weight = 100
palettes = ['standard']
map = """
....
.XX.
.XX.
....
"""
placements = []
spawn_points = []

[chunk.Size]
W = 4
H = 4

[[chunk]]
name = '5x4_office'
weight = 100
palettes = ['standard']
map = """
.....
.DC..
.DC..
.....
"""
placements = []
spawn_points = []

[chunk.Size]
W = 5
H = 4
