# ボスフロア用パレット

[palette]
  description = "ボスフロア用パレット"
  id          = "boss"

  # 地形の定義
  [palette.terrain]
    "." = "floor" # 床

  # Propsの定義
  [palette.props]

  # NPCの定義
  [palette.npcs]
    "M" = {id = "frozen_hunter", tile = "floor"}
