# ボスフロア用パレット

[palette]
  description = "ボスフロア用パレット"
  id          = "boss"

  # 地形の定義
  [palette.terrain]
    "." = "floor" # 床

  # Propsの定義
  [palette.props]
    "!" = {id = "door_lock_trigger", tile = "floor"} # ドアロックトリガー
    "<" = {id = "warp_escape", tile = "floor"}       # 帰還ポータル

  # NPCの定義
  [palette.npcs]
    "M" = {id = "凍晶化した猟師", tile = "floor"}
