[palette]
id = 'town'
description = '街用の地形パレット'

[palette.terrain]
'.' = 'dirt'
r = 'floor'

[palette.props]
[palette.props.K]
id = 'wooden_crate'
tile = 'floor'

[palette.props.A]
id = 'auction_box'
tile = 'floor'

[palette.npcs]
[palette.npcs.'$']
id = 'merchant'
tile = 'dirt'

[palette.npcs.1]
id = 'old_soldier'
tile = 'dirt'

[palette.npcs.2]
id = 'suspicious_scientist'
tile = 'dirt'
