[palette]
id = 'town'
description = '街用の地形パレット'

[palette.terrain]
'.' = 'dirt'
r = 'floor'

[palette.props]
[palette.props.G]
id = 'dungeon_gate'
tile = 'dirt'

[palette.npcs]
[palette.npcs.'$']
id = '商人'
tile = 'dirt'

[palette.npcs.1]
id = '老兵'
tile = 'dirt'

[palette.npcs.2]
id = '怪しい科学者'
tile = 'dirt'
