# 街用パレット

[palette]
  description = "街用の地形パレット"
  id          = "town"

  # 地形の定義
  [palette.terrain]
    "." = "dirt"  # 土
    "r" = "floor" # 道路

  # NPCの定義
  [palette.npcs]
    "$" = {id = "商人", tile = "dirt"}
    "1" = {id = "老兵", tile = "dirt"}
    "2" = {id = "怪しい科学者", tile = "dirt"}

  # Propsの定義
  [palette.props]
    "G" = {id = "dungeon_gate", tile = "dirt"} # ダンジョン選択ゲート
