# item ================

[[item]]
Name = "回復薬"
Description = "体力を半分程度回復する"
ProvidesHealing = 20

[item.consumable]
UsableScene = "ANY"
TargetFaction = "ALLY"
TargetNum = "SINGLE"

[[item]]
Name = "回復スプレー"
Description = "全員の体力を半分程度回復する"
ProvidesHealing = 20

[item.consumable]
UsableScene = "ANY"
TargetFaction = "ALLY"
TargetNum = "ALL"

[[item]]
Name = "手榴弾"
Description = "敵全体にダメージを与える"
InflictsDamage = 100

[item.consumable]
UsableScene = "BATTLE"
TargetFaction = "ENEMY"
TargetNum = "ALL"

# weapon ================

[[item]]
Name = "木刀"
Description = "旅行の土産でおなじみの木を削って作られた刀"

[item.weapon]
Accuracy = 100
BaseDamage = 8
AttackCount = 1
EnergyConsumption = 1

[[item]]
Name = "鉄のナイフ"
Description = "鉄で作られた小ぶりのナイフ"

[item.weapon]
Accuracy = 100
BaseDamage = 9
AttackCount = 1
EnergyConsumption = 1

[[item]]
Name = "ハンドガン"
Description = "樹脂素材を多用した自動拳銃"

[item.weapon]
Accuracy = 95
BaseDamage = 14
AttackCount = 1
EnergyConsumption = 2

[[item]]
Name = "レイガン"
Description = "光線を発射する拳銃"

[item.weapon]
Accuracy = 90
BaseDamage = 20
AttackCount = 1
EnergyConsumption = 3

# material ================

[[material]]
Name = "鉄くず"
Description = "鉄を多く含む金属の塊"

[[material]]
Name = "緑ハーブ"
Description = "よい香りに鎮静・興奮などの作用がある植物"

[[material]]
Name = "黄ハーブ"
Description = "体力を増強させる作用がある植物"

[[material]]
Name = "木の棒"
Description = "滑らかな表面を持ち、軽くて持ちやすい棒"

[[material]]
Name = "フェライトコア"
Description = "フェライト製の磁性体"

[[material]]
Name = "鉄"
Description = "加工しやすく産業の中核をなす金属"

# recipe ================

[[recipe]]
Name = "回復薬"

[[recipe.inputs]]
Name = "緑ハーブ"
Amount = 1

[[recipe.inputs]]
Name = "黄ハーブ"
Amount = 1

[[recipe]]
Name = "木刀"

[[recipe.inputs]]
Name = "木の棒"
Amount = 2

[[recipe]]
Name = "鉄のナイフ"

[[recipe.inputs]]
Name = "鉄"
Amount = 2

[[recipe.inputs]]
Name = "木の棒"
Amount = 2

[[recipe]]
Name = "レイガン"

[[recipe.inputs]]
Name = "鉄"
Amount = 4

[[recipe.inputs]]
Name = "フェライトコア"
Amount = 2

# member ================

[[member]]
Name = "村上"
HP = 101
SP = 82

[[member]]
Name = "白瀬"
HP = 82
SP = 87
