# item ================

[[item]]
Name = "ルビー原石"
Description = "赤く光る鉱物。高く売れる"

[[item]]
Name = "回復薬"
Description = "体力を半分程度回復する"

[item.consumable]
UsableScene = "ANY"
TargetGroup = "ALLY"
TargetNum = "SINGLE"

[item.provides_healing]
ValueType = "PERCENTAGE"
Ratio = 0.5

[[item]]
Name = "回復スプレー"
Description = "全員の体力を半分程度回復する"

[item.consumable]
UsableScene = "ANY"
TargetGroup = "ALLY"
TargetNum = "ALL"

[item.provides_healing]
ValueType = "PERCENTAGE"
Ratio = 0.5

[[item]]
Name = "手榴弾"
Description = "敵全体にダメージを与える"
InflictsDamage = 20

[item.consumable]
UsableScene = "BATTLE"
TargetGroup = "ENEMY"
TargetNum = "ALL"

# card ================

[[item]]
Name = "体当たり"
Description = "勢いをつけて体を接触させてダメージを与える"

[item.card]
Cost = 0
TargetGroup = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 100
Damage = 4
AttackCount = 1
Element = "NONE"
AttackCategory = "FIST"

[[item]]
Name = "木刀"
Description = "旅行の土産でおなじみの、木でできた刃のない刀"

[item.card]
Cost = 2
TargetGroup = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 100
Damage = 8
AttackCount = 1
Element = "NONE"
AttackCategory = "SWORD"

[[item]]
Name = "鉄のナイフ"
Description = "鉄で作られた軽いナイフ"

[item.card]
Cost = 2
TargetGroup = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 100
Damage = 9
AttackCount = 1
Element = "NONE"
AttackCategory = "SWORD"

[[item]]
Name = "ハンドガン"
Description = "樹脂素材を多用した自動拳銃"

[item.card]
Cost = 2
TargetGroup = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 95
Damage = 14
AttackCount = 1
Element = "NONE"
AttackCategory = "HANDGUN"

[[item]]
Name = "レイガン"
Description = "光線を発射する拳銃"

[item.card]
Cost = 2
TargetGroup = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 90
Damage = 20
AttackCount = 1
Element = "PHOTON"
AttackCategory = "HANDGUN"

[[item]]
Name = "電撃グレネード"
Description = "放電物質を投射する擲弾銃"

[item.card]
Cost = 3
TargetGroup = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 80
Damage = 26
AttackCount = 1
Element = "THUNDER"
AttackCategory = "RIFLE"

[[item]]
Name = "冷凍グレネード"
Description = "極低温物質を投射する擲弾銃"

[item.card]
Cost = 3
TargetGroup = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 80
Damage = 25
AttackCount = 1
Element = "CHILL"
AttackCategory = "RIFLE"

[[item]]
Name = "M72 LAW"
Description = "成形炸薬弾を投射する対戦車ロケット弾発射機"

[item.card]
Cost = 14
TargetGroup = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 85
Damage = 34
AttackCount = 1
Element = "NONE"
AttackCategory = "CANON"

[[item]]
Name = "50ミリ砲"
Description = "取り回しがよい車両用の大砲"

[item.card]
Cost = 14
TargetGroup = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 90
Damage = 34
AttackCount = 1
Element = "NONE"
AttackCategory = "CANON"

[[item]]
Name = "M1919重機関銃"
Description = "車載型の空冷式機関銃"

[item.card]
Cost = 10
TargetGroup = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 90
Damage = 8
AttackCount = 4
Element = "NONE"
AttackCategory = "CANON"

[[item]]
Name = "溶解液"
Description = "濃度の高い強酸性の液体"

[item.card]
Cost = 8
TargetGroup = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 80
Damage = 14
AttackCount = 1
Element = "NONE"
AttackCategory = "CANON"

# wearable ================

[[item]]
Name = "作業用ヘルメット"
Description = "衝撃吸収性に優れた産業用の帽子"

[item.wearable]
Defense = 4
EquipmentCategory = "HEAD"

[item.equip_bonus]
Vitality = 4
Agility = -2

[[item]]
Name = "西洋鎧"
Description = "伝統的な意匠が施されたずっしりと重い鎧"

[item.wearable]
Defense = 8
EquipmentCategory = "TORSO"

[item.equip_bonus]
Agility = -4

[[item]]
Name = "革のブーツ"
Description = "よくなめされた革で成形された長靴"

[item.wearable]
Defense = 3
EquipmentCategory = "LEGS"

[item.equip_bonus]
Agility = -2

[[item]]
Name = "機械の指輪"
Description = "指輪型の小さな機械"

[item.wearable]
Defense = 1
EquipmentCategory = "JEWELRY"

[item.equip_bonus]
Vitality = 1
Strength = 1
Sensation = 1
Dexterity = 1
Agility = 1

# material ================

[[material]]
Name = "鉄くず"
Description = "鉄を多く含む金属の塊"

[[material]]
Name = "緑ハーブ"
Description = "よい香りに鎮静・興奮などの作用がある植物"

[[material]]
Name = "黄ハーブ"
Description = "体力を増強させる作用がある植物"

[[material]]
Name = "木の棒"
Description = "滑らかな表面を持ち、軽くて持ちやすい棒"

[[material]]
Name = "フェライトコア"
Description = "フェライト製の磁性体"

[[material]]
Name = "鉄"
Description = "加工しやすく産業の中核をなす金属"

[[material]]
Name = "銀の欠片"
Description = "淡く光る銀色の金属片。不浄なものを退ける力があるとされる"

[[material]]
Name = "古い歯車"
Description = "錆びついた真鍮の歯車。精巧な工芸技術で作られている"

[[material]]
Name = "水晶の粉"
Description = "透明な結晶を砕いた粉末。微かに光を放っている"

[[material]]
Name = "黒曜石"
Description = "漆黒に輝く火山ガラス。鋭い刃を作るのに適している"

[[material]]
Name = "血赤石"
Description = "深紅に染まった鉱石。触れると温かい"

[[material]]
Name = "月光草"
Description = "夜に青白く光る神秘的な植物。薬草として珍重される"

[[material]]
Name = "古代の骨"
Description = "長い年月を経た動物の骨。異様に硬く軽い"

[[material]]
Name = "星鉄"
Description = "隕石から取れる特殊な金属。普通の鉄より遥かに硬い"

[[material]]
Name = "霧の結晶"
Description = "霧が結晶化したような不思議な物質。触れると冷たい"

[[material]]
Name = "古布の切れ端"
Description = "古い祭服の断片。聖別された布と思われる"

[[material]]
Name = "琥珀"
Description = "太古の樹液が化石化した宝石。中に小さな虫が閉じ込められている"

[[material]]
Name = "深海の塩"
Description = "深海から採取された特殊な塩。普通の塩とは違う効能がある"

[[material]]
Name = "雷光石"
Description = "雷に打たれて生まれた石。微かに電気を帯びている"

[[material]]
Name = "灰"
Description = "何かが燃え尽きた後の灰。神聖な儀式に使われていたようだ"

[[material]]
Name = "蒼鉛"
Description = "青みがかった重い金属。魔除けの効果があるとされる"

[[material]]
Name = "獣の毛皮"
Description = "未知の獣から剥いだ毛皮。非常に丈夫で防水性に優れる"

[[material]]
Name = "朽ちた羊皮紙"
Description = "古い文書の断片。文字は読めないが重要そうな内容"

[[material]]
Name = "紫水晶"
Description = "美しい紫色の水晶。精神を集中させる効果があるという"

[[material]]
Name = "錆びた鎖"
Description = "古い鎖の一部。何かを繋ぎ止めていた痕跡がある"

[[material]]
Name = "聖油"
Description = "聖別された油。武器や防具の祝福に使用される"

# recipe ================

[[recipe]]
Name = "回復薬"

[[recipe.inputs]]
Name = "緑ハーブ"
Amount = 1

[[recipe.inputs]]
Name = "黄ハーブ"
Amount = 1

[[recipe]]
Name = "木刀"

[[recipe.inputs]]
Name = "木の棒"
Amount = 2

[[recipe]]
Name = "鉄のナイフ"

[[recipe.inputs]]
Name = "鉄"
Amount = 2

[[recipe.inputs]]
Name = "木の棒"
Amount = 2

[[recipe]]
Name = "レイガン"

[[recipe.inputs]]
Name = "鉄"
Amount = 4

[[recipe.inputs]]
Name = "フェライトコア"
Amount = 2

[[recipe]]
Name = "電撃グレネード"

[[recipe.inputs]]
Name = "鉄"
Amount = 3

[[recipe]]
Name = "冷凍グレネード"

[[recipe.inputs]]
Name = "鉄"
Amount = 3

[[recipe]]
Name = "西洋鎧"

[[recipe.inputs]]
Name = "鉄"
Amount = 4

[[recipe]]
Name = "作業用ヘルメット"

[[recipe.inputs]]
Name = "鉄"
Amount = 3

[[recipe]]
Name = "革のブーツ"

[[recipe.inputs]]
Name = "鉄"
Amount = 2

[[recipe]]
Name = "機械の指輪"

[[recipe.inputs]]
Name = "鉄"
Amount = 1

# member ================

[[member]]
Name = "セレスティン"
Job = "探索者"
Player = true
[member.attributes]
Vitality = 7
Strength = 50
Sensation = 5
Dexterity = 6
Agility = 5
Defense = 0

[[member]]
Name = "コルデリア"
Job = "狩医者"
[member.attributes]
Vitality = 5
Strength = 40
Sensation = 8
Dexterity = 7
Agility = 7
Defense = 0

[[member]]
Name = "バルサザール"
Job = "脱走兵"
[member.attributes]
Vitality = 5
Strength = 5
Sensation = 5
Dexterity = 5
Agility = 5
Defense = 0

[[member]]
Name = "ハンス"
Job = "裁定者"
[member.attributes]
Vitality = 5
Strength = 5
Sensation = 5
Dexterity = 5
Agility = 5
Defense = 0

[[member]]
Name = "カイン"
Job = "石棺戦士"
[member.attributes]
Vitality = 5
Strength = 5
Sensation = 5
Dexterity = 5
Agility = 5
Defense = 0

[[member]]
Name = "メイ"
Job = "灰壺の守人"
[member.attributes]
Vitality = 5
Strength = 5
Sensation = 5
Dexterity = 5
Agility = 5
Defense = 0

[[member]]
Name = "アーサス"
Job = "歯車技師"
[member.attributes]
Vitality = 6
Strength = 4
Sensation = 8
Dexterity = 9
Agility = 6
Defense = 0

[[member]]
Name = "エヴァンジェリン"
Job = "従軍医官"
[member.attributes]
Vitality = 7
Strength = 3
Sensation = 9
Dexterity = 5
Agility = 4
Defense = 0

[[member]]
Name = "サイラス"
Job = "夜襲兵"
[member.attributes]
Vitality = 5
Strength = 6
Sensation = 7
Dexterity = 6
Agility = 9
Defense = 0

[[member]]
Name = "ベアトリス"
Job = "火薬調合師"
[member.attributes]
Vitality = 4
Strength = 7
Sensation = 6
Dexterity = 8
Agility = 5
Defense = 0

[[member]]
Name = "ガーディアン"
Job = "重鎧騎士"
[member.attributes]
Vitality = 8
Strength = 8
Sensation = 4
Dexterity = 3
Agility = 3
Defense = 0

[[member]]
Name = "セラフィナ"
Job = "密偵"
[member.attributes]
Vitality = 5
Strength = 4
Sensation = 8
Dexterity = 7
Agility = 7
Defense = 0

[[member]]
Name = "モルガン"
Job = "攻城兵"
[member.attributes]
Vitality = 6
Strength = 7
Sensation = 8
Dexterity = 5
Agility = 4
Defense = 0

[[member]]
Name = "メリディア"
Job = "伝令術師"
[member.attributes]
Vitality = 5
Strength = 4
Sensation = 9
Dexterity = 6
Agility = 8
Defense = 0

[[member]]
Name = "カスパー"
Job = "補給官"
[member.attributes]
Vitality = 7
Strength = 6
Sensation = 6
Dexterity = 5
Agility = 5
Defense = 0

[[member]]
Name = "レティシア"
Job = "精密射手"
[member.attributes]
Vitality = 4
Strength = 5
Sensation = 9
Dexterity = 8
Agility = 7
Defense = 0

[[member]]
Name = "軽戦車"
[member.attributes]
Vitality = 12
Strength = 8
Sensation = 5
Dexterity = 5
Agility = 5
Defense = 5

[[member]]
Name = "火の玉"
[member.attributes]
Vitality = 7
Strength = 8
Sensation = 4
Dexterity = 5
Agility = 6
Defense = 4

[[member]]
Name = "灰の偶像"
[member.attributes]
Vitality = 12
Strength = 23
Sensation = 5
Dexterity = 2
Agility = 3
Defense = 40

# command table ================

[[command_table]]
Name = "軽戦車"
[[command_table.entries]]
Card = "50ミリ砲"
Weight = 0.5
[[command_table.entries]]
Card = "M1919重機関銃"
Weight = 0.5

[[command_table]]
Name = "火の玉"
[[command_table.entries]]
Card = "体当たり"
Weight = 0.8
[[command_table.entries]]
Card = "溶解液"
Weight = 0.2

[[command_table]]
Name = "灰の偶像"
[[command_table.entries]]
Card = "体当たり"
Weight = 1.0

# drop table ================

[[drop_table]]
Name = "軽戦車"
XpBase = 10
[[ drop_table.entries]]
Material = "鉄"
Weight = 0.4
[[drop_table.entries]]
Material = "鉄くず"
Weight = 0.4
[[drop_table.entries]]
Material = "フェライトコア"
Weight = 0.2

[[drop_table]]
Name = "火の玉"
XpBase = 5
[[drop_table.entries]]
Material = "鉄くず"
Weight = 1.0

[[drop_table]]
Name = "灰の偶像"
XpBase = 50
[[drop_table.entries]]
Material = "鉄くず"
Weight = 1.0

# sheets ================

[[sprite_sheet]]
Name = "軽戦車"
[sprite_sheet.battle_body]
SheetName = "front_tank1"

[[sprite_sheet]]
Name = "火の玉"
[sprite_sheet.battle_body]
SheetName = "front_flame1"

[[sprite_sheet]]
Name = "灰の偶像"
[sprite_sheet.battle_body]
SheetName = "front_idol1"