[[item]]
Name = "回復薬"
Description = "体力を半分程度回復する"
Consumable = true
ProvidesHealing = 20

[[item]]
Name = "劇薬"
Description = "ダメージを与える"
Consumable = true
InflictsDamage = 50

[[item]]
Name = "手榴弾"
Description = "全体にダメージを与える"
Consumable = true

[[member]]
Name = "椿"
HP = 100
SP = 82

[[member]]
Name = "白瀬"
HP = 82
SP = 87
