# item ================

[[item]]
Name = "回復薬"
Description = "体力を半分程度回復する"
ProvidesHealing = 20

[item.consumable]
UsableScene = "ANY"
TargetFaction = "ALLY"
TargetNum = "SINGLE"

[[item]]
Name = "回復スプレー"
Description = "全員の体力を半分程度回復する"
ProvidesHealing = 20

[item.consumable]
UsableScene = "ANY"
TargetFaction = "ALLY"
TargetNum = "ALL"

[[item]]
Name = "劇薬"
Description = "ダメージを与える"
InflictsDamage = 50

[item.consumable]
UsableScene = "BATTLE"
TargetFaction = "ENEMY"
TargetNum = "SINGLE"

[[item]]
Name = "手榴弾"
Description = "全体にダメージを与える。全体にダメージを与える。"
InflictsDamage = 100

[item.consumable]
UsableScene = "BATTLE"
TargetFaction = "ENEMY"
TargetNum = "ALL"

# weapon ================

[[item]]
Name = "木刀"
Description = "木を削って作られた刀"

[item.weapon]
Accuracy = 100
BaseDamage = 10
AttackCount = 1
EnergyConsumption = 1

[[item]]
Name = "レイガン"
Description = "光線を発射する拳銃"

[item.weapon]
Accuracy = 90
BaseDamage = 20
AttackCount = 1
EnergyConsumption = 2

[[item]]
Name = "ファイヤガン"
Description = "炎の弾丸を発射する拳銃"

[item.weapon]
Accuracy = 90
BaseDamage = 22
AttackCount = 1
EnergyConsumption = 3

# material ================

[[material]]
Name = "鉄くず"
Description = "鉄を多く含む金属の塊"

[[material]]
Name = "緑のハーブ"
Description = "よい香りに鎮静・興奮などの作用がある植物"

[[material]]
Name = "フェライトコア"
Description = "フェライト製の磁性体"

# member ================

[[member]]
Name = "椿"
HP = 100
SP = 82

[[member]]
Name = "白瀬"
HP = 82
SP = 87
