# item ================

[[item]]
Name = "回復薬"
Description = "体力を半分程度回復する"

[item.consumable]
UsableScene = "ANY"
TargetFaction = "ALLY"
TargetNum = "SINGLE"

[item.provides_healing]
ValueType = "PERCENTAGE"
Ratio = 0.5

[[item]]
Name = "回復スプレー"
Description = "全員の体力を半分程度回復する"

[item.consumable]
UsableScene = "ANY"
TargetFaction = "ALLY"
TargetNum = "ALL"

[item.provides_healing]
ValueType = "PERCENTAGE"
Ratio = 0.5

[[item]]
Name = "手榴弾"
Description = "敵全体にダメージを与える"
InflictsDamage = 100

[item.consumable]
UsableScene = "BATTLE"
TargetFaction = "ENEMY"
TargetNum = "ALL"

# card ================

[[item]]
Name = "木刀"
Description = "旅行の土産でおなじみの、木でできた刃のない刀"

[item.card]
Cost = 2
TargetFaction = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 100
Damage = 8
AttackCount = 1
Element = "NONE"
AttackCategory = "SWORD"

[item.equip_bonus]
Strength = 1

[[item]]
Name = "鉄のナイフ"
Description = "鉄で作られた軽いナイフ"

[item.card]
Cost = 2
TargetFaction = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 100
Damage = 9
AttackCount = 1
Element = "NONE"
AttackCategory = "SWORD"

[[item]]
Name = "ハンドガン"
Description = "樹脂素材を多用した自動拳銃"

[item.card]
Cost = 2
TargetFaction = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 95
Damage = 14
AttackCount = 1
Element = "NONE"
AttackCategory = "HANDGUN"

[[item]]
Name = "レイガン"
Description = "光線を発射する拳銃"

[item.card]
Cost = 2
TargetFaction = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 90
Damage = 20
AttackCount = 1
Element = "PHOTON"
AttackCategory = "HANDGUN"

[[item]]
Name = "電撃グレネード"
Description = "放電物質を投射する擲弾銃"

[item.card]
Cost = 2
TargetFaction = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 80
Damage = 26
AttackCount = 1
Element = "THUNDER"
AttackCategory = "RIFLE"

[[item]]
Name = "冷凍グレネード"
Description = "極低温物質を投射する擲弾銃"

[item.card]
Cost = 2
TargetFaction = "ENEMY"
TargetNum = "SINGLE"

[item.attack]
Accuracy = 80
Damage = 25
AttackCount = 1
Element = "CHILL"
AttackCategory = "RIFLE"

# wearable ================

[[item]]
Name = "作業用ヘルメット"
Description = "衝撃吸収性に優れた産業用の帽子"

[item.wearable]
Defense = 10
EquipmentCategory = "HEAD"

[item.equip_bonus]
Vitality = 4
Agility = -2

[[item]]
Name = "西洋鎧"
Description = "伝統的な意匠が施されたずっしりと重い鎧"

[item.wearable]
Defense = 16
EquipmentCategory = "TORSO"

[item.equip_bonus]
Agility = -4

[[item]]
Name = "革のブーツ"
Description = "よくなめされた革で成形された長靴"

[item.wearable]
Defense = 5
EquipmentCategory = "LEGS"

[item.equip_bonus]
Agility = -2

[[item]]
Name = "機械の指輪"
Description = "指輪型の小さな機械"

[item.wearable]
Defense = 1
EquipmentCategory = "JEWELRY"

[item.equip_bonus]
Vitality = 1
Strength = 1
Sensation = 1
Dexterity = 1
Agility = 1

# material ================

[[material]]
Name = "鉄くず"
Description = "鉄を多く含む金属の塊"

[[material]]
Name = "緑ハーブ"
Description = "よい香りに鎮静・興奮などの作用がある植物"

[[material]]
Name = "黄ハーブ"
Description = "体力を増強させる作用がある植物"

[[material]]
Name = "木の棒"
Description = "滑らかな表面を持ち、軽くて持ちやすい棒"

[[material]]
Name = "フェライトコア"
Description = "フェライト製の磁性体"

[[material]]
Name = "鉄"
Description = "加工しやすく産業の中核をなす金属"

# recipe ================

[[recipe]]
Name = "回復薬"

[[recipe.inputs]]
Name = "緑ハーブ"
Amount = 1

[[recipe.inputs]]
Name = "黄ハーブ"
Amount = 1

[[recipe]]
Name = "木刀"

[[recipe.inputs]]
Name = "木の棒"
Amount = 2

[[recipe]]
Name = "鉄のナイフ"

[[recipe.inputs]]
Name = "鉄"
Amount = 2

[[recipe.inputs]]
Name = "木の棒"
Amount = 2

[[recipe]]
Name = "レイガン"

[[recipe.inputs]]
Name = "鉄"
Amount = 4

[[recipe.inputs]]
Name = "フェライトコア"
Amount = 2

[[recipe]]
Name = "電撃グレネード"

[[recipe.inputs]]
Name = "鉄"
Amount = 3

[[recipe]]
Name = "冷凍グレネード"

[[recipe.inputs]]
Name = "鉄"
Amount = 3

[[recipe]]
Name = "西洋鎧"

[[recipe.inputs]]
Name = "鉄"
Amount = 4

[[recipe]]
Name = "作業用ヘルメット"

[[recipe.inputs]]
Name = "鉄"
Amount = 3

[[recipe]]
Name = "革のブーツ"

[[recipe.inputs]]
Name = "鉄"
Amount = 2

[[recipe]]
Name = "機械の指輪"

[[recipe.inputs]]
Name = "鉄"
Amount = 1

# member ================

[[member]]
Name = "イシハラ"
[member.attributes]
Vitality = 7
Strength = 5
Sensation = 5
Dexterity = 6
Agility = 5
Defense = 0

[[member]]
Name = "シラセ"
[member.attributes]
Vitality = 5
Strength = 4
Sensation = 8
Dexterity = 7
Agility = 7
Defense = 0