[[item]]
Name = "回復薬"
Description = "体力を半分程度回復する"
ProvidesHealing = 20

[item.consumable]
UsableScene = "ANY"
TargetFaction = "ALLY"
TargetWhole = false

[[item]]
Name = "回復スプレー"
Description = "全員の体力を半分程度回復する"
ProvidesHealing = 20

[item.consumable]
UsableScene = "ANY"
TargetFaction = "ALLY"
TargetWhole = true

[[item]]
Name = "劇薬"
Description = "ダメージを与える"
InflictsDamage = 50

[item.consumable]
UsableScene = "BATTLE"
TargetFaction = "ENEMY"
TargetWhole = false

[[item]]
Name = "手榴弾"
Description = "全体にダメージを与える"
InflictsDamage = 100

[item.consumable]
UsableScene = "BATTLE"
TargetFaction = "ENEMY"
TargetWhole = true

[[member]]
Name = "椿"
HP = 100
SP = 82

[[member]]
Name = "白瀬"
HP = 82
SP = 87
