name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install semantic-release
        run: npm install -g semantic-release@24.1.2
      - name: Releaser
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: semantic-release
