name: WASM Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Build
        run: |
          docker build --target builder -t testimage .
          docker run --rm -v ${PWD}:/app -w /app testimage bash -c "env GOOS=js GOARCH=wasm go build -o ./wasm/game.wasm -buildvcs=false"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Generate godoc
        run: |
          go install golang.org/x/tools/cmd/godoc@v0.24.0
          $(go env GOPATH)/bin/godoc -http=localhost:8888 & \
          sleep 30
          wget -r -np -nv -N -E -p -k -e robots=off --reject-regex="png" "http://localhost:8888/pkg/github.com/kijimaD/ruins/"
          pkill godoc
          mv localhost:8888/ ./wasm/godoc/

      - name: Check
        run: |
          ls -al ./wasm
          ls -al ./wasm/godoc

      - name: Publish generated content to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          branch: gh-pages
          folder: wasm
