name: WASM Build

on:
  push:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # タグ情報を取得するために全履歴を取得

      - name: Build
        run: ./scripts/build.sh

      - name: Set up Go
        uses: actions/setup-go@v6

      - name: Generate godoc
        run: |
          go install golang.org/x/tools/cmd/godoc@v0.24.0
          $(go env GOPATH)/bin/godoc -http=localhost:8888 & \
          sleep 60
          wget -r -np -nv -N -E -p -k -e robots=off --reject-regex="png" "http://localhost:8888/pkg/github.com/kijimaD/ruins/"
          pkill godoc
          mv localhost:8888/ ./wasm/godoc/

      - name: Check
        run: |
          ls -al ./wasm
          ls -al ./wasm/godoc

      - name: Publish generated content to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: wasm
